============ initial translation from Move ================

fun TestSpecBlock::looping(x: u64): u64 {
     var $t1: u64
     var $t2: u64
     var $t3: bool
     var $t4: u64
     var $t5: u64
     var $t6: u64
     var $t7: u64
  0: spec at 592..616
  1: goto L3
  2: L3:
  3: $t1 := copy(x)
  4: $t2 := 10
  5: $t3 := <($t1, $t2)
  6: if ($t3) goto L0 else goto L1
  7: L1:
  8: goto L2
  9: L0:
 10: spec at 653..676
 11: $t4 := copy(x)
 12: $t5 := 1
 13: $t6 := +($t4, $t5)
 14: x := $t6
 15: goto L3
 16: L2:
 17: spec at 718..742
 18: $t7 := copy(x)
 19: return $t7
}


fun TestSpecBlock::simple1(x: u64, y: u64) {
     var $t2: u64
     var $t3: u64
     var $t4: bool
     var $t5: bool
     var $t6: u64
  0: $t2 := copy(x)
  1: $t3 := copy(y)
  2: $t4 := >($t2, $t3)
  3: $t5 := !($t4)
  4: if ($t5) goto L0 else goto L1
  5: L1:
  6: goto L2
  7: L0:
  8: $t6 := 1
  9: abort($t6)
 10: L2:
 11: spec at 97..139
 12: return ()
}


fun TestSpecBlock::simple2(x: u64) {
     var y: u64
     var $t2: u64
     var $t3: u64
     var $t4: u64
  0: $t2 := copy(x)
  1: $t3 := 1
  2: $t4 := +($t2, $t3)
  3: y := $t4
  4: spec at 220..267
  5: return ()
}


fun TestSpecBlock::simple3(x: u64, y: u64) {
  0: spec at 317..386
  1: return ()
}


fun TestSpecBlock::simple4(x: u64, y: u64) {
     var z: u64
     var $t3: u64
     var $t4: u64
     var $t5: u64
  0: $t3 := copy(x)
  1: $t4 := copy(y)
  2: $t5 := +($t3, $t4)
  3: z := $t5
  4: spec at 475..545
  5: return ()
}
