Command `sandbox test dummy/test_1/args.txt`:
1 / 1 test(s) passed.
Command `sandbox test dummy/test_2`:
1 / 1 test(s) passed.
Command `sandbox test dummy`:
2 / 2 test(s) passed.
Command `sandbox test cov/plain --track-cov`:
1 / 1 test(s) passed.
Module 00000000000000000000000000000042::M
	fun test
		total: 1
		covered: 1
		% coverage: 100.00
>>> % Module coverage: 100.00
Command `sandbox test cov/two-runs-same-module --track-cov`:
1 / 1 test(s) passed.
Module 00000000000000000000000000000042::M
	fun test
		total: 7
		covered: 7
		% coverage: 100.00
>>> % Module coverage: 100.00
Command `sandbox test cov/two-runs-diff-module --track-cov`:
1 / 1 test(s) passed.
Module 00000000000000000000000000000042::M1
	fun test
		total: 1
		covered: 1
		% coverage: 100.00
>>> % Module coverage: 100.00
Module 00000000000000000000000000000042::M2
	fun test
		total: 1
		covered: 1
		% coverage: 100.00
>>> % Module coverage: 100.00
