warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/typing/borrow_divergent.move:4:13
  │
4 │            &break;
  │             ^^^^^ Invalid use of a divergent expression. The code following the evaluation of this expression will be dead and should be removed.

warning[W09005]: dead or unreachable code
   ┌─ tests/move_check/typing/borrow_divergent.move:11:12
   │
11 │         &{ return };
   │            ^^^^^^ Invalid use of a divergent expression. The code following the evaluation of this expression will be dead and should be removed.

warning[W09005]: dead or unreachable code
   ┌─ tests/move_check/typing/borrow_divergent.move:18:10
   │
18 │         &(if (cond) return else return);
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid use of a divergent expression. The code following the evaluation of this expression will be dead and should be removed.

