warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/typing/break_any_type.move:6:17
  │
6 │             0 + break;
  │                 ^^^^^ Invalid use of a divergent expression. The code following the evaluation of this expression will be dead and should be removed.

warning[W09005]: dead or unreachable code
   ┌─ tests/move_check/typing/break_any_type.move:12:17
   │
12 │             foo(break)
   │                 ^^^^^ Invalid use of a divergent expression. The code following the evaluation of this expression will be dead and should be removed.

