error[E04007]: incompatible types
   ┌─ tests/move_check/typing/constant_invalid_usage.move:11:20
   │
 8 │     const C6: vector<u8> = x"0123";
   │               ---------- Given: 'vector<u8>'
   ·
11 │     fun t1(): u8 { C6 }
   │               --   ^^ Invalid return expression
   │               │     
   │               Expected: 'u8'

error[E04007]: incompatible types
   ┌─ tests/move_check/typing/constant_invalid_usage.move:12:21
   │
 9 │     const C7: vector<u8> = b"abcd";
   │               ---------- Given: 'vector<u8>'
   ·
12 │     fun t2(): u64 { C7 }
   │               ---   ^^ Invalid return expression
   │               │      
   │               Expected: 'u64'

error[E04007]: incompatible types
   ┌─ tests/move_check/typing/constant_invalid_usage.move:13:22
   │
 3 │     const C1: u8 = 0;
   │               -- Given: 'u8'
   ·
13 │     fun t3(): u128 { C1 }
   │               ----   ^^ Invalid return expression
   │               │       
   │               Expected: 'u128'

error[E04007]: incompatible types
   ┌─ tests/move_check/typing/constant_invalid_usage.move:14:22
   │
 4 │     const C2: u64 = 0;
   │               --- Given: 'u64'
   ·
14 │     fun t4(): bool { C2 }
   │               ----   ^^ Invalid return expression
   │               │       
   │               Expected: 'bool'

error[E04007]: incompatible types
   ┌─ tests/move_check/typing/constant_invalid_usage.move:15:25
   │
 5 │     const C3: u128 = 0;
   │               ---- Given: 'u128'
   ·
15 │     fun t5(): address { C3 }
   │               -------   ^^ Invalid return expression
   │               │          
   │               Expected: 'address'

error[E04007]: incompatible types
   ┌─ tests/move_check/typing/constant_invalid_usage.move:16:28
   │
 6 │     const C4: bool = false;
   │               ---- Given: 'bool'
   ·
16 │     fun t6(): vector<u8> { C4 }
   │               ----------   ^^ Invalid return expression
   │               │             
   │               Expected: 'vector<u8>'

error[E04007]: incompatible types
   ┌─ tests/move_check/typing/constant_invalid_usage.move:17:28
   │
 7 │     const C5: address = @0x0;
   │               ------- Given: 'address'
   ·
17 │     fun t7(): vector<u8> { C5 }
   │               ----------   ^^ Invalid return expression
   │               │             
   │               Expected: 'vector<u8>'

