[0] Transaction(0)
[1] Move VM Status: EXECUTED
[2] Transaction Status: Keep(EXECUTED)
[3] Transaction(1)
[4] Move VM Status: ABORTED { code: 1, location: 00000000000000000000000000000001::DiemTimestamp }
[5] Transaction Status: Keep(ABORTED { code: 1, location: 00000000000000000000000000000001::DiemTimestamp })
[6] Transaction(2)
[7] Move VM Status: EXECUTED
[8] Transaction Status: Keep(EXECUTED)
[9] Transaction(3)
[10] Move VM Status: ABORTED { code: 262, location: 00000000000000000000000000000001::AccountLimits }
[11] Transaction Status: Discard(INVALID_WRITE_SET)
[12] Transaction(4)
[13] Move VM Status: ABORTED { code: 2, location: 00000000000000000000000000000001::CoreAddresses }
[14] Transaction Status: Keep(ABORTED { code: 2, location: 00000000000000000000000000000001::CoreAddresses })
[15] Transaction(5)
[16] Move VM Status: ABORTED { code: 6, location: 00000000000000000000000000000001::AccountLimits }
[17] Transaction Status: Keep(ABORTED { code: 6, location: 00000000000000000000000000000001::AccountLimits })
[18] Transaction(6)
[19] Move VM Status: EXECUTED
[20] Transaction Status: Keep(EXECUTED)
[21] Transaction(7)
[22] Move VM Status: ABORTED { code: 258, location: 00000000000000000000000000000001::CoreAddresses }
[23] Transaction Status: Keep(ABORTED { code: 258, location: 00000000000000000000000000000001::CoreAddresses })
[24] Transaction(8)
[25] Move VM Status: EXECUTED
[26] Transaction Status: Keep(EXECUTED)
[27] Transaction(9)
[28] Move VM Status: ABORTED { code: 5, location: 00000000000000000000000000000001::AccountLimits }
[29] Transaction Status: Keep(ABORTED { code: 5, location: 00000000000000000000000000000001::AccountLimits })
[30] Transaction(10)
[31] Move VM Status: EXECUTED
[32] Transaction Status: Keep(EXECUTED)
[33] Transaction(11)
[34] Move VM Status: EXECUTED
[35] Transaction Status: Keep(EXECUTED)
[36] Transaction(12)
[37] Move VM Status: EXECUTED
[38] Transaction Status: Keep(EXECUTED)
[39] Transaction(13)
[40] Move VM Status: ABORTED { code: 5, location: 00000000000000000000000000000001::AccountLimits }
[41] Transaction Status: Keep(ABORTED { code: 5, location: 00000000000000000000000000000001::AccountLimits })
[42] Transaction(14)
[43] Move VM Status: ABORTED { code: 258, location: 00000000000000000000000000000001::CoreAddresses }
[44] Transaction Status: Keep(ABORTED { code: 258, location: 00000000000000000000000000000001::CoreAddresses })
[45] Transaction(15)
[46] Move VM Status: EXECUTED
[47] Transaction Status: Keep(EXECUTED)
[48] Transaction(16)
[49] Move VM Status: EXECUTED
[50] Transaction Status: Keep(EXECUTED)
[51] Transaction(17)
[52] Move VM Status: ABORTED { code: 5, location: 00000000000000000000000000000001::AccountLimits }
[53] Transaction Status: Discard(INVALID_WRITE_SET)
