============ initial translation from Move ================

fun TestLifetime::lifetime_(cond: bool): (TestLifetime::T, TestLifetime::S) {
     var a: TestLifetime::T
     var a_ref: &mut TestLifetime::T
     var b: TestLifetime::S
     var b_ref: &mut TestLifetime::S
     var tmp#$5: &mut u64
     var x_ref: &mut u64
     var $t7: u64
     var $t8: TestLifetime::T
     var $t9: u64
     var $t10: TestLifetime::S
     var $t11: &mut TestLifetime::T
     var $t12: &mut TestLifetime::S
     var $t13: bool
     var $t14: &mut TestLifetime::S
     var $t15: &mut TestLifetime::T
     var $t16: &mut u64
     var $t17: &mut TestLifetime::T
     var $t18: &mut TestLifetime::S
     var $t19: &mut u64
     var $t20: &mut u64
     var $t21: bool
     var $t22: u64
     var $t23: &mut u64
     var $t24: u64
     var $t25: &mut u64
     var $t26: TestLifetime::T
     var $t27: TestLifetime::S
  0: $t7 := 3
  1: $t8 := pack TestLifetime::T($t7)
  2: a := $t8
  3: $t9 := 4
  4: $t10 := pack TestLifetime::S($t9)
  5: b := $t10
  6: $t11 := borrow_local(a)
  7: a_ref := $t11
  8: $t12 := borrow_local(b)
  9: b_ref := $t12
 10: $t13 := copy(cond)
 11: if ($t13) goto L0 else goto L1
 12: L1:
 13: goto L2
 14: L0:
 15: $t14 := move(b_ref)
 16: destroy($t14)
 17: $t15 := move(a_ref)
 18: $t16 := borrow_field<TestLifetime::T>.x($t15)
 19: tmp#$5 := $t16
 20: goto L3
 21: L2:
 22: $t17 := move(a_ref)
 23: destroy($t17)
 24: $t18 := move(b_ref)
 25: $t19 := borrow_field<TestLifetime::S>.y($t18)
 26: tmp#$5 := $t19
 27: goto L3
 28: L3:
 29: $t20 := move(tmp#$5)
 30: x_ref := $t20
 31: $t21 := copy(cond)
 32: if ($t21) goto L4 else goto L5
 33: L5:
 34: goto L6
 35: L4:
 36: $t22 := 2
 37: $t23 := move(x_ref)
 38: write_ref($t23, $t22)
 39: goto L7
 40: L6:
 41: $t24 := 0
 42: $t25 := move(x_ref)
 43: write_ref($t25, $t24)
 44: goto L7
 45: L7:
 46: $t26 := move(a)
 47: $t27 := move(b)
 48: return ($t26, $t27)
}


fun TestLifetime::lifetime_R(): TestLifetime::R {
     var r: TestLifetime::R
     var r_ref: &mut TestLifetime::R
     var x_ref: &mut u64
     var $t3: u64
     var $t4: TestLifetime::R
     var $t5: &mut TestLifetime::R
     var $t6: &mut TestLifetime::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: &mut TestLifetime::R
     var $t11: &mut TestLifetime::R
     var $t12: &mut u64
     var $t13: u64
     var $t14: &mut u64
     var $t15: TestLifetime::R
  0: $t3 := 3
  1: $t4 := pack TestLifetime::R($t3)
  2: r := $t4
  3: $t5 := borrow_local(r)
  4: r_ref := $t5
  5: $t6 := move(r_ref)
  6: $t7 := borrow_field<TestLifetime::R>.x($t6)
  7: x_ref := $t7
  8: $t8 := 0
  9: $t9 := move(x_ref)
 10: write_ref($t9, $t8)
 11: $t10 := borrow_local(r)
 12: r_ref := $t10
 13: $t11 := move(r_ref)
 14: $t12 := borrow_field<TestLifetime::R>.x($t11)
 15: x_ref := $t12
 16: $t13 := 2
 17: $t14 := move(x_ref)
 18: write_ref($t14, $t13)
 19: $t15 := move(r)
 20: return $t15
}


fun TestLifetime::lifetime_R_2(): TestLifetime::R {
     var r: TestLifetime::R
     var r_ref: &mut TestLifetime::R
     var x_ref: &mut u64
     var $t3: u64
     var $t4: TestLifetime::R
     var $t5: &mut TestLifetime::R
     var $t6: &mut TestLifetime::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: u64
     var $t11: &mut u64
     var $t12: &mut TestLifetime::R
     var $t13: &mut TestLifetime::R
     var $t14: &mut u64
     var $t15: u64
     var $t16: &mut u64
     var $t17: TestLifetime::R
  0: $t3 := 4
  1: $t4 := pack TestLifetime::R($t3)
  2: r := $t4
  3: $t5 := borrow_local(r)
  4: r_ref := $t5
  5: $t6 := move(r_ref)
  6: $t7 := borrow_field<TestLifetime::R>.x($t6)
  7: x_ref := $t7
  8: $t8 := 0
  9: $t9 := copy(x_ref)
 10: write_ref($t9, $t8)
 11: $t10 := 2
 12: $t11 := move(x_ref)
 13: write_ref($t11, $t10)
 14: $t12 := borrow_local(r)
 15: r_ref := $t12
 16: $t13 := move(r_ref)
 17: $t14 := borrow_field<TestLifetime::R>.x($t13)
 18: x_ref := $t14
 19: $t15 := 3
 20: $t16 := move(x_ref)
 21: write_ref($t16, $t15)
 22: $t17 := move(r)
 23: return $t17
}

============ after pipeline `lifetime` ================

fun TestLifetime::lifetime_(cond: bool): (TestLifetime::T, TestLifetime::S) {
     var a: TestLifetime::T
     var a_ref: &mut TestLifetime::T
     var b: TestLifetime::S
     var b_ref: &mut TestLifetime::S
     var tmp#$5: &mut u64
     var x_ref: &mut u64
     var $t7: u64
     var $t8: TestLifetime::T
     var $t9: u64
     var $t10: TestLifetime::S
     var $t11: &mut TestLifetime::T
     var $t12: &mut TestLifetime::S
     var $t13: bool
     var $t14: &mut TestLifetime::S
     var $t15: &mut TestLifetime::T
     var $t16: &mut u64
     var $t17: &mut TestLifetime::T
     var $t18: &mut TestLifetime::S
     var $t19: &mut u64
     var $t20: &mut u64
     var $t21: bool
     var $t22: u64
     var $t23: &mut u64
     var $t24: u64
     var $t25: &mut u64
     var $t26: TestLifetime::T
     var $t27: TestLifetime::S
  0: $t7 := 3
  1: $t8 := pack TestLifetime::T($t7)
  2: a := $t8
  3: $t9 := 4
  4: $t10 := pack TestLifetime::S($t9)
  5: b := $t10
  6: $t11 := borrow_local(a)
  7: a_ref := $t11
  8: $t12 := borrow_local(b)
  9: b_ref := $t12
 10: $t13 := copy(cond)
 11: if ($t13) goto L0 else goto L1
 12: L1:
 13: goto L2
 14: L0:
 15: $t14 := move(b_ref)
     // mut ends: $t14
 16: destroy($t14)
 17: $t15 := move(a_ref)
 18: $t16 := borrow_field<TestLifetime::T>.x($t15)
 19: tmp#$5 := $t16
 20: goto L3
 21: L2:
 22: $t17 := move(a_ref)
     // mut ends: $t17
 23: destroy($t17)
 24: $t18 := move(b_ref)
 25: $t19 := borrow_field<TestLifetime::S>.y($t18)
 26: tmp#$5 := $t19
 27: goto L3
 28: L3:
 29: $t20 := move(tmp#$5)
 30: x_ref := $t20
 31: $t21 := copy(cond)
 32: if ($t21) goto L4 else goto L5
 33: L5:
 34: goto L6
 35: L4:
 36: $t22 := 2
 37: $t23 := move(x_ref)
     // mut ends: $t15, $t18, $t23
 38: write_ref($t23, $t22)
 39: goto L7
 40: L6:
 41: $t24 := 0
 42: $t25 := move(x_ref)
     // mut ends: $t15, $t18, $t25
 43: write_ref($t25, $t24)
 44: goto L7
 45: L7:
 46: $t26 := move(a)
 47: $t27 := move(b)
 48: return ($t26, $t27)
}


fun TestLifetime::lifetime_R(): TestLifetime::R {
     var r: TestLifetime::R
     var r_ref: &mut TestLifetime::R
     var x_ref: &mut u64
     var $t3: u64
     var $t4: TestLifetime::R
     var $t5: &mut TestLifetime::R
     var $t6: &mut TestLifetime::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: &mut TestLifetime::R
     var $t11: &mut TestLifetime::R
     var $t12: &mut u64
     var $t13: u64
     var $t14: &mut u64
     var $t15: TestLifetime::R
  0: $t3 := 3
  1: $t4 := pack TestLifetime::R($t3)
  2: r := $t4
  3: $t5 := borrow_local(r)
  4: r_ref := $t5
  5: $t6 := move(r_ref)
  6: $t7 := borrow_field<TestLifetime::R>.x($t6)
  7: x_ref := $t7
  8: $t8 := 0
  9: $t9 := move(x_ref)
     // mut ends: $t6, $t9
 10: write_ref($t9, $t8)
 11: $t10 := borrow_local(r)
 12: r_ref := $t10
 13: $t11 := move(r_ref)
 14: $t12 := borrow_field<TestLifetime::R>.x($t11)
 15: x_ref := $t12
 16: $t13 := 2
 17: $t14 := move(x_ref)
     // mut ends: $t11, $t14
 18: write_ref($t14, $t13)
 19: $t15 := move(r)
 20: return $t15
}


fun TestLifetime::lifetime_R_2(): TestLifetime::R {
     var r: TestLifetime::R
     var r_ref: &mut TestLifetime::R
     var x_ref: &mut u64
     var $t3: u64
     var $t4: TestLifetime::R
     var $t5: &mut TestLifetime::R
     var $t6: &mut TestLifetime::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: u64
     var $t11: &mut u64
     var $t12: &mut TestLifetime::R
     var $t13: &mut TestLifetime::R
     var $t14: &mut u64
     var $t15: u64
     var $t16: &mut u64
     var $t17: TestLifetime::R
  0: $t3 := 4
  1: $t4 := pack TestLifetime::R($t3)
  2: r := $t4
  3: $t5 := borrow_local(r)
  4: r_ref := $t5
  5: $t6 := move(r_ref)
  6: $t7 := borrow_field<TestLifetime::R>.x($t6)
  7: x_ref := $t7
  8: $t8 := 0
  9: $t9 := copy(x_ref)
 10: write_ref($t9, $t8)
 11: $t10 := 2
 12: $t11 := move(x_ref)
     // mut ends: $t6, $t11
 13: write_ref($t11, $t10)
 14: $t12 := borrow_local(r)
 15: r_ref := $t12
 16: $t13 := move(r_ref)
 17: $t14 := borrow_field<TestLifetime::R>.x($t13)
 18: x_ref := $t14
 19: $t15 := 3
 20: $t16 := move(x_ref)
     // mut ends: $t13, $t16
 21: write_ref($t16, $t15)
 22: $t17 := move(r)
 23: return $t17
}
