Move prover returns: exiting with boogie verification errors
error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:34:5 ───
    │
 34 │ ╭     invariant
 35 │ │         exists<S::Storage<u64, bool>>(@0x22)
 36 │ │             ==> global<S::Storage<u64, bool>>(@0x22).x == 1;
    │ ╰────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:10: publish_u64_bool
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:11: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:10: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:11: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:34

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:39:5 ───
    │
 39 │ ╭     invariant
 40 │ │         forall t: type:
 41 │ │             exists<S::Storage<u64, t>>(@0x23)
 42 │ │                 ==> global<S::Storage<u64, t>>(@0x23).x > 0;
    │ ╰────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:10: publish_u64_bool
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:11: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:10: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:11: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:45:5 ───
    │
 45 │ ╭     invariant
 46 │ │         forall t: type:
 47 │ │             exists<S::Storage<t, bool>>(@0x24)
 48 │ │                 ==> global<S::Storage<t, bool>>(@0x24).y;
    │ ╰─────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:10: publish_u64_bool
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:11: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:10: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:11: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39
    =     at tests/sources/functional/invariants_with_generics.move:45

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:51:5 ───
    │
 51 │ ╭     invariant
 52 │ │         forall t1: type, t2: type:
 53 │ │             (exists<S::Storage<t1, t2>>(@0x25) && exists<S::Storage<t1, t2>>(@0x26))
 54 │ │                 ==> global<S::Storage<t1, t2>>(@0x25) == global<S::Storage<t1, t2>>(@0x26);
    │ ╰───────────────────────────────────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:10: publish_u64_bool
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:11: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:10: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:11: publish_u64_bool
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39
    =     at tests/sources/functional/invariants_with_generics.move:45
    =     at tests/sources/functional/invariants_with_generics.move:51

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:39:5 ───
    │
 39 │ ╭     invariant
 40 │ │         forall t: type:
 41 │ │             exists<S::Storage<u64, t>>(@0x23)
 42 │ │                 ==> global<S::Storage<u64, t>>(@0x23).x > 0;
    │ ╰────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:15: publish_u64_y
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:16: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:15: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:16: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:51:5 ───
    │
 51 │ ╭     invariant
 52 │ │         forall t1: type, t2: type:
 53 │ │             (exists<S::Storage<t1, t2>>(@0x25) && exists<S::Storage<t1, t2>>(@0x26))
 54 │ │                 ==> global<S::Storage<t1, t2>>(@0x25) == global<S::Storage<t1, t2>>(@0x26);
    │ ╰───────────────────────────────────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:15: publish_u64_y
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:16: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:15: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:16: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39
    =     at tests/sources/functional/invariants_with_generics.move:45
    =     at tests/sources/functional/invariants_with_generics.move:51

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:34:5 ───
    │
 34 │ ╭     invariant
 35 │ │         exists<S::Storage<u64, bool>>(@0x22)
 36 │ │             ==> global<S::Storage<u64, bool>>(@0x22).x == 1;
    │ ╰────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:15: publish_u64_y
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:16: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:15: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:16: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:34

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:45:5 ───
    │
 45 │ ╭     invariant
 46 │ │         forall t: type:
 47 │ │             exists<S::Storage<t, bool>>(@0x24)
 48 │ │                 ==> global<S::Storage<t, bool>>(@0x24).y;
    │ ╰─────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:15: publish_u64_y
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:16: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:15: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:16: publish_u64_y
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39
    =     at tests/sources/functional/invariants_with_generics.move:45

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:45:5 ───
    │
 45 │ ╭     invariant
 46 │ │         forall t: type:
 47 │ │             exists<S::Storage<t, bool>>(@0x24)
 48 │ │                 ==> global<S::Storage<t, bool>>(@0x24).y;
    │ ╰─────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:20: publish_x_bool
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:21: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:20: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:21: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39
    =     at tests/sources/functional/invariants_with_generics.move:45

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:51:5 ───
    │
 51 │ ╭     invariant
 52 │ │         forall t1: type, t2: type:
 53 │ │             (exists<S::Storage<t1, t2>>(@0x25) && exists<S::Storage<t1, t2>>(@0x26))
 54 │ │                 ==> global<S::Storage<t1, t2>>(@0x25) == global<S::Storage<t1, t2>>(@0x26);
    │ ╰───────────────────────────────────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:20: publish_x_bool
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:21: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:20: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:21: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39
    =     at tests/sources/functional/invariants_with_generics.move:45
    =     at tests/sources/functional/invariants_with_generics.move:51

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:34:5 ───
    │
 34 │ ╭     invariant
 35 │ │         exists<S::Storage<u64, bool>>(@0x22)
 36 │ │             ==> global<S::Storage<u64, bool>>(@0x22).x == 1;
    │ ╰────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:20: publish_x_bool
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:21: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:20: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:21: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:34

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:39:5 ───
    │
 39 │ ╭     invariant
 40 │ │         forall t: type:
 41 │ │             exists<S::Storage<u64, t>>(@0x23)
 42 │ │                 ==> global<S::Storage<u64, t>>(@0x23).x > 0;
    │ ╰────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:20: publish_x_bool
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:21: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:20: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:21: publish_x_bool
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:51:5 ───
    │
 51 │ ╭     invariant
 52 │ │         forall t1: type, t2: type:
 53 │ │             (exists<S::Storage<t1, t2>>(@0x25) && exists<S::Storage<t1, t2>>(@0x26))
 54 │ │                 ==> global<S::Storage<t1, t2>>(@0x25) == global<S::Storage<t1, t2>>(@0x26);
    │ ╰───────────────────────────────────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:25: publish_x_y
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:26: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:25: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:26: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39
    =     at tests/sources/functional/invariants_with_generics.move:45
    =     at tests/sources/functional/invariants_with_generics.move:51

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:39:5 ───
    │
 39 │ ╭     invariant
 40 │ │         forall t: type:
 41 │ │             exists<S::Storage<u64, t>>(@0x23)
 42 │ │                 ==> global<S::Storage<u64, t>>(@0x23).x > 0;
    │ ╰────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:25: publish_x_y
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:26: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:25: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:26: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:34:5 ───
    │
 34 │ ╭     invariant
 35 │ │         exists<S::Storage<u64, bool>>(@0x22)
 36 │ │             ==> global<S::Storage<u64, bool>>(@0x22).x == 1;
    │ ╰────────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:25: publish_x_y
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:26: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:25: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:26: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:34

error: global memory invariant does not hold

    ┌── tests/sources/functional/invariants_with_generics.move:45:5 ───
    │
 45 │ ╭     invariant
 46 │ │         forall t: type:
 47 │ │             exists<S::Storage<t, bool>>(@0x24)
 48 │ │                 ==> global<S::Storage<t, bool>>(@0x24).y;
    │ ╰─────────────────────────────────────────────────────────^
    │
    =     at tests/sources/functional/invariants_with_generics.move:25: publish_x_y
    =         account = <redacted>
    =         x = <redacted>
    =         y = <redacted>
    =     at tests/sources/functional/invariants_with_generics.move:26: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:25: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:26: publish_x_y
    =     at tests/sources/functional/invariants_with_generics.move:34
    =     at tests/sources/functional/invariants_with_generics.move:39
    =     at tests/sources/functional/invariants_with_generics.move:45
