Move prover returns: exiting with boogie verification errors
error: missing specification for TestMutatedArgSpecCheck mod_T_x_incorrect $ret_0 $TestMutatedArgSpecCheck_T_y in mod_T_x_incorrect

    ┌── tests/sources/functional/mutated_args_spec_check.move:30:5 ───
    │
 30 │ ╭     public fun mod_T_x_incorrect(t: &mut T, _t2: &mut T)
 31 │ │     {
 32 │ │         let x = &mut t.x;
 33 │ │         *x = 10;
 34 │ │     }
    │ ╰─────^
    │

error: missing specification for TestMutatedArgSpecCheck mod_T_x_incorrect $ret_1 $TestMutatedArgSpecCheck_T_x in mod_T_x_incorrect

    ┌── tests/sources/functional/mutated_args_spec_check.move:30:5 ───
    │
 30 │ ╭     public fun mod_T_x_incorrect(t: &mut T, _t2: &mut T)
 31 │ │     {
 32 │ │         let x = &mut t.x;
 33 │ │         *x = 10;
 34 │ │     }
    │ ╰─────^
    │

error: missing specification for TestMutatedArgSpecCheck mod_T_x_incorrect $ret_1 $TestMutatedArgSpecCheck_T_y in mod_T_x_incorrect

    ┌── tests/sources/functional/mutated_args_spec_check.move:30:5 ───
    │
 30 │ ╭     public fun mod_T_x_incorrect(t: &mut T, _t2: &mut T)
 31 │ │     {
 32 │ │         let x = &mut t.x;
 33 │ │         *x = 10;
 34 │ │     }
    │ ╰─────^
    │

error: missing specification for TestMutatedArgSpecCheck mod_T_x_caller $ret_0 in mod_T_x_caller

    ┌── tests/sources/functional/mutated_args_spec_check.move:77:5 ───
    │
 77 │ ╭     public fun mod_T_x_caller(t: &mut T): u64 {
 78 │ │         let y = mod_T_x_callee(t);
 79 │ │         y
 80 │ │     }
    │ ╰─────^
    │

error: missing specification for TestMutatedArgSpecCheck mod_T_x_caller $ret_1 $TestMutatedArgSpecCheck_T_x in mod_T_x_caller

    ┌── tests/sources/functional/mutated_args_spec_check.move:77:5 ───
    │
 77 │ ╭     public fun mod_T_x_caller(t: &mut T): u64 {
 78 │ │         let y = mod_T_x_callee(t);
 79 │ │         y
 80 │ │     }
    │ ╰─────^
    │

error: missing specification for TestMutatedArgSpecCheck mod_T_x_caller $ret_1 $TestMutatedArgSpecCheck_T_y in mod_T_x_caller

    ┌── tests/sources/functional/mutated_args_spec_check.move:77:5 ───
    │
 77 │ ╭     public fun mod_T_x_caller(t: &mut T): u64 {
 78 │ │         let y = mod_T_x_callee(t);
 79 │ │         y
 80 │ │     }
    │ ╰─────^
    │
