Move prover returns: exiting with boogie verification errors
error: abort not covered by any of the `aborts_if` clauses

    ┌── tests/sources/functional/pragma.move:10:5 ───
    │
 10 │ ╭     fun always_aborts_with_verify_incorrect(_c: bool) {
 11 │ │         abort(1)
 12 │ │     }
    │ ╰─────^
    ·
 11 │         abort(1)
    │         -------- abort happened here
    │
    =     at tests/sources/functional/pragma.move:10:5: always_aborts_with_verify_incorrect (entry)
    =     at tests/sources/functional/pragma.move:11:9: always_aborts_with_verify_incorrect (ABORTED)
