Move prover returns: exiting with boogie verification errors
error: abort not covered by any of the `aborts_if` clauses

    ┌── tests/sources/functional/pragma.move:10:5 ───
    │
 10 │ ╭     fun always_aborts_with_verify_incorrect(_c: bool) {
 11 │ │         abort(1)
 12 │ │     }
    │ ╰─────^
    ·
 11 │         abort(1)
    │              --- abort happened here with code `0x1`
    │
    =     at tests/sources/functional/pragma.move:10:5: always_aborts_with_verify_incorrect
    =     at tests/sources/functional/pragma.move:11:14: always_aborts_with_verify_incorrect (ABORTED)
    =         _c = <redacted>
