Move prover returns: exiting with boogie verification errors
error: abort not covered by any of the `aborts_if` clauses

   ┌── tests/sources/functional/script_incorrect.move:7:1 ───
   │
 7 │ ╭ fun main<Token>(account: &signer) {
 8 │ │     ScriptProvider::register<Token>(account);
 9 │ │ }
   │ ╰─^
   │
   =     at tests/sources/functional/script_incorrect.move:7:1: main
   =         account = <redacted>
   =     at tests/sources/functional/script_provider.move:17:5: register
   =         account = <redacted>,
   =         $t1 = <redacted>
   =     at tests/sources/functional/script_provider.move:19:9: register
   =     at tests/sources/functional/script_provider.move:18:24: register (ABORTED)

    ┌── tests/sources/functional/script_provider.move:18:24 ───
    │
 18 │         assert(Signer::address_of(account) == 0x1, 1);
    │                        ---------- abort happened here
    │
