============ initial translation from Move ================

[variant baseline]
fun TestBranching::branching($t0|cond: bool): u64 {
     var $t1|tmp#$1: u64
     var $t2|x: u64
     var $t3: bool
     var $t4: u64
     var $t5: u64
     var $t6: u64
     var $t7: u64
  0: $t3 := copy($t0)
  1: if ($t3) goto 4 else goto 2
  2: label L1
  3: goto 8
  4: label L0
  5: $t4 := 3
  6: $t1 := $t4
  7: goto 12
  8: label L2
  9: $t5 := 4
 10: $t1 := $t5
 11: goto 12
 12: label L3
 13: $t6 := move($t1)
 14: $t2 := $t6
 15: $t7 := copy($t2)
 16: return $t7
}

============ after pipeline `reaching_def` ================

[variant baseline]
fun TestBranching::branching($t0|cond: bool): u64 {
     var $t1|tmp#$1: u64
     var $t2|x: u64
     var $t3: bool
     var $t4: u64
     var $t5: u64
     var $t6: u64
     var $t7: u64
  0: $t3 := copy($t0)
  1: if ($t0) goto 4 else goto 2
  2: label L1
  3: goto 8
  4: label L0
  5: $t4 := 3
  6: $t1 := $t4
  7: goto 11
  8: label L2
  9: $t5 := 4
 10: $t1 := $t5
 11: label L3
 12: $t6 := move($t1)
 13: $t2 := $t1
 14: $t7 := copy($t1)
 15: return $t1
}
