Move prover returns: exiting with boogie verification errors
bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1054:6 ───
      │
 1054 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1054:6 ───
      │
 1054 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1050:6 ───
      │
 1050 │     assert false; // $LibraAccount_save_account not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1050:6 ───
      │
 1050 │     assert false; // $LibraAccount_save_account not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1054:6 ───
      │
 1054 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1054:6 ───
      │
 1054 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1054:6 ───
      │
 1054 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1054:6 ───
      │
 1054 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1050:6 ───
      │
 1050 │     assert false; // $LibraAccount_save_account not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1050:6 ───
      │
 1050 │     assert false; // $LibraAccount_save_account not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1050:6 ───
      │
 1050 │     assert false; // $LibraAccount_save_account not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1050:6 ───
      │
 1050 │     assert false; // $LibraAccount_save_account not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1063:6 ───
      │
 1063 │     assert false; // $Signature_ed25519_verify not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1063:6 ───
      │
 1063 │     assert false; // $Signature_ed25519_verify not implemented
      │      ^
      │
