Move prover returns: exiting with boogie verification errors
bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1138:6 ───
      │
 1138 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1138:6 ───
      │
 1138 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1138:6 ───
      │
 1138 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1138:6 ───
      │
 1138 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1138:6 ───
      │
 1138 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1116:6 ───
      │
 1116 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1125:6 ───
      │
 1125 │     assert false; // $Signature_ed25519_verify not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1125:6 ───
      │
 1125 │     assert false; // $Signature_ed25519_verify not implemented
      │      ^
      │
