Move prover returns: exiting with boogie verification errors
bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1101:6 ───
      │
 1101 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1101:6 ───
      │
 1101 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1101:6 ───
      │
 1101 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1101:6 ───
      │
 1101 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1101:6 ───
      │
 1101 │     assert false; // $LCS_to_bytes not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1079:6 ───
      │
 1079 │     assert false; // $LibraAccount_write_to_event_store not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1088:6 ───
      │
 1088 │     assert false; // $Signature_ed25519_verify not implemented
      │      ^
      │

bug:  This assertion might not hold.

      ┌── approved_payment.bpl:1088:6 ───
      │
 1088 │     assert false; // $Signature_ed25519_verify not implemented
      │      ^
      │
