Move prover returns: exiting with boogie verification errors
error:  A precondition for this call might not hold.

    ┌── tests/sources/stdlib/modules/validator_config.move:93:5 ───
    │
 93 │ ╭     public fun rotate_consensus_pubkey(consensus_pubkey: vector<u8>) acquires T {
 94 │ │         let t_ref = borrow_global_mut<T>(Transaction::sender());
 95 │ │         let key_ref = &mut t_ref.config.consensus_pubkey;
 96 │ │         *key_ref = consensus_pubkey;
 97 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/stdlib/modules/libra_system.move:289:4: rotate_consensus_pubkey (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:290:32: rotate_consensus_pubkey
    =         consensus_pubkey = <redacted>,
    =         validator_set_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:291:43: rotate_consensus_pubkey
    =         account_address = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
    =         addr = <redacted>,
    =         validators_vec_ref = <redacted>,
    =         size = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
    =         i = <redacted>,
    =         validator_info_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:295:12: rotate_consensus_pubkey
    =     at tests/sources/stdlib/modules/libra_system.move:294:8: rotate_consensus_pubkey
    =     at tests/sources/stdlib/modules/validator_config.move:93:5: rotate_consensus_pubkey (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:115:5 ───
     │
 115 │ ╭     public fun get_discovery_address(d: &DiscoveryInfo): &address {
 116 │ │         &d.addr
 117 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:329:4: rotate_validator_network_address (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:332:32: rotate_validator_network_address
     =         validator_network_address = <redacted>,
     =         discovery_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:335:58: rotate_validator_network_address
     =     at tests/sources/stdlib/modules/validator_config.move:113:5: rotate_validator_network_address (entry)
     =     at tests/sources/stdlib/modules/validator_config.move:116:21: rotate_validator_network_address
     =         validator_network_address = <redacted>,
     =         t_ref = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:117:13: rotate_validator_network_address
     =         key_ref = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:118:20: rotate_validator_network_address
     =         key_ref = <redacted>,
     =         t_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:335:25: rotate_validator_network_address
     =     at tests/sources/stdlib/modules/libra_system.move:207:5: get_discovery_index (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:208:27: get_discovery_index
     =         discovery_set = <redacted>,
     =         addr = <redacted>,
     =         len = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:209:17: get_discovery_index
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:211:54: get_discovery_index
     =     at tests/sources/stdlib/modules/libra_system.move:115:5: get_discovery_address (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:115:5 ───
     │
 115 │ ╭     public fun get_discovery_address(d: &DiscoveryInfo): &address {
 116 │ │         &d.addr
 117 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:311:4: rotate_validator_network_identity_pubkey (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:314:32: rotate_validator_network_identity_pubkey
     =         validator_network_identity_pubkey = <redacted>,
     =         discovery_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:317:66: rotate_validator_network_identity_pubkey
     =     at tests/sources/stdlib/modules/validator_config.move:103:5: rotate_validator_network_identity_pubkey (entry)
     =     at tests/sources/stdlib/modules/validator_config.move:106:21: rotate_validator_network_identity_pubkey
     =         validator_network_identity_pubkey = <redacted>,
     =         t_ref = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:107:13: rotate_validator_network_identity_pubkey
     =         key_ref = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:108:20: rotate_validator_network_identity_pubkey
     =         key_ref = <redacted>,
     =         t_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:317:25: rotate_validator_network_identity_pubkey
     =     at tests/sources/stdlib/modules/libra_system.move:207:5: get_discovery_index (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:208:27: get_discovery_index
     =         discovery_set = <redacted>,
     =         addr = <redacted>,
     =         len = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:209:17: get_discovery_index
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:211:54: get_discovery_index
     =     at tests/sources/stdlib/modules/libra_system.move:115:5: get_discovery_address (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:412:4 ───
     │
 412 │ ╭    fun make_validator_info(addr: address): ValidatorInfo {
 413 │ │        let config = ValidatorConfig::config(addr);
 414 │ │
 415 │ │       ValidatorInfo {
 416 │ │           addr: addr,
 417 │ │           consensus_pubkey: ValidatorConfig::consensus_pubkey(&config),
 418 │ │           consensus_voting_power: 1,
 419 │ │           network_signing_pubkey: ValidatorConfig::validator_network_signing_pubkey(&config),
 420 │ │           network_identity_pubkey: ValidatorConfig::validator_network_identity_pubkey(&config),
 421 │ │       }
 422 │ │    }
     │ ╰────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:227:5: add_validator (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:233:4: add_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:235:8: add_validator_
     =         account_address = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:24:5: has (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:237:45: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:239:32: add_validator_
     =         validator_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:240:64: add_validator_
     =         discovery_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
     =         addr = <redacted>,
     =         validators_vec_ref = <redacted>,
     =         size = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
     =         i = <redacted>,
     =         validator_info_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:153:19: is_validator_
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:154:17: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:244:13: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:243:8: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:412:4: make_validator_info (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:412:4 ───
     │
 412 │ ╭    fun make_validator_info(addr: address): ValidatorInfo {
 413 │ │        let config = ValidatorConfig::config(addr);
 414 │ │
 415 │ │       ValidatorInfo {
 416 │ │           addr: addr,
 417 │ │           consensus_pubkey: ValidatorConfig::consensus_pubkey(&config),
 418 │ │           consensus_voting_power: 1,
 419 │ │           network_signing_pubkey: ValidatorConfig::validator_network_signing_pubkey(&config),
 420 │ │           network_identity_pubkey: ValidatorConfig::validator_network_identity_pubkey(&config),
 421 │ │       }
 422 │ │    }
     │ ╰────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:233:4: add_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:235:8: add_validator_
     =         account_address = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:24:5: has (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:237:45: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:239:32: add_validator_
     =         validator_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:240:64: add_validator_
     =         discovery_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
     =         addr = <redacted>,
     =         validators_vec_ref = <redacted>,
     =         size = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
     =         i = <redacted>,
     =         validator_info_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:153:19: is_validator_
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:154:17: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:244:13: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:243:8: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:412:4: make_validator_info (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:115:5 ───
     │
 115 │ ╭     public fun get_discovery_address(d: &DiscoveryInfo): &address {
 116 │ │         &d.addr
 117 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:207:5: get_discovery_index (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:208:27: get_discovery_index
     =         discovery_set = <redacted>,
     =         addr = <redacted>,
     =         len = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:209:17: get_discovery_index
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:211:54: get_discovery_index
     =     at tests/sources/stdlib/modules/libra_system.move:115:5: get_discovery_address (entry)

error:  A precondition for this call might not hold.

    ┌── tests/sources/stdlib/modules/libra_system.move:93:5 ───
    │
 93 │ ╭     public fun get_validator_address(v: &ValidatorInfo): &address {
 94 │ │       &v.addr
 95 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/stdlib/modules/libra_system.move:190:5: get_validator_index (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:191:27: get_validator_index
    =         validators = <redacted>,
    =         addr = <redacted>,
    =         len = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:192:17: get_validator_index
    =         i = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:194:54: get_validator_index
    =     at tests/sources/stdlib/modules/libra_system.move:93:5: get_validator_address (entry)

error:  A precondition for this call might not hold.

    ┌── tests/sources/stdlib/modules/libra_system.move:93:5 ───
    │
 93 │ ╭     public fun get_validator_address(v: &ValidatorInfo): &address {
 94 │ │       &v.addr
 95 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/stdlib/modules/libra_system.move:258:4: remove_validator (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:260:8: remove_validator
    =         account_address = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:262:32: remove_validator
    =         validator_set_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:263:64: remove_validator
    =         discovery_set_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
    =         addr = <redacted>,
    =         validators_vec_ref = <redacted>,
    =         size = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
    =         i = <redacted>,
    =         validator_info_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:266:12: remove_validator
    =     at tests/sources/stdlib/modules/libra_system.move:265:8: remove_validator
    =     at tests/sources/stdlib/modules/libra_system.move:190:5: get_validator_index (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:191:27: get_validator_index
    =     at tests/sources/stdlib/modules/libra_system.move:192:17: get_validator_index
    =     at tests/sources/stdlib/modules/libra_system.move:194:54: get_validator_index
    =     at tests/sources/stdlib/modules/libra_system.move:93:5: get_validator_address (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:174:5 ───
     │
 174 │ ╭     public fun get_ith_validator_address(i: u64): address acquires ValidatorSet {
 175 │ │       let validator_set = borrow_global<ValidatorSet>(0x1D8);
 176 │ │       let len = Vector::length(&validator_set.validators);
 177 │ │       Transaction::assert(i < len, 3);
 178 │ │       Vector::borrow(&validator_set.validators, i).addr
 179 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/transaction_fee.move:51:5: distribute_transaction_fees (entry)
     =     at tests/sources/stdlib/modules/transaction_fee.move:53:7: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/libra_system.move:136:5: validator_set_size (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:137:25: validator_set_size
     =     at tests/sources/stdlib/modules/transaction_fee.move:55:41: distribute_transaction_fees
     =         num_validators = <redacted>
     =     at tests/sources/stdlib/modules/transaction_fee.move:56:52: distribute_transaction_fees
     =         amount_collected = <redacted>
     =     at tests/sources/stdlib/modules/libra_account.move:384:5: balance (entry)
     =     at tests/sources/stdlib/modules/libra_account.move:385:21: balance
     =         addr = <redacted>
     =     at tests/sources/stdlib/modules/libra_account.move:379:5: balance_for (entry)
     =     at tests/sources/stdlib/modules/libra_coin.move:105:5: value (entry)
     =     at tests/sources/stdlib/modules/libra_coin.move:105:5: value (exit)
     =         coin_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_account.move:380:20: balance_for
     =         balance = <redacted>
     =     at tests/sources/stdlib/modules/libra_account.move:385:9: balance
     =     at tests/sources/stdlib/modules/transaction_fee.move:56:44: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/transaction_fee.move:59:11: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/transaction_fee.move:108:5: per_validator_distribution_amount (entry)
     =     at tests/sources/stdlib/modules/transaction_fee.move:109:9: per_validator_distribution_amount
     =         amount_collected = <redacted>,
     =         num_validators = <redacted>
     =     at tests/sources/stdlib/modules/transaction_fee.move:110:49: per_validator_distribution_amount
     =         validator_payout = <redacted>
     =     at tests/sources/stdlib/modules/transaction_fee.move:111:29: per_validator_distribution_amount
     =     at tests/sources/stdlib/modules/transaction_fee.move:62:48: distribute_transaction_fees
     =         amount_to_distribute_per_validator = <redacted>
     =     at tests/sources/stdlib/modules/transaction_fee.move:69:11: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/transaction_fee.move:79:5: distribute_transaction_fees_internal (entry)
     =     at tests/sources/stdlib/modules/transaction_fee.move:83:37: distribute_transaction_fees_internal
     =         amount_to_distribute_per_validator = <redacted>,
     =         num_validators = <redacted>,
     =         distribution_resource = <redacted>
     =     at tests/sources/stdlib/modules/transaction_fee.move:84:21: distribute_transaction_fees_internal
     =         index = <redacted>
     =     at tests/sources/stdlib/modules/transaction_fee.move:86:16: distribute_transaction_fees_internal
     =     at tests/sources/stdlib/modules/libra_system.move:174:5: get_ith_validator_address (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:174:5 ───
     │
 174 │ ╭     public fun get_ith_validator_address(i: u64): address acquires ValidatorSet {
 175 │ │       let validator_set = borrow_global<ValidatorSet>(0x1D8);
 176 │ │       let len = Vector::length(&validator_set.validators);
 177 │ │       Transaction::assert(i < len, 3);
 178 │ │       Vector::borrow(&validator_set.validators, i).addr
 179 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/transaction_fee.move:79:5: distribute_transaction_fees_internal (entry)
     =     at tests/sources/stdlib/modules/transaction_fee.move:83:37: distribute_transaction_fees_internal
     =         amount_to_distribute_per_validator = <redacted>,
     =         num_validators = <redacted>,
     =         distribution_resource = <redacted>
     =     at tests/sources/stdlib/modules/transaction_fee.move:84:21: distribute_transaction_fees_internal
     =         index = <redacted>
     =     at tests/sources/stdlib/modules/transaction_fee.move:86:16: distribute_transaction_fees_internal
     =     at tests/sources/stdlib/modules/libra_system.move:174:5: get_ith_validator_address (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:174:5 ───
     │
 174 │ ╭     public fun get_ith_validator_address(i: u64): address acquires ValidatorSet {
 175 │ │       let validator_set = borrow_global<ValidatorSet>(0x1D8);
 176 │ │       let len = Vector::length(&validator_set.validators);
 177 │ │       Transaction::assert(i < len, 3);
 178 │ │       Vector::borrow(&validator_set.validators, i).addr
 179 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/libra_block.move:57:5: block_prologue (entry)
     =     at tests/sources/stdlib/modules/libra_block.move:64:7: block_prologue
     =         timestamp = <redacted>,
     =         new_block_hash = <redacted>,
     =         previous_block_votes = <redacted>,
     =         proposer = <redacted>
     =     at tests/sources/stdlib/modules/libra_block.move:74:5: process_block_prologue (entry)
     =     at tests/sources/stdlib/modules/libra_block.move:80:34: process_block_prologue
     =         timestamp = <redacted>,
     =         new_block_hash = <redacted>,
     =         previous_block_votes = <redacted>,
     =         proposer = <redacted>,
     =         block_metadata_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_block.move:83:12: process_block_prologue
     =     at tests/sources/stdlib/modules/libra_block.move:84:44: process_block_prologue
     =     at tests/sources/stdlib/modules/libra_time.move:24:5: update_global_time (entry)
     =     at tests/sources/stdlib/modules/libra_time.move:26:9: update_global_time
     =     at tests/sources/stdlib/modules/libra_time.move:28:28: update_global_time
     =     at tests/sources/stdlib/modules/libra_time.move:29:13: update_global_time
     =     at tests/sources/stdlib/modules/libra_time.move:31:13: update_global_time
     =     at tests/sources/stdlib/modules/libra_time.move:36:37: update_global_time
     =     at tests/sources/stdlib/modules/libra_block.move:84:25: process_block_prologue
     =     at tests/sources/stdlib/modules/libra_block.move:86:9: process_block_prologue
     =     at tests/sources/stdlib/modules/libra_block.move:87:39: process_block_prologue
     =     at tests/sources/stdlib/modules/libra_block.move:88:37: process_block_prologue
     =     at tests/sources/stdlib/modules/libra_block.move:66:7: block_prologue
     =     at tests/sources/stdlib/modules/transaction_fee.move:51:5: distribute_transaction_fees (entry)
     =     at tests/sources/stdlib/modules/transaction_fee.move:53:7: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/libra_system.move:136:5: validator_set_size (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:137:25: validator_set_size
     =     at tests/sources/stdlib/modules/transaction_fee.move:55:41: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/transaction_fee.move:56:52: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/libra_account.move:384:5: balance (entry)
     =     at tests/sources/stdlib/modules/libra_account.move:385:21: balance
     =     at tests/sources/stdlib/modules/libra_account.move:379:5: balance_for (entry)
     =     at tests/sources/stdlib/modules/libra_coin.move:105:5: value (entry)
     =     at tests/sources/stdlib/modules/libra_coin.move:105:5: value (exit)
     =     at tests/sources/stdlib/modules/libra_account.move:380:20: balance_for
     =     at tests/sources/stdlib/modules/libra_account.move:385:9: balance
     =     at tests/sources/stdlib/modules/transaction_fee.move:56:44: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/transaction_fee.move:59:11: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/transaction_fee.move:108:5: per_validator_distribution_amount (entry)
     =     at tests/sources/stdlib/modules/transaction_fee.move:109:9: per_validator_distribution_amount
     =     at tests/sources/stdlib/modules/transaction_fee.move:110:49: per_validator_distribution_amount
     =     at tests/sources/stdlib/modules/transaction_fee.move:111:29: per_validator_distribution_amount
     =     at tests/sources/stdlib/modules/transaction_fee.move:62:48: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/transaction_fee.move:69:11: distribute_transaction_fees
     =     at tests/sources/stdlib/modules/transaction_fee.move:79:5: distribute_transaction_fees_internal (entry)
     =     at tests/sources/stdlib/modules/transaction_fee.move:83:37: distribute_transaction_fees_internal
     =     at tests/sources/stdlib/modules/transaction_fee.move:84:21: distribute_transaction_fees_internal
     =     at tests/sources/stdlib/modules/transaction_fee.move:86:16: distribute_transaction_fees_internal
     =     at tests/sources/stdlib/modules/libra_system.move:174:5: get_ith_validator_address (entry)

error:  A precondition for this call might not hold.

    ┌── tests/sources/stdlib/modules/libra_time.move:24:5 ───
    │
 24 │ ╭     public fun update_global_time(proposer: address, timestamp: u64) acquires CurrentTimeMicroseconds {
 25 │ │
 26 │ │         Transaction::assert(Transaction::sender() == 0x0, 33);
 27 │ │
 28 │ │         let global_timer = borrow_global_mut<CurrentTimeMicroseconds>(0xA550C18);
 29 │ │         if (proposer == 0x0) {
 30 │ │
 31 │ │             Transaction::assert(timestamp == global_timer.microseconds, 5001);
 32 │ │         } else {
 33 │ │
 34 │ │             Transaction::assert(global_timer.microseconds < timestamp, 5001);
 35 │ │         };
 36 │ │         global_timer.microseconds = timestamp;
 37 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/stdlib/modules/libra_block.move:74:5: process_block_prologue (entry)
    =     at tests/sources/stdlib/modules/libra_block.move:80:34: process_block_prologue
    =         timestamp = <redacted>,
    =         new_block_hash = <redacted>,
    =         previous_block_votes = <redacted>,
    =         proposer = <redacted>,
    =         block_metadata_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_block.move:83:12: process_block_prologue
    =     at tests/sources/stdlib/modules/libra_system.move:162:5: is_validator (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:163:31: is_validator
    =         addr = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
    =         addr = <redacted>,
    =         validators_vec_ref = <redacted>,
    =         size = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
    =         i = <redacted>,
    =         validator_info_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:163:9: is_validator
    =     at tests/sources/stdlib/modules/libra_block.move:83:62: process_block_prologue
    =     at tests/sources/stdlib/modules/libra_block.move:84:44: process_block_prologue
    =     at tests/sources/stdlib/modules/libra_time.move:24:5: update_global_time (entry)
