Move prover returns: exiting with boogie verification errors
error:  A precondition for this call might not hold.

    ┌── tests/sources/stdlib/modules/validator_config.move:93:5 ───
    │
 93 │ ╭     public fun rotate_consensus_pubkey(consensus_pubkey: vector<u8>) acquires T {
 94 │ │         let t_ref = borrow_global_mut<T>(Transaction::sender());
 95 │ │         let key_ref = &mut t_ref.config.consensus_pubkey;
 96 │ │         *key_ref = consensus_pubkey;
 97 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/stdlib/modules/libra_system.move:289:4: rotate_consensus_pubkey (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:290:32: rotate_consensus_pubkey
    =         consensus_pubkey = <redacted>,
    =         validator_set_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:291:43: rotate_consensus_pubkey
    =         account_address = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
    =         addr = <redacted>,
    =         validators_vec_ref = <redacted>,
    =         size = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
    =         i = <redacted>,
    =         validator_info_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:295:12: rotate_consensus_pubkey
    =     at tests/sources/stdlib/modules/libra_system.move:294:8: rotate_consensus_pubkey
    =     at tests/sources/stdlib/modules/validator_config.move:93:5: rotate_consensus_pubkey (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:115:5 ───
     │
 115 │ ╭     public fun get_discovery_address(d: &DiscoveryInfo): &address {
 116 │ │         &d.addr
 117 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:329:4: rotate_validator_network_address (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:332:32: rotate_validator_network_address
     =         validator_network_address = <redacted>,
     =         discovery_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:335:58: rotate_validator_network_address
     =     at tests/sources/stdlib/modules/validator_config.move:113:5: rotate_validator_network_address (entry)
     =     at tests/sources/stdlib/modules/validator_config.move:116:21: rotate_validator_network_address
     =         validator_network_address = <redacted>,
     =         t_ref = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:117:13: rotate_validator_network_address
     =         key_ref = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:118:20: rotate_validator_network_address
     =         key_ref = <redacted>,
     =         t_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:335:25: rotate_validator_network_address
     =     at tests/sources/stdlib/modules/libra_system.move:207:5: get_discovery_index (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:208:27: get_discovery_index
     =         discovery_set = <redacted>,
     =         addr = <redacted>,
     =         len = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:209:17: get_discovery_index
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:211:54: get_discovery_index
     =     at tests/sources/stdlib/modules/libra_system.move:115:5: get_discovery_address (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:115:5 ───
     │
 115 │ ╭     public fun get_discovery_address(d: &DiscoveryInfo): &address {
 116 │ │         &d.addr
 117 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:311:4: rotate_validator_network_identity_pubkey (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:314:32: rotate_validator_network_identity_pubkey
     =         validator_network_identity_pubkey = <redacted>,
     =         discovery_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:317:66: rotate_validator_network_identity_pubkey
     =     at tests/sources/stdlib/modules/validator_config.move:103:5: rotate_validator_network_identity_pubkey (entry)
     =     at tests/sources/stdlib/modules/validator_config.move:106:21: rotate_validator_network_identity_pubkey
     =         validator_network_identity_pubkey = <redacted>,
     =         t_ref = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:107:13: rotate_validator_network_identity_pubkey
     =         key_ref = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:108:20: rotate_validator_network_identity_pubkey
     =         key_ref = <redacted>,
     =         t_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:317:25: rotate_validator_network_identity_pubkey
     =     at tests/sources/stdlib/modules/libra_system.move:207:5: get_discovery_index (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:208:27: get_discovery_index
     =         discovery_set = <redacted>,
     =         addr = <redacted>,
     =         len = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:209:17: get_discovery_index
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:211:54: get_discovery_index
     =     at tests/sources/stdlib/modules/libra_system.move:115:5: get_discovery_address (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:412:4 ───
     │
 412 │ ╭    fun make_validator_info(addr: address): ValidatorInfo {
 413 │ │        let config = ValidatorConfig::config(addr);
 414 │ │
 415 │ │       ValidatorInfo {
 416 │ │           addr: addr,
 417 │ │           consensus_pubkey: ValidatorConfig::consensus_pubkey(&config),
 418 │ │           consensus_voting_power: 1,
 419 │ │           network_signing_pubkey: ValidatorConfig::validator_network_signing_pubkey(&config),
 420 │ │           network_identity_pubkey: ValidatorConfig::validator_network_identity_pubkey(&config),
 421 │ │       }
 422 │ │    }
     │ ╰────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:227:5: add_validator (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:233:4: add_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:235:8: add_validator_
     =         account_address = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:24:5: has (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:237:45: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:239:32: add_validator_
     =         validator_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:240:64: add_validator_
     =         discovery_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
     =         addr = <redacted>,
     =         validators_vec_ref = <redacted>,
     =         size = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
     =         i = <redacted>,
     =         validator_info_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:153:19: is_validator_
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:154:17: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:244:13: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:243:8: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:412:4: make_validator_info (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:412:4 ───
     │
 412 │ ╭    fun make_validator_info(addr: address): ValidatorInfo {
 413 │ │        let config = ValidatorConfig::config(addr);
 414 │ │
 415 │ │       ValidatorInfo {
 416 │ │           addr: addr,
 417 │ │           consensus_pubkey: ValidatorConfig::consensus_pubkey(&config),
 418 │ │           consensus_voting_power: 1,
 419 │ │           network_signing_pubkey: ValidatorConfig::validator_network_signing_pubkey(&config),
 420 │ │           network_identity_pubkey: ValidatorConfig::validator_network_identity_pubkey(&config),
 421 │ │       }
 422 │ │    }
     │ ╰────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:233:4: add_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:235:8: add_validator_
     =         account_address = <redacted>
     =     at tests/sources/stdlib/modules/validator_config.move:24:5: has (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:237:45: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:239:32: add_validator_
     =         validator_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:240:64: add_validator_
     =         discovery_set_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
     =         addr = <redacted>,
     =         validators_vec_ref = <redacted>,
     =         size = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
     =         i = <redacted>,
     =         validator_info_ref = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:153:19: is_validator_
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:154:17: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:244:13: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:243:8: add_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:412:4: make_validator_info (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:115:5 ───
     │
 115 │ ╭     public fun get_discovery_address(d: &DiscoveryInfo): &address {
 116 │ │         &d.addr
 117 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:207:5: get_discovery_index (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:208:27: get_discovery_index
     =         discovery_set = <redacted>,
     =         addr = <redacted>,
     =         len = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:209:17: get_discovery_index
     =         i = <redacted>
     =     at tests/sources/stdlib/modules/libra_system.move:211:54: get_discovery_index
     =     at tests/sources/stdlib/modules/libra_system.move:115:5: get_discovery_address (entry)

error:  A precondition for this call might not hold.

    ┌── tests/sources/stdlib/modules/libra_system.move:93:5 ───
    │
 93 │ ╭     public fun get_validator_address(v: &ValidatorInfo): &address {
 94 │ │       &v.addr
 95 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/stdlib/modules/libra_system.move:190:5: get_validator_index (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:191:27: get_validator_index
    =         validators = <redacted>,
    =         addr = <redacted>,
    =         len = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:192:17: get_validator_index
    =         i = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:194:54: get_validator_index
    =     at tests/sources/stdlib/modules/libra_system.move:93:5: get_validator_address (entry)

error:  A precondition for this call might not hold.

    ┌── tests/sources/stdlib/modules/libra_system.move:93:5 ───
    │
 93 │ ╭     public fun get_validator_address(v: &ValidatorInfo): &address {
 94 │ │       &v.addr
 95 │ │     }
    │ ╰─────^
    │
    =     at tests/sources/stdlib/modules/libra_system.move:258:4: remove_validator (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:260:8: remove_validator
    =         account_address = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:262:32: remove_validator
    =         validator_set_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:263:64: remove_validator
    =         discovery_set_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
    =         addr = <redacted>,
    =         validators_vec_ref = <redacted>,
    =         size = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
    =         i = <redacted>,
    =         validator_info_ref = <redacted>
    =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
    =     at tests/sources/stdlib/modules/libra_system.move:266:12: remove_validator
    =     at tests/sources/stdlib/modules/libra_system.move:265:8: remove_validator
    =     at tests/sources/stdlib/modules/libra_system.move:190:5: get_validator_index (entry)
    =     at tests/sources/stdlib/modules/libra_system.move:191:27: get_validator_index
    =     at tests/sources/stdlib/modules/libra_system.move:192:17: get_validator_index
    =     at tests/sources/stdlib/modules/libra_system.move:194:54: get_validator_index
    =     at tests/sources/stdlib/modules/libra_system.move:93:5: get_validator_address (entry)

error:  A precondition for this call might not hold.

     ┌── tests/sources/stdlib/modules/libra_system.move:190:5 ───
     │
 190 │ ╭     public fun get_validator_index(validators: &vector<ValidatorInfo>, addr: address): u64 {
 191 │ │         let len = Vector::length(validators);
 192 │ │         let i = 0;
 193 │ │         loop {
 194 │ │             if (get_validator_address(Vector::borrow(validators, i)) == &addr) {
 195 │ │                 return i
 196 │ │             };
 197 │ │
 198 │ │             i = i + 1;
 199 │ │             if (i >= len) { break };
 200 │ │         };
 201 │ │
 202 │ │         abort 99
 203 │ │     }
     │ ╰─────^
     │
     =     at tests/sources/stdlib/modules/libra_system.move:258:4: remove_validator (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:260:8: remove_validator
     =     at tests/sources/stdlib/modules/libra_system.move:262:32: remove_validator
     =     at tests/sources/stdlib/modules/libra_system.move:263:64: remove_validator
     =     at tests/sources/stdlib/modules/libra_system.move:140:4: is_validator_ (entry)
     =     at tests/sources/stdlib/modules/libra_system.move:141:28: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:142:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:146:13: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:148:49: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:150:18: is_validator_
     =     at tests/sources/stdlib/modules/libra_system.move:266:12: remove_validator
     =     at tests/sources/stdlib/modules/libra_system.move:265:8: remove_validator
     =     at tests/sources/stdlib/modules/libra_system.move:190:5: get_validator_index (entry)
