warning[W09004]: unnecessary trailing semicolon
  ┌─ tests/move_check/liveness/loop_weirdness.move:9:43
  │
9 │                 if (my_local >= 0) { break; };
  │                                      -----^
  │                                      │    │
  │                                      │    Invalid trailing ';'
  │                                      │    A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
  │                                      Any code after this expression will not be reached

