warning[W09004]: unnecessary trailing semicolon
  ┌─ tests/move_check/liveness/trailing_semi.move:3:15
  │
3 │         return;
  │         ------^
  │         │     │
  │         │     Invalid trailing ';'
  │         │     A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
  │         Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
  ┌─ tests/move_check/liveness/trailing_semi.move:9:16
  │
9 │         abort 0;
  │         -------^
  │         │      │
  │         │      Invalid trailing ';'
  │         │      A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
  │         Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi.move:15:19
   │
15 │         { return };
   │           ------  ^
   │           │       │
   │           │       Invalid trailing ';'
   │           │       A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │           Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi.move:21:20
   │
21 │         { abort 0 };
   │           -------  ^
   │           │        │
   │           │        Invalid trailing ';'
   │           │        A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │           Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi.move:29:19
   │
29 │             return;
   │             ------^
   │             │     │
   │             │     Invalid trailing ';'
   │             │     A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │             Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi.move:43:14
   │  
39 │ ╭             if (cond) {
40 │ │                 return
41 │ │             } else {
42 │ │                 abort 0
43 │ │             };
   │ │              ^
   │ │              │
   │ │              Invalid trailing ';'
   │ │              A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │ ╰─────────────' Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi.move:52:24
   │
52 │                 abort 0;
   │                 -------^
   │                 │      │
   │                 │      Invalid trailing ';'
   │                 │      A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │                 Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi.move:54:23
   │
54 │                 return;
   │                 ------^
   │                 │     │
   │                 │     Invalid trailing ';'
   │                 │     A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │                 Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi.move:55:14
   │  
51 │ ╭             if (cond) {
52 │ │                 abort 0;
53 │ │             } else {
54 │ │                 return;
55 │ │             };
   │ │              ^
   │ │              │
   │ │              Invalid trailing ';'
   │ │              A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │ ╰─────────────' Any code after this expression will not be reached

