warning[W09004]: unnecessary trailing semicolon
  ┌─ tests/move_check/liveness/trailing_semi_loops.move:3:16
  │
3 │         loop ();
  │         -------^
  │         │      │
  │         │      Invalid trailing ';'
  │         │      A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
  │         Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
  ┌─ tests/move_check/liveness/trailing_semi_loops.move:9:26
  │
9 │         { (loop (): ()) };
  │            -------       ^
  │            │             │
  │            │             Invalid trailing ';'
  │            │             A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
  │            Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:18:10
   │  
15 │ ╭         loop {
16 │ │             let x = 0;
17 │ │             0 + x + 0;
18 │ │         };
   │ │          ^
   │ │          │
   │ │          Invalid trailing ';'
   │ │          A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │ ╰─────────' Any code after this expression will not be reached

warning[W09005]: dead or unreachable code
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:27:26
   │
27 │             let x: u64 = if (true) break else break;
   │                          ^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid use of a divergent expression. The code following the evaluation of this expression will be dead and should be removed.

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:35:18
   │
35 │             break;
   │             -----^
   │             │    │
   │             │    Invalid trailing ';'
   │             │    A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │             Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:44:22
   │
44 │                 break;
   │                 -----^
   │                 │    │
   │                 │    Invalid trailing ';'
   │                 │    A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │                 Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:55:42
   │
55 │             if (cond) continue else break;
   │             -----------------------------^
   │             │                            │
   │             │                            Invalid trailing ';'
   │             │                            A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │             Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:63:42
   │
63 │             if (cond) abort 0 else return;
   │             -----------------------------^
   │             │                            │
   │             │                            Invalid trailing ';'
   │             │                            A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │             Any code after this expression will not be reached

warning[W09003]: unused assignment
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:76:17
   │
76 │                 x = 2;
   │                 ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:78:14
   │  
72 │ ╭             if (cond) {
73 │ │                 x = 1;
74 │ │                 break
75 │ │             } else {
76 │ │                 x = 2;
77 │ │                 continue
78 │ │             };
   │ │              ^
   │ │              │
   │ │              Invalid trailing ';'
   │ │              A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │ ╰─────────────' Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:88:22
   │
88 │                 break;
   │                 -----^
   │                 │    │
   │                 │    Invalid trailing ';'
   │                 │    A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │                 Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:90:25
   │
90 │                 continue;
   │                 --------^
   │                 │       │
   │                 │       Invalid trailing ';'
   │                 │       A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │                 Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/liveness/trailing_semi_loops.move:91:14
   │  
87 │ ╭             if (cond) {
88 │ │                 break;
89 │ │             } else {
90 │ │                 continue;
91 │ │             };
   │ │              ^
   │ │              │
   │ │              Invalid trailing ';'
   │ │              A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │ ╰─────────────' Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
    ┌─ tests/move_check/liveness/trailing_semi_loops.move:100:23
    │
100 │                 return;
    │                 ------^
    │                 │     │
    │                 │     Invalid trailing ';'
    │                 │     A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
    │                 Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
    ┌─ tests/move_check/liveness/trailing_semi_loops.move:102:24
    │
102 │                 abort 0;
    │                 -------^
    │                 │      │
    │                 │      Invalid trailing ';'
    │                 │      A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
    │                 Any code after this expression will not be reached

warning[W09004]: unnecessary trailing semicolon
    ┌─ tests/move_check/liveness/trailing_semi_loops.move:103:14
    │  
 99 │ ╭             if (cond) {
100 │ │                 return;
101 │ │             } else {
102 │ │                 abort 0;
103 │ │             };
    │ │              ^
    │ │              │
    │ │              Invalid trailing ';'
    │ │              A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
    │ ╰─────────────' Any code after this expression will not be reached

