warning[W09003]: unused assignment
  ┌─ tests/move_check/liveness/unused_assignment.move:3:13
  │
3 │         let x = 0;
  │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09003]: unused assignment
  ┌─ tests/move_check/liveness/unused_assignment.move:7:13
  │
7 │         let x = 0;
  │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09003]: unused assignment
  ┌─ tests/move_check/liveness/unused_assignment.move:8:9
  │
8 │         x = 0;
  │         ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09003]: unused assignment
   ┌─ tests/move_check/liveness/unused_assignment.move:13:17
   │
13 │             let x = 0;
   │                 ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09003]: unused assignment
   ┌─ tests/move_check/liveness/unused_assignment.move:21:13
   │
21 │             x = 0;
   │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09003]: unused assignment
   ┌─ tests/move_check/liveness/unused_assignment.move:26:13
   │
26 │         let x = 0;
   │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09003]: unused assignment
   ┌─ tests/move_check/liveness/unused_assignment.move:28:13
   │
28 │             x = 1;
   │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09003]: unused assignment
   ┌─ tests/move_check/liveness/unused_assignment.move:30:13
   │
30 │             x = 2;
   │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

warning[W09003]: unused assignment
   ┌─ tests/move_check/liveness/unused_assignment.move:41:13
   │
41 │             x = 1;
   │             ^ Unused assignment or binding for local 'x'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_x')

