{
 "title": "Test net metrics",
 "time": { "from": "now/w", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transaction count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(consensus{op='committed_txns_count'})"
    }
   ]
  },
  {
   "title": "Accounts created",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(executor{op='num_accounts'})",
     "legendFormat": "Num Accounts Created"
    }
   ]
  },
  {
   "title": "Transactions per second (5min avg)",
   "type": "gauge",
   "description": "Avg over the last 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(rate(consensus{op='committed_txns_count'}[5m]))"
    }
   ]
  },
  {
   "title": "Account creation per second (5min avg)",
   "type": "gauge",
   "description": "Avg over the last 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(rate(executor{op='num_accounts'}[5m]))"
    }
   ]
  },
  {
   "title": "Transactions per second (5min avg)",
   "type": "graph",
   "description": "Avg over the last 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(consensus{op='committed_txns_count'}[5m]))",
     "legendFormat": "Transactions /s"
    }
   ]
  },
  {
   "title": "Accounts created per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(executor{op='num_accounts'}[5m]))",
     "legendFormat": "Num Accounts Created / second"
    }
   ]
  },
  {
   "title": "Transaction count by node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus{op='committed_txns_count'}"
    }
   ]
  },
  {
   "title": "Transaction count by node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "executor{op='num_accounts'}" }
   ]
  }
 ]
}