{
 "title": "Consensus",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_last_committed_round[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed successful txns per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_last_committed_version[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Block creation to vote / QC / commit",
   "type": "graph",
   "description": "Duration between block generation time until the moment it is first received by a voter / gathers full QC",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_creation_to_qc_s_sum[1m])/irate(libra_consensus_creation_to_qc_s_count[1m])",
     "legendFormat": "{{peer_id}}: QC"
    },
    {
     "expr": "irate(libra_consensus_creation_to_receival_s_sum[1m])/irate(libra_consensus_creation_to_receival_s_count[1m])",
     "legendFormat": "{{peer_id}}: vote"
    },
    {
     "expr": "irate(libra_consensus_creation_to_commit_s_sum[1m])/irate(libra_consensus_creation_to_commit_s_count[1m])",
     "legendFormat": "{{peer_id}: commit"
    }
   ]
  },
  { "title": "Main loop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Event Loop Idle Percent",
   "type": "graph",
   "description": "Percent of time the main Event Loop spends idle",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "1 -(irate(consensus_duration_sum{op='process_block_retrieval'}[1m]) + on (peer_id) irate(consensus_duration_sum{op='process_message'}[1m]) + on (peer_id) irate(consensus_duration_sum{op='process_local_timeout'}[1m])) / on(peer_id) irate(consensus_duration_sum{op='main_loop'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Event Loop process consensus msg",
   "type": "graph",
   "description": "Percent of time the main Event Loop spends for block retrieval",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='process_message'}[1m]) / on(peer_id) irate(consensus_duration_sum{op='main_loop'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Event Loop process block retrieval",
   "type": "graph",
   "description": "Percent of time the main Event Loop spends for block retrieval",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='process_block_retrieval'}[1m]) / on(peer_id) irate(consensus_duration_sum{op='main_loop'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Event Loop process local timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='process_local_timeout'}[1m]) / on(peer_id) irate(consensus_duration_sum{op='main_loop'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "description": "The error rate of main loop.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_error_count[1m]) / on (peer_id) irate(consensus_duration_count{op='main_loop'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Process vote",
   "type": "graph",
   "description": "Percent time spent in process vote compared to all consensus msg",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='process_vote'}[1m]) / on(peer_id) irate(consensus_duration_sum{op='process_message'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Process sync info",
   "type": "graph",
   "description": "Percent time spent in process sync info compared to all consensus msg",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='process_sync_info'}[1m]) / on(peer_id) irate(consensus_duration_sum{op='process_message'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Process proposal",
   "type": "graph",
   "description": "Percent time spent in process proposal compared to all consensus msg",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "percentunit", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='process_proposal'}[1m]) / on(peer_id) irate(consensus_duration_sum{op='process_message'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Current running function",
   "type": "graph",
   "description": "Useful when the node is stuck somewhere",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus_gauge{op='process_proposal_running'}",
     "legendFormat": "{{peer_id}}: proposal"
    },
    {
     "expr": "consensus_gauge{op='process_vote_running'}",
     "legendFormat": "{{peer_id}}: vote"
    },
    {
     "expr": "consensus_gauge{op='process_local_timeout_running'}",
     "legendFormat": "{{peer_id}}: timeout"
    },
    {
     "expr": "consensus_gauge{op='reconfig_running'}",
     "legendFormat": "{{peer_id}}: reconfig"
    },
    {
     "expr": "consensus_gauge{op='execute_block'}",
     "legendFormat": "{{peer_id}}: execute"
    },
    {
     "expr": "consensus_gauge{op='commit_block'}",
     "legendFormat": "{{peer_id}}: commit"
    },
    { "expr": "consensus_gauge{op='sync_to'}", "legendFormat": "{{peer_id}}: sync" },
    {
     "expr": "consensus_gauge{op='block_retrieval'}",
     "legendFormat": "{{peer_id}}: rpc"
    }
   ]
  },
  { "title": "RoundState", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Current Round",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "libra_consensus_current_round", "legendFormat": "{{peer_id}}" }
   ]
  },
  {
   "title": "Total timeout rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "count timeout rounds" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_timeout_rounds_count",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total local timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "count timeouts" }
   ],
   "targets": [
    { "expr": "libra_consensus_timeout_count", "legendFormat": "{{peer_id}}" }
   ]
  },
  {
   "title": "Total QC rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "rounds per sec" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_qc_rounds_count",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Round timeout val",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "ms", "label": "timeout val (ms)" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_round_timeout_s",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "EpochState", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Current Epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "libra_consensus_epoch", "legendFormat": "{{peer_id}}" }
   ]
  },
  {
   "title": "Number of validators",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_current_epoch_validators",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "BlockStore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Pending blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_num_blocks_in_tree - 1",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_num_txns_per_block_sum[1m])/irate(libra_consensus_num_txns_per_block_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total wait duration",
   "type": "graph",
   "description": "Total time the node has to wait before inserting the block",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_wait_duration_s_sum",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "External call", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Execute block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "dtdurations", "label": "s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='execute_block'}[1m]) / irate(consensus_duration_count{op='execute_block'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Commit block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "dtdurations", "label": "s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='commit_block'}[1m]) / irate(consensus_duration_count{op='commit_block'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Safety rules",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "dtdurations", "label": "s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='safety_rules'}[1m]) / irate(consensus_duration_count{op='safety_rules'}[1m])",
     "legendFormat": "{{peer_id}} "
    },
    {
     "expr": "irate(consensus_duration_sum{op='safety_rules_init'}[1m]) / irate(consensus_duration_count{op='safety_rules_init'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Pull txn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "dtdurations", "label": "s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='pull_txn'}[1m]) / irate(consensus_duration_count{op='pull_txn'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Notify mempool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "yaxes": [
    { "format": "dtdurations", "label": "s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='notify_mempool'}[1m]) / irate(consensus_duration_count{op='notify_mempool'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "Notify state sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "yaxes": [
    { "format": "dtdurations", "label": "s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_duration_sum{op='notify_state_sync'}[1m]) / irate(consensus_duration_count{op='notify_state_sync'}[1m])",
     "legendFormat": "{{peer_id}} "
    }
   ]
  },
  {
   "title": "State sync count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short", "label": "count state sync" }
   ],
   "targets": [
    {
     "expr": "consensus_duration_count{op='sync_to'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total time spent on state sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "s", "label": "total time spent (s)" }
   ],
   "targets": [
    {
     "expr": "consensus_duration_sum{op='sync_to'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total sync info sent to help peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_sync_info_msg_sent_count",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Block retrieval count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "consensus_duration_count{op='block_retrieval'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total time spent on block retrieval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "yaxes": [
    { "format": "s", "label": "total time spent (s)" }
   ],
   "targets": [
    {
     "expr": "consensus_duration_sum{op='block_retrieval'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Proposer Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Proposals rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_proposals_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total vote on Nil",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 103 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    { "expr": "libra_consensus_vote_nil_count", "legendFormat": "{{peer_id}}" }
   ]
  },
  { "title": "SafetyState", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Last voted round",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_safety_rules_last_voted_round",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Preferred round",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_safety_rules_preferred_round",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Message queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Network -> Consensus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_pending_network_events{state=\"enqueued\"} - on (peer_id) libra_consensus_pending_network_events{state=\"dequeued\"}",
     "legendFormat": "{{peer_id}}: pending"
    },
    {
     "expr": "libra_consensus_pending_network_events{state=\"dropped\"}",
     "legendFormat": "{{peer_id}}: dropped"
    }
   ]
  },
  {
   "title": "Consensus -> Main loop (Consensus Msg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_channel_msgs_count{state=\"enqueued\"} - on (peer_id) libra_consensus_channel_msgs_count{state=\"dequeued\"} - on (peer_id) libra_consensus_channel_msgs_count{state=\"dropped\"}",
     "legendFormat": "{{peer_id}}: pending"
    },
    {
     "expr": "libra_consensus_channel_msgs_count{state=\"dropped\"}",
     "legendFormat": "{{peer_id}}: dropped"
    }
   ]
  },
  {
   "title": "Consensus -> Main loop (Block retrieval)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_block_retrieval_channel_msgs_count{state=\"enqueued\"} - on (peer_id) libra_consensus_block_retrieval_channel_msgs_count{state=\"dequeued\"}",
     "legendFormat": "{{peer_id}}: pending"
    },
    {
     "expr": "libra_consensus_block_retrieval_channel_msgs_count{state=\"dropped\"}",
     "legendFormat": "{{peer_id}}: dropped"
    }
   ]
  },
  {
   "title": "Pending self message & local timeout",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_consensus_pending_self_messages",
     "legendFormat": "{{peer_id}}: self message"
    },
    {
     "expr": "libra_consensus_pending_round_timeouts",
     "legendFormat": "{{peer_id}}: timeout"
    }
   ]
  },
  { "title": "Running", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } }
 ]
}