{
 "title": "Execution",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Block execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(executor_duration_sum{op='block_execute_time_s'}[1m]) / irate(executor_duration_count{op='block_execute_time_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "VM execute block time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(executor_duration_sum{op='vm_execute_block_time_s'}[1m]) / irate(executor_duration_count{op='vm_execute_block_time_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(executor_duration_sum{op='blocks_commit_time_s'}[1m]) / irate(executor_duration_count{op='blocks_commit_time_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(executor_duration_sum{op='storage_save_transactions_time_s'}[1m]) / irate(executor_duration_count{op='storage_save_transactions_time_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}