{
 "title": "Full Node",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "VFN Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Full Nodes",
   "type": "graph",
   "description": "Number of downstream full nodes a validator is connected to",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_network_peers{role_type=\"full_node\", state=\"connected\", role=\"validator\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Upstream Peers",
   "type": "graph",
   "description": "Number of upstream validator peers a full node can proxy transactions up to",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_admission_control_upstream_peer_count{role=\"fullnode\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Write Requests (Transaction Submission)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Transaction Submission Request Rate",
   "type": "graph",
   "description": "The rate at which transaction submission requests are received at admission control service",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "req / sec" }
   ],
   "targets": [
    {
     "expr": "irate(num_req{method=\"admission_control.AdmissionControl.SubmitTransaction\", role=\"fullnode\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Transaction Proxy Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_admission_control_transaction_proxy_count{role=\"fullnode\"}",
     "legendFormat": "{{peer_id}} : {{state}}"
    }
   ]
  },
  {
   "title": "Transaction Proxy Timeout",
   "type": "graph",
   "description": "Number of timeouts that happen when a full node proxies transactions upstream",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_admission_control_timeout_count{role=\"fullnode\"}",
     "legendFormat": "{{peer_id}} : {{state}}"
    }
   ]
  },
  {
   "title": "Transaction Proxy Latency",
   "type": "graph",
   "description": "The time it takes for a full node to proxy a transaction submission request to an upstream peer",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "libra_admission_control_transaction_submission_latency_s{role=\"fullnode\"}",
     "legendFormat": "{{peer_id}} : {{state}}"
    }
   ]
  },
  {
   "title": "Read Requests (UpdateToLatestLedger)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "UpdateToLatestLedger Query Rate",
   "type": "graph",
   "description": "The rate at which UpdateToLatestLedger queries are submitted to AC service",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "queries / sec" }
   ],
   "targets": [
    {
     "expr": "irate(num_req{method=\"admission_control.AdmissionControl.UpdateToLatestLedger\", role=\"fullnode\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed Version",
   "type": "graph",
   "description": "Current version of a full node",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_committed_version{role=\"fullnode\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}