{
 "title": "HAproxy",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "AC new connection rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_sessions_total{frontend=\"ac\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "AC denied connection rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_requests_denied_total{frontend=\"ac\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "AC request error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_request_errors_total_total{frontend=\"ac\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "AC active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{frontend=\"ac\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "AC backend queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=\"validators\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "AC healthy backends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_server{backend=\"validators\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_http_requests_total{frontend=\"faucet\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet denied request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_requests_denied_total{frontend=\"faucet\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet error request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_request_errors_total{frontend=\"faucet\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet backend queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=\"faucet_server\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet healthy backends",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_server{backend=\"faucet_server\"}",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}