{
 "title": "Logging",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Validator Logging Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_count{role=\"validator\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "FullNode Logging Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_count{role=\"fullnode\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "Validator Send To Logstash Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_tcp_submit_count{role=\"validator\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "FullNode Send To Logstash Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_tcp_submit_count{role=\"fullnode\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "Validator Connect To Logstash Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_tcp_connect_count{role=\"validator\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "FullNode Connect To Logstash Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_tcp_connect_count{role=\"fullnode\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "Validator Macro to Logstash Log Submission Failure Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-(rate(libra_struct_log_tcp_submit_count{role=\"validator\"}[1m])/rate(libra_struct_log_count{role=\"validator\"}[1m]))",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "FullNode Macro to Logstash Log Submission Failure Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-(rate(libra_struct_log_tcp_submit_count{role=\"fullnode\"}[1m])/rate(libra_struct_log_count{role=\"fullnode\"}[1m]))",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "Validator Connect Error Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_connect_error_count{role=\"validator\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "FullNode Connect Error Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_connect_error_count{role=\"fullnode\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "Validator Queue Error Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_queue_error_count{role=\"validator\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "FullNode Queue Error Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_queue_error_count{role=\"fullnode\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "Validator Send To Logstash Error Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_send_error_count{role=\"validator\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  },
  {
   "title": "FullNode Send To Logstash Error Rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libra_struct_log_send_error_count{role=\"fullnode\"}[1m])",
     "legendFormat": "{{partner}}"
    }
   ]
  }
 ]
}