{
 "title": "Mempool",
 "time": { "from": "2020-07-21T02:44:11.000Z", "to": "2020-07-21T02:51:08.000Z" },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mempool size",
   "type": "graph",
   "description": "total number of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_core_mempool_index_size{index=\"system_ttl\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "insertion result",
   "type": "graph",
   "description": "mempool insertion result of txn",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "txns / sec" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mempool{op=~'insert..*'}[1m]), 'status', '$1', 'op', '.*code: (.*?),.*')",
     "legendFormat": "{{peer_id}}: {{status}}"
    }
   ]
  },
  { "title": "Core Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client-expired txns",
   "type": "graph",
   "description": "number of transactions that expired in mempool based on client-specified expiration time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "txns" }
   ],
   "targets": [
    {
     "expr": "libra_core_mempool_gc_latency_count{type=\"system_ttl\"}",
     "legendFormat": "{{peer_id}} : {{status}}"
    }
   ]
  },
  {
   "title": "System-expired Txns",
   "type": "graph",
   "description": "Transactions that expired in mempool based on mempool-specified expiration time",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "txns" }
   ],
   "targets": [
    {
     "expr": "libra_core_mempool_gc_latency{type=\"system_ttl\"}",
     "legendFormat": "{{peer_id}} : {{status}}"
    }
   ]
  },
  { "title": "Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Accepted Transaction Commit Rate",
   "type": "graph",
   "description": "Rate of accepted transactions committed per second (notified from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "accepted txns / sec" }
   ],
   "targets": [
    {
     "expr": "rate(libra_mempool_service_transactions_sum{type=\"commit_accepted\"}[1m])\n",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg time for commit (accepted)",
   "type": "graph",
   "description": "average time it takes for mempool to process a commit of accepted transactions (sent from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(libra_mempool_service_latency_ms_sum{type=\"commit_accepted\"}[1m])/rate(libra_mempool_service_latency_ms_count{type=\"commit_accepted\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Rejected Transaction Commit Rate",
   "type": "graph",
   "description": "rate of rejected committed transactions (notified from consensus)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "txns/sec" }
   ],
   "targets": [
    {
     "expr": "rate(libra_mempool_service_transactions_sum{type=\"commit_rejected\"}[1m])\n"
    }
   ]
  },
  {
   "title": "Avg time of commit (rejected txns)",
   "type": "graph",
   "description": "avg time it takes to process committed rejected txns",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "rate(libra_mempool_service_latency_ms_sum{type=\"commit_rejected\"}[1m])/rate(libra_mempool_service_latency_ms_count{type=\"commit_rejected\"}[1m])"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "graph",
   "description": "Average size of consensus blocks pulled from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "avg block size" }
   ],
   "targets": [
    {
     "expr": "rate(libra_mempool_service_transactions_sum{type=\"get_block\"}[1m])/rate(libra_mempool_service_transactions_count{type=\"get_block\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg time for get_block",
   "type": "graph",
   "description": "Avg time it takes for consensus to pull block from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(libra_mempool_service_latency_ms_sum{type=\"get_block\"}[1m])/rate(libra_mempool_service_latency_ms_count{type=\"get_block\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Shared mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Incoming events per sec",
   "type": "graph",
   "description": "rate of shared mempool events from peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "events/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_shared_mempool_events[1m])",
     "legendFormat": "{{peer_id}}: {{event}}"
    }
   ]
  },
  {
   "title": "Shared Mempool Task Spawn Latency",
   "type": "graph",
   "description": "average time it takes  for mempool to spawn an async task",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(libra_bounded_executor_spawn_latency_sum[1m])/irate(libra_bounded_executor_spawn_latency_count[1m])",
     "legendFormat": "{{peer_id}} : {{task}}"
    }
   ]
  },
  { "title": "Incoming Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "New transactions received per sec",
   "type": "graph",
   "description": "rate of new transactions received",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "txns/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_shared_mempool_transactions_processed{status=\"received\"}[1m])",
     "legendFormat": "{{peer_id}} <- {{sender}}"
    }
   ]
  },
  {
   "title": "Successful transaction validation per sec",
   "type": "graph",
   "description": "rate of transactions that were successfully validated before mempool insertion\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "txns/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_shared_mempool_transactions_processed{status=\"success\"}[1m])",
     "legendFormat": "{{peer_id}} <- {{sender}}"
    }
   ]
  },
  {
   "title": "Txn Processing Latency",
   "type": "graph",
   "description": "avg time it takes to process incoming transactions, per incoming submission",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "sec / txn submission" }
   ],
   "targets": [
    {
     "expr": "irate(libra_shared_mempool_request_latency_sum[1m])/irate(libra_shared_mempool_request_latency_count[1m])",
     "legendFormat": "{{sender}} -> {{peer_id}}"
    }
   ]
  },
  {
   "title": "VM Validation Latency",
   "type": "graph",
   "description": "avg time it takes to VM-validate txns in a submission",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short", "label": "sec" }
   ],
   "targets": [
    {
     "expr": "irate(libra_mempool_process_txn_breakdown_latency_sum{portion=\"vm_validation\"}[1m])/irate(libra_mempool_process_txn_breakdown_latency_count{portion=\"vm_validation\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Outgoing Txn Broadcasts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Average Broadcast Size",
   "type": "graph",
   "description": "average number of transactions in a single broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "txns / broadcast" }
   ],
   "targets": [
    {
     "expr": "rate(libra_shared_mempool_transaction_broadcast_sum[1m])/rate(libra_shared_mempool_transaction_broadcast_count[1m])",
     "legendFormat": "{{peer_id}} -> {{recipient}}"
    }
   ]
  },
  {
   "title": "Broadcasted Txns Rate",
   "type": "graph",
   "description": "rate of transactions broadcasted to other peers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "txns/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_shared_mempool_transaction_broadcast_sum[1m])",
     "legendFormat": "{{peer_id}} -> {{recipient}}"
    }
   ]
  },
  {
   "title": "Broadcast Rate",
   "type": "graph",
   "description": "avg number of broadcasts / sec",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "broadcasts / sec" }
   ],
   "targets": [
    {
     "expr": "irate(libra_broadcast_latency_count[1m])",
     "legendFormat": "{{peer_id}} -> {{sender}}"
    }
   ]
  },
  {
   "title": "Broadcast execution time",
   "type": "graph",
   "description": "avg time it takes to execute a broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "secs / broadcast" }
   ],
   "targets": [
    {
     "expr": "irate(libra_broadcast_latency_sum[1m])/irate(libra_broadcast_latency_count[1m])",
     "legendFormat": "{{peer_id}} -> {{recipient}}"
    }
   ]
  },
  {
   "title": "Broadcast Roundtrip Time",
   "type": "graph",
   "description": "average time b/w broadcast sent and ACK coming back for it",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(libra_shared_mempool_broadcast_roundtrip_latency_sum[1m])/rate(libra_shared_mempool_broadcast_roundtrip_latency_count[1m])",
     "legendFormat": "{{peer_id}} -> {{recipient}}"
    }
   ]
  },
  {
   "title": "Pending Broadcasts",
   "type": "graph",
   "description": "number of sent broadcasts awaiting an ACK",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "# broadcasts" }
   ],
   "targets": [
    {
     "expr": "libra_shared_mempool_pending_broadcasts_count",
     "legendFormat": "{{peer_id}} -> {{recipient}}"
    }
   ]
  }
 ]
}