{
 "title": "Network",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outbound Message Throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(libra_network_direct_send_bytes_sum{state=\"sent\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Inbound Message Throughput(bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(libra_network_direct_send_bytes_sum{state=\"received\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Rate of outbound RPCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_network_rpc_messages{type=\"request\",state=\"sent\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Rate of inbound RPCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_network_rpc_messages{type=\"request\", state=\"received\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Connected Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_network_peers{role_type=\"validator\", state=\"connected\"}\n",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Verified Validator Discovery Notes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_network_discovery_notes{role_type=\"validator\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Inbound Validator Network Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_connections{network_id=\"Validator\", direction=\"Inbound\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Outbound Validator Network Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_connections{network_id=\"Validator\", direction=\"Outbound\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Inbound Public Network Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_connections{network_id=\"Public\", direction=\"Inbound\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Outbound Public Network Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_connections{network_id=\"Public\", direction=\"Outbound\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Direct Send Messages Drop Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libra_network_direct_send_messages{state=\"dropped\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "RPC Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libra_network_rpc_messages{type=\"request\",state=\"failed\"}[1m])",
     "legendFormat": "{{peer_id}}"
    },
    {
     "expr": "irate(libra_network_rpc_messages{type=\"request\",state=\"canceled\"}[1m])",
     "legendFormat": "{{peer_id}}"
    },
    {
     "expr": "irate(libra_network_rpc_messages{type=\"response\",state=\"failed\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Direct Send Outbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Pending Network Requests (Consensus/Mempool -> Network Provider)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_network_requests\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending Direct Send Requests (Network Provider -> Direct Send)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_direct_send_requests\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending Direct Send Outbound Messages (Direct Send -> Wire)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_peer_gauge{op=\"pending_direct_send_outbound_messages\"} > 0",
     "legendFormat": "{{peer_id}} -> {{remote_peer_id}}"
    }
   ]
  },
  { "title": "Direct Send Inbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Pending Notifications (Peer Manager -> Direct Send)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_peer_manager_direct_send_notifications\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending Notifications (Direct Send -> Network Provider)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_direct_send_notifications\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending Network Events (Network Provider -> Consensus)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_consensus_network_events\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending Network Events (Network Provider -> Mempool)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_mempool_network_events\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "RPC Outbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Pending Network Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_network_requests\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending RPC Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_rpc_requests\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "RPC Inbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Pending Notifications (Peer Manager -> RPC)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_peer_manager_rpc_notifications\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending Notifications (RPC -> Network Provider)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_rpc_notifications\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Pending Network Events (Network Provider -> Consensus)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op=\"pending_consensus_network_events\"} > 0",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}