{
 "title": "Overview",
 "description": "Top level view for Validator nodes + Faucet server",
 "tags": [
  "overview",
  "oncall"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "workspace", "label": "Workspace", "query": "label_values(workspace)" },
   {
    "name": "validator_peer_id",
    "label": "Validator Peer",
    "query": "label_values(node_boot_time_seconds{role=\"validator\"}, peer_id)"
   },
   {
    "name": "fullnode_peer_id",
    "label": "Fullnode Peer",
    "query": "label_values(node_boot_time_seconds{role=\"fullnode\"}, peer_id)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 1 }, "content": "# Workspace: $workspace" },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_boot_time_seconds{role=\"validator\"})"
    }
   ]
  },
  {
   "title": "Total Accounts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(storage_gauge{op=\"new_state_leaves\"} - ignoring (op) storage_gauge{op=\"stale_state_leaves\"})"
    }
   ]
  },
  {
   "title": "Total Stored Txn",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(storage_gauge{op=\"latest_transaction_version\"}) + 1"
    }
   ]
  },
  { "title": "General health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "AC SubmitTransaction Request Rate",
   "type": "graph",
   "description": "Rate of submit_transaction requests accepted by AdmissionControl, per-instance view.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "irate(libra_client_service_requests_count{type='submit'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "description": "Rate of block commits by consensus, including empty blocks.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "blocks per sec" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_last_committed_round[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed txns per sec",
   "type": "graph",
   "description": "Rate of transactions commits: can be zero if there are no new transactions.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "txns per sec" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_last_committed_version[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "graph",
   "description": "Average time it takes for a transaction to commit since it's received by Mempool.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted|commit_rejected\"}[1m])/irate(libra_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted|commit_rejected\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Failed txns rate",
   "type": "graph",
   "description": "Among all the transactions of the committed blocks, calculates the percentage of the transactions that failed the execution.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 * irate(libra_consensus_committed_txns_count{state=\"failed\"}[1m]) / irate(libra_consensus_committed_txns_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Timeout txns per sec",
   "type": "graph",
   "description": "Count the number of active transactions that timeout in mempool",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "txns / sec" }
   ],
   "targets": [
    {
     "expr": "irate(libra_core_mempool_gc_latency_count{status=\"active\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Faucet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  { "title": "Instance", "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 }, "content": "### Faucet" },
  {
   "title": "revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"faucet\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")\n",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"faucet\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='other_nodes',mode='idle',role='faucet'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',role='faucet'} + node_memory_Cached_bytes{workspace='$workspace',role='faucet'} + node_memory_Buffers_bytes{workspace='$workspace',role='faucet'}) / node_memory_MemTotal_bytes{workspace='$workspace',role='faucet'} * 100) by (role)"
    }
   ]
  },
  {
   "title": "Disk Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='other_nodes',role='faucet',mountpoint='/'} / node_filesystem_size_bytes{job='other_nodes'} * 100) by (role)"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "validator_peer_id" },
  {
   "title": "peer_id",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "content": "### $validator_peer_id",
   "targets": [
    { "legendFormat": "$validator_peer_id", "panelId": 429 }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 15 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$validator_peer_id\", container_name=\"validator\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 15 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$validator_peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_instances',mode='idle',peer_id='$validator_peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$validator_peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$validator_peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$validator_peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$validator_peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "/data Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_instances',peer_id='$validator_peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_instances',mountpoint='/data'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "/ Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_instances',peer_id='$validator_peer_id',mountpoint='/'} / node_filesystem_size_bytes{job='validator_instances', mountpoint='/'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{state='connected',peer_id='$validator_peer_id',role_type='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "peer_id",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "content": "### $validator_peer_id",
   "targets": [
    { "legendFormat": "$validator_peer_id", "panelId": 429 }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 18 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$validator_peer_id\", container_name=\"validator\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 18 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$validator_peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_instances',mode='idle',peer_id='$validator_peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$validator_peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$validator_peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$validator_peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$validator_peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "/data Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_instances',peer_id='$validator_peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_instances',mountpoint='/data'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "/ Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_instances',peer_id='$validator_peer_id',mountpoint='/'} / node_filesystem_size_bytes{job='validator_instances', mountpoint='/'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{state='connected',peer_id='$validator_peer_id',role_type='validator'}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "peer_id",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 21 },
   "content": "### $validator_peer_id",
   "targets": [
    { "legendFormat": "$validator_peer_id", "panelId": 429 }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 21 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"validator\", peer_id=\"$validator_peer_id\", container_name=\"validator\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 21 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"validator\", peer_id=\"$validator_peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='validator_instances',mode='idle',peer_id='$validator_peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$validator_peer_id'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$validator_peer_id'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$validator_peer_id'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$validator_peer_id'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "/data Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_instances',peer_id='$validator_peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='validator_instances',mountpoint='/data'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "/ Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='validator_instances',peer_id='$validator_peer_id',mountpoint='/'} / node_filesystem_size_bytes{job='validator_instances', mountpoint='/'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{state='connected',peer_id='$validator_peer_id',role_type='validator'}"
    }
   ]
  },
  { "title": "Fullnodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "fullnode_peer_id" },
  {
   "title": "peer_id",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 24 },
   "content": "### $fullnode_peer_id",
   "targets": [
    { "panelId": 429 }
   ]
  },
  {
   "title": "Revision",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 24 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "label_replace(build_info{workspace=\"$workspace\", role=\"fullnode\", peer_id=\"$fullnode_peer_id\"}, \"short_rev\", \"$1\", \"revision\", \"(.{7}).*\")",
     "legendFormat": "{{short_rev}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 24 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{workspace=\"$workspace\", role=\"fullnode\", peer_id=\"$fullnode_peer_id\"}"
    }
   ]
  },
  {
   "title": "CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (1 - avg((irate(node_cpu_seconds_total{job='fullnode_instances',mode='idle',peer_id='$fullnode_peer_id'}[5m]))))"
    }
   ]
  },
  {
   "title": "Mem Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (node_memory_MemFree_bytes{workspace='$workspace',peer_id='$fullnode_peer_id', role='fullnode'} + node_memory_Cached_bytes{workspace='$workspace',peer_id='$fullnode_peer_id', role='fullnode'} + node_memory_Buffers_bytes{workspace='$workspace',peer_id='$fullnode_peer_id', role='fullnode'}) / node_memory_MemTotal_bytes{workspace='$workspace',peer_id='$fullnode_peer_id', role='fullnode'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "/ Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='fullnode_instances',peer_id='$fullnode_peer_id',mountpoint='/'} / node_filesystem_size_bytes{job='fullnode_instances', mountpoint='/'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "/data Util",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - node_filesystem_avail_bytes{job='fullnode_instances',peer_id='$fullnode_peer_id',mountpoint='/data'} / node_filesystem_size_bytes{job='fullnode_instances',mountpoint='/data'} * 100) by (peer_id)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libra_network_peers{state='connected',peer_id='$fullnode_peer_id',role='fullnode'}"
    }
   ]
  }
 ]
}