{
 "title": "Performance",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "High level values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg e2e latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(mempool_duration_sum{op='e2e.latency'}[1m])/irate(mempool_duration_count{op='e2e.latency'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed successful txns per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "txns per sec" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_last_committed_version[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg num txns per block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "txns per block" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_num_txns_per_block_sum[1m])/irate(libra_consensus_num_txns_per_block_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Storage and Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Avg txn execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_txn_execution_duration_s_sum[1m])/irate(libra_consensus_txn_execution_duration_s_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg txn execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_txn_execution_duration_s_sum[1m])/irate(libra_consensus_txn_execution_duration_s_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg commit (store) time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_vm_execute_block_time_s_sum[1m])/irate(libra_consensus_vm_execute_block_time_s_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "AC and Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Avg time spent before consensus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(mempool_duration_sum{op='txn_pre_consensus_s'}[1m])/irate(mempool_duration_count{op='txn_pre_consensus_s'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Avg time since block creation to commit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_creation_to_commit_s_sum[1m])/irate(libra_consensus_creation_to_commit_s_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg time since block creation to strong commit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_creation_to_strong_commit_s_sum[1m])/irate(libra_consensus_creation_to_strong_commit_s_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg time since block creation to QC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_consensus_creation_to_qc_s_sum[1m])/irate(libra_consensus_creation_to_qc_s_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}