{
 "title": "State Sync",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Upstream Peers",
   "type": "graph",
   "description": "Number of peers that are currently active and upstream. They are the set of nodes a node can make sync requests to",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Num upstream peers" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_active_upstream_peers",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed Version",
   "type": "graph",
   "description": "Version of the latest ledger info committed. Any synced transactions beyond this version will not be considered committed",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "version number" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_version{type=\"committed\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Synced Version",
   "type": "graph",
   "description": "The version of the latest transaction synced",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "version number" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_version{type=\"synced\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Sync Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Apply Chunk Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_apply_chunk_success_total",
     "legendFormat": "{{peer_id}}: {{chunk_sender_id}}"
    }
   ]
  },
  {
   "title": "Apply Chunk Failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_apply_chunk_failure_total",
     "legendFormat": "{{peer_id}}: {{chunk_sender_id}}"
    }
   ]
  },
  {
   "title": "Target Version",
   "type": "graph",
   "description": "A version a node is trying to sync up to",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_version{type=\"target\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Chunk E2E Latency",
   "type": "graph",
   "description": "How long it took to sync a chunk, from requesting a chunk to fully processing and executing it",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_state_sync_sync_progress_duration_s_sum[1m]) / irate(libra_state_sync_sync_progress_duration_s_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "description": "number of txns in a chunk",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(libra_state_sync_chunk_size_sum[1m])/irate(libra_state_sync_chunk_size_count[1m])",
     "legendFormat": "{{peer_id}} <- {{sender}}"
    }
   ]
  },
  {
   "title": "Transaction Replayed",
   "type": "graph",
   "description": "number of transactions state synchronizer has retrieved since last restart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_chunk_size_sum",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Execute/Commit Chunk Time",
   "type": "graph",
   "description": "time it takes to execute and commit a chunk (via executor proxy)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(libra_state_sync_execute_chunk_duration_s_sum[1m])/irate(libra_state_sync_execute_chunk_duration_s_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Requests and Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Requests Sent",
   "type": "graph",
   "description": "Number of chunk requests sent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_requests_sent_total",
     "legendFormat": "{{peer_id}} -> {{requested_peer_id}}"
    }
   ]
  },
  {
   "title": "Response Received",
   "type": "graph",
   "description": "number of chunk responses received",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_process_msg_latency_count{type=\"chunk_response\"}",
     "legendFormat": "{{peer_id}} <- {{sender}}"
    }
   ]
  },
  {
   "title": "Chunk Request Process Time",
   "type": "graph",
   "description": "time it takes to process a chunk request",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(libra_state_sync_process_msg_latency_sum{type=\"chunk_request\"}[1m]) / irate(libra_state_sync_process_msg_latency_count{type=\"chunk_request\"}[1m])",
     "legendFormat": "{{peer_id}} <- {{sender}}"
    }
   ]
  },
  {
   "title": "Chunk Response Process Time",
   "type": "graph",
   "description": "time it takes to process a chunk response",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "irate(libra_state_sync_process_msg_latency_sum{type=\"chunk_response\"}[1m])/irate(libra_state_sync_process_msg_latency_count{type=\"chunk_response\"}[1m])",
     "legendFormat": "{{peer_id}} <- {{sender}}"
    }
   ]
  },
  {
   "title": "Subscription Delivery Count",
   "type": "graph",
   "description": "number of times a FN long-poll subscription was delivered (does not include times where the initial FN chunk request was immediately responded to)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_subscription_delivery_count",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Timeouts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Timeout",
   "type": "graph",
   "description": "Number of times a FN's long-poll sync request timed out",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "libra_state_sync_timeout_total", "legendFormat": "{{peer_id}}" }
   ]
  },
  {
   "title": "Mempool Commit Timeout",
   "type": "graph",
   "description": "Number of times state-sync <-> mempool communication times out",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_commit_timeout_total{component=\"mempool\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Consensus Commit Timeout",
   "type": "graph",
   "description": "Number of times consensus <-> state-sync communication times out",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_state_sync_commit_timeout_total{component=\"consensus\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}