{
 "title": "Storage",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cf_name", "query": "storage_gauge" },
   {
    "name": "api_name",
    "query": "libra_storage_api_latency_seconds_count"
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest vs Min Readable (Pruned Till) Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libra_storage_latest_transaction_version",
     "legendFormat": "{{peer_id}}"
    },
    {
     "expr": "libra_storage_pruner_least_readable_state_version",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Number of Accounts vs Internal Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(libra_storage_ledger{type=\"new_state_nodes\"} - ignoring(type) libra_storage_ledger{type=\"stale_state_nodes\"})",
     "legendFormat": "accounts"
    },
    {
     "expr": "max(libra_storage_ledger{type=\"new_state_nodes\"} - ignoring(type) libra_storage_ledger{type=\"stale_state_nodes\"} - ignoring(type) libra_storage_ledger{type=\"new_state_leaves\"} + ignoring(type) libra_storage_ledger{type=\"stale_state_leaves\"})",
     "legendFormat": "internal_nodes"
    }
   ]
  },
  {
   "title": "Avg Column Family Size By Name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by(cf_name)(libra_storage_cf_size_bytes)",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "title": "Commits per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    irate(schemadb_duration_count{op=~\"db_batch_commit_bytes_.*\"}[1m]),\n    \"db\", \"$1\", \"op\", \"db_batch_commit_bytes_(.*)\"\n)",
     "legendFormat": "{{peer_id}} {{db}}"
    }
   ]
  },
  {
   "title": "Commit bytes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    irate(schemadb_duration_sum{op=~\"db_batch_commit_bytes_.*\"}[1m]),\n    \"db\", \"$1\", \"op\", \"db_batch_commit_bytes_(.*)\"\n)",
     "legendFormat": "{{peer_id}} {{db}}"
    }
   ]
  },
  {
   "title": "Commit size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    schemadb_duration_sum{op=~\"db_batch_commit_bytes_.*\"} / schemadb_duration_count{op=~\"db_batch_commit_bytes_.*\"},\n    \"db\", \"$1\", \"op\", \"db_batch_commit_bytes_(.*)\"\n)",
     "legendFormat": "{{peer_id}} {{db}}"
    }
   ]
  },
  {
   "title": "Column Family Sizes By Validator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "repeat": "cf_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "$cf_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "storage_gauge{op='cf_size_bytes_$cf_name'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Avg Account Updates per Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(libra_storage_ledger{type=\"new_state_leaves\"}[10m]) / ignoring(type) irate(libra_storage_latest_transaction_version[10m]))",
     "legendFormat": "accounts/txn"
    }
   ]
  },
  {
   "title": "Avg Events Emits per Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(libra_storage_ledger{type=\"events_created\"}[10m]) / on(peer_id) irate(libra_storage_latest_transaction_version[10m]))",
     "legendFormat": "events/txn"
    }
   ]
  },
  {
   "title": "Avg Internal Node Updates per Account Update",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(irate(libra_storage_ledger{type=\"new_state_nodes\"}[10m]) / ignoring(type) irate(libra_storage_ledger{type=\"new_state_leaves\"}[10m])) - 1",
     "legendFormat": "internal nodes/accounts"
    }
   ]
  },
  {
   "title": "Record size (key + value) by Column Family",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n    avg by(op)(rate(schemadb_duration_sum{op=~\"db_put_bytes_.*\"}[10m])) / avg by(op)(rate(schemadb_duration_count{op=~\"db_put_bytes_.*\"}[10m])),\n    \"cf\", \"$1\", \"op\", \"db_put_bytes_(.*)\"\n)",
     "legendFormat": "{{cf}}"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "repeat": "api_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "$api_name",
     "type": "graph",
     "description": "api $api_name latency ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(libra_storage_api_latency_seconds_sum{api_name=\"$api_name\"}[1m]) / rate(libra_storage_api_latency_seconds_count{api_name=\"$api_name\"}[1m])",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  }
 ]
}