{
 "title": "Usage Stats",
 "description": "Usage statistics: account creation, txn submits and updates",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Accounts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(executor{op=\"num_accounts\"})",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "AC Total Submit Txn",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(num_req{method=\"admission_control.AdmissionControl.SubmitTransaction\"})"
    }
   ]
  },
  {
   "title": "AC Total Update Ledger",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(num_req{method=\"admission_control.AdmissionControl.UpdateToLatestLedger\"})"
    }
   ]
  },
  {
   "title": "Account Creation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(executor{op=\"num_accounts\"}[2m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "AC Txn Submit rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(num_req{method=\"admission_control.AdmissionControl.SubmitTransaction\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "AC Update Ledger rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(num_req{method=\"admission_control.AdmissionControl.UpdateToLatestLedger\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "AC active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_frontend_current_sessions{frontend=\"ac\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "AC denied connection rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_requests_denied_total{frontend=\"ac\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "AC Update Ledger processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "irate(duration_sum{method=\"admission_control.AdmissionControl.UpdateToLatestLedger\"}[1m])/irate(duration_count{method=\"admission_control.AdmissionControl.UpdateToLatestLedger\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Faucet request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_http_requests_total{frontend=\"faucet\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Faucet denied request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_requests_denied_total{frontend=\"faucet\"}[1m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Total Bytes Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_backend_bytes_out_total[1m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}