{
 "title": "Validators",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Container Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - ecs_start_time_seconds{role='validator'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_gauge{op='connected_peers',role='validator'}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_gauge{op='current_round',role='validator'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_gauge{op='last_committed_version',role='validator'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(mempool_duration_sum{op='e2e.latency'}[1m])/irate(mempool_duration_count{op='e2e.latency'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Committed Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus_gauge{op='last_committed_round',role='validator'}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Failed Transaction Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(consensus{op=\"failed_txns_count\"}[1m]) / irate(consensus{op=\"committed_txns_count\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Timeout Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(mempool{op=~\"gc.system_ttl_index.active|gc.expiration_time_index.active\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_gauge{op=\"txn.system_ttl_index\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}