{
 "title": "Vault",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Vault CPU Idle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode='idle',role='vault'}[1m])) / sum(irate(node_cpu_seconds_total{role='vault'}[1m]))"
    }
   ]
  },
  {
   "title": "Vault Memory Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{role='vault'}"
    }
   ]
  },
  {
   "title": "Vault GC Pauses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ns/s" }
   ],
   "targets": [
    {
     "expr": "irate(vault_runtime_total_gc_pause_ns[1m])"
    }
   ]
  },
  {
   "title": "Vault Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(vault_route_read_secret__count[1m])",
     "legendFormat": "read secret"
    },
    {
     "expr": "irate(vault_route_update_secret__count[1m])",
     "legendFormat": "update secret"
    },
    {
     "expr": "irate(vault_route_read_transit__count[1m])",
     "legendFormat": "read transit"
    }
   ]
  },
  {
   "title": "Vault Core Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "vault_core_handle_request", "legendFormat": "{{quantile}}" }
   ]
  }
 ]
}