{
 "title": "VM",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Transactions (Successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_user_transactions_executed{status=\"success\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "System Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_system_transactions_executed[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Validated Transactions (Successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_transactions_validated{status=\"success\"}[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Num Txns per Block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "txns per block" }
   ],
   "targets": [
    {
     "expr": "libra_vm_block_transaction_count",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Gas Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg Gas per User Txn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "gas" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_txn_gas_usage_sum[1m])/irate(libra_vm_txn_gas_usage_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Avg Txn Total Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_txn_total_seconds_sum[1m])/irate(libra_vm_txn_total_seconds_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg Txn Verification Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_txn_verification_seconds_sum[1m])/irate(libra_vm_txn_verification_seconds_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg Txn Validation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_txn_validation_seconds_sum[1m])/irate(libra_vm_txn_validation_seconds_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg Txn Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_txn_execution_seconds_sum[1m])/irate(libra_vm_txn_execution_seconds_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg Txn Prologue Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_txn_prologue_seconds_sum[1m])/irate(libra_vm_txn_prologue_seconds_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Avg Txn Epilogue Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(libra_vm_txn_epilogue_seconds_sum[1m])/irate(libra_vm_txn_epilogue_seconds_count[1m])",
     "legendFormat": "{{peer_id}}"
    }
   ]
  }
 ]
}