Command `sandbox publish src -v`:
Compiling Move modules...
Found and compiled 1 modules
Publishing a new module 00000000000000000000000000000042::Module (wrote 120 bytes)
Wrote 120 bytes of module ID's and code
Command `sandbox view storage/0x00000000000000000000000000000042/modules/Module.mv`:
module 42.Module {
struct S {
	i: u64
}

public foo(): S {
	0: CopyLoc[0](Arg0: u64)
	1: Pack[0](S)
	2: Ret
}
}
