[0] Transaction(0)
[1] Move VM Status: EXECUTED
[2] Transaction Status: Keep(EXECUTED)
[3] Transaction(1)
[4] Move VM Status: EXECUTED
[5] Transaction Status: Keep(EXECUTED)
[6] Transaction(2)
[7] Move VM Status: ABORTED { code: 1793, location: 00000000000000000000000000000001::DiemAccount }
[8] Transaction Status: Keep(ABORTED { code: 1793, location: 00000000000000000000000000000001::DiemAccount })
[9] Transaction(3)
[10] Move VM Status: EXECUTED
[11] Transaction Status: Keep(EXECUTED)
[12] Transaction(4)
[13] Move VM Status: EXECUTED
[14] Transaction Status: Keep(EXECUTED)
