[0] Transaction(0)
[1] Move VM Status: EXECUTED
[2] Transaction Status: Keep(EXECUTED)
[3] Transaction(1)
[4] Move VM Status: EXECUTED
[5] Transaction Status: Keep(EXECUTED)
[6] Transaction(2)
[7] Move VM Status: EXECUTED
[8] Transaction Status: Keep(EXECUTED)
[9] Transaction(3)
[10] Move VM Status: EXECUTED
[11] Transaction Status: Keep(EXECUTED)
[12] Transaction(4)
[13] Move VM Status: ERROR { status_code: INVALID_AUTH_KEY }
[14] Transaction Status: Discard(INVALID_AUTH_KEY)
[15] Transaction(5)
[16] Move VM Status: EXECUTED
[17] Transaction Status: Keep(EXECUTED)
[18] Transaction(6)
[19] Move VM Status: EXECUTED
[20] Transaction Status: Keep(EXECUTED)
