============ initial translation from Move ================

[variant baseline]
public fun A::mutate_at($t0|addr: address) {
     var $t1|s: &mut A::S
     var $t2: address
     var $t3: &mut A::S
     var $t4: u64
     var $t5: &mut A::S
     var $t6: &mut u64
  0: $t2 := copy($t0)
  1: $t3 := borrow_global<A::S>($t2)
  2: $t1 := $t3
  3: $t4 := 2
  4: $t5 := move($t1)
  5: $t6 := borrow_field<A::S>.x($t5)
  6: write_ref($t6, $t4)
  7: return ()
}


[variant baseline]
public fun A::read_at($t0|addr: address): u64 {
     var $t1|s: &A::S
     var $t2: address
     var $t3: &A::S
     var $t4: &A::S
     var $t5: &u64
     var $t6: u64
  0: $t2 := copy($t0)
  1: $t3 := borrow_global<A::S>($t2)
  2: $t1 := $t3
  3: $t4 := move($t1)
  4: $t5 := borrow_field<A::S>.x($t4)
  5: $t6 := read_ref($t5)
  6: return $t6
}


[variant baseline]
public fun B::move_from_test_incorrect($t0|addr1: address, $t1|addr2: address): B::T {
     var $t2|v: B::T
     var $t3|x0: u64
     var $t4|x1: u64
     var $t5: address
     var $t6: u64
     var $t7: address
     var $t8: B::T
     var $t9: address
     var $t10: u64
     var $t11: B::T
  0: $t5 := copy($t1)
  1: $t6 := A::read_at($t5)
  2: $t3 := $t6
  3: $t7 := copy($t0)
  4: $t8 := move_from<B::T>($t7)
  5: $t2 := $t8
  6: $t9 := copy($t1)
  7: $t10 := A::read_at($t9)
  8: $t4 := $t10
  9: assert Eq<u64>($t3, $t4)
 10: $t11 := move($t2)
 11: return $t11
}


[variant baseline]
public fun B::move_to_test_incorrect($t0|account: &signer, $t1|addr2: address) {
     var $t2|x0: u64
     var $t3|x1: u64
     var $t4: address
     var $t5: u64
     var $t6: &signer
     var $t7: u64
     var $t8: B::T
     var $t9: address
     var $t10: u64
  0: $t4 := copy($t1)
  1: $t5 := A::read_at($t4)
  2: $t2 := $t5
  3: $t6 := move($t0)
  4: $t7 := 2
  5: $t8 := pack B::T($t7)
  6: move_to<B::T>($t8, $t6)
  7: $t9 := copy($t1)
  8: $t10 := A::read_at($t9)
  9: $t3 := $t10
 10: assert Eq<u64>($t2, $t3)
 11: return ()
}


[variant baseline]
public fun B::mutate_S_test1_incorrect($t0|addr1: address, $t1|addr2: address) {
     var $t2|x0: u64
     var $t3|x1: u64
     var $t4: address
     var $t5: u64
     var $t6: address
     var $t7: address
     var $t8: u64
  0: $t4 := copy($t1)
  1: $t5 := A::read_at($t4)
  2: $t2 := $t5
  3: $t6 := copy($t0)
  4: A::mutate_at($t6)
  5: $t7 := copy($t1)
  6: $t8 := A::read_at($t7)
  7: $t3 := $t8
  8: assert Eq<u64>($t2, $t3)
  9: return ()
}


[variant baseline]
public fun B::mutate_S_test2_incorrect($t0|addr: address) {
     var $t1|x0: u64
     var $t2|x1: u64
     var $t3: address
     var $t4: u64
     var $t5: address
     var $t6: address
     var $t7: u64
  0: $t3 := copy($t0)
  1: $t4 := A::read_at($t3)
  2: $t1 := $t4
  3: $t5 := copy($t0)
  4: A::mutate_at($t5)
  5: $t6 := copy($t0)
  6: $t7 := A::read_at($t6)
  7: $t2 := $t7
  8: assert Eq<u64>($t1, $t2)
  9: return ()
}


[variant baseline]
public fun B::mutate_at_test_incorrect($t0|addr1: address, $t1|addr2: address) {
     var $t2|t: &mut B::T
     var $t3|x0: u64
     var $t4|x1: u64
     var $t5: address
     var $t6: u64
     var $t7: address
     var $t8: &mut B::T
     var $t9: u64
     var $t10: &mut B::T
     var $t11: &mut u64
     var $t12: address
     var $t13: u64
  0: $t5 := copy($t1)
  1: $t6 := A::read_at($t5)
  2: $t3 := $t6
  3: $t7 := copy($t0)
  4: $t8 := borrow_global<B::T>($t7)
  5: $t2 := $t8
  6: $t9 := 2
  7: $t10 := move($t2)
  8: $t11 := borrow_field<B::T>.x($t10)
  9: write_ref($t11, $t9)
 10: $t12 := copy($t1)
 11: $t13 := A::read_at($t12)
 12: $t4 := $t13
 13: assert Eq<u64>($t3, $t4)
 14: return ()
}

============ after pipeline `spec_instrumentation` ================

[variant verification]
public fun A::mutate_at($t0|addr: address) {
     var $t1|s: &mut A::S
     var $t2: &mut A::S
     var $t3: num
     var $t4: u64
     var $t5: &mut u64
  0: assume WellFormed($t0)
  1: assume forall $rsc: ResourceDomain<A::S>(): WellFormed($rsc)
  2: @1 := save_mem(A::S)
     # VC: caller does not have permission to modify `A::S` at given address at tests/spec_instrumentation/modifies.move:18:17+17
  3: assert CanModify<A::S>($t0)
  4: $t2 := borrow_global<A::S>($t0) on_abort goto 14 with $t3
  5: $t4 := 2
  6: $t5 := borrow_field<A::S>.x($t2)
  7: write_ref($t5, $t4)
  8: write_back[Reference($t2)]($t5)
  9: write_back[A::S]($t2)
 10: label L1
     # VC: function does not abort under this condition at tests/spec_instrumentation/modifies.move:24:9+27
 11: assert Not(Not(exists[@1]<A::S>($t0)))
     # VC: post-condition does not hold at tests/spec_instrumentation/modifies.move:23:9+31
 12: assert Eq<u64>(select A::S.x(global<A::S>($t0)), 2)
 13: return ()
 14: label L2
     # VC: abort not covered by any of the `aborts_if` clauses at tests/spec_instrumentation/modifies.move:21:5+166
 15: assert Not(exists[@1]<A::S>($t0))
 16: abort($t3)
}


[variant verification]
public fun A::read_at($t0|addr: address): u64 {
     var $t1|s: A::S
     var $t2: A::S
     var $t3: num
     var $t4: u64
  0: assume WellFormed($t0)
  1: assume forall $rsc: ResourceDomain<A::S>(): WellFormed($rsc)
  2: @0 := save_mem(A::S)
  3: $t2 := get_global<A::S>($t0) on_abort goto 9 with $t3
  4: $t4 := get_field<A::S>.x($t2)
  5: label L1
     # VC: function does not abort under this condition at tests/spec_instrumentation/modifies.move:13:9+27
  6: assert Not(Not(exists[@0]<A::S>($t0)))
     # VC: post-condition does not hold at tests/spec_instrumentation/modifies.move:14:9+36
  7: assert Eq<u64>($t4, select A::S.x(global<A::S>($t0)))
  8: return $t4
  9: label L2
     # VC: abort not covered by any of the `aborts_if` clauses at tests/spec_instrumentation/modifies.move:11:5+135
 10: assert Not(exists[@0]<A::S>($t0))
 11: abort($t3)
}


[variant verification]
public fun B::move_from_test_incorrect($t0|addr1: address, $t1|addr2: address): B::T {
     var $t2|v: B::T
     var $t3|x0: u64
     var $t4|x1: u64
     var $t5: bool
     var $t6: num
     var $t7: u64
     var $t8: B::T
     var $t9: bool
     var $t10: u64
  0: assume WellFormed($t0)
  1: assume WellFormed($t1)
  2: assume forall $rsc: ResourceDomain<A::S>(): WellFormed($rsc)
  3: assume forall $rsc: ResourceDomain<B::T>(): WellFormed($rsc)
     # >> opaque call: $t5 := A::read_at($t1)
  4: nop
  5: assume Identical($t5, Not(exists<A::S>($t1)))
  6: if ($t5) goto 7 else goto 10
  7: label L4
  8: trace_abort($t6)
  9: goto 29
 10: label L3
 11: assume WellFormed($t7)
 12: assume Eq<u64>($t7, select A::S.x(global<A::S>($t1)))
     # << opaque call: $t5 := A::read_at($t1)
 13: nop
     # VC: caller does not have permission to modify `B::T` at given address at tests/spec_instrumentation/modifies.move:65:17+9
 14: assert CanModify<B::T>($t0)
 15: $t8 := move_from<B::T>($t0) on_abort goto 29 with $t6
     # >> opaque call: $t7 := A::read_at($t1)
 16: nop
 17: assume Identical($t9, Not(exists<A::S>($t1)))
 18: if ($t9) goto 19 else goto 22
 19: label L6
 20: trace_abort($t6)
 21: goto 29
 22: label L5
 23: assume WellFormed($t10)
 24: assume Eq<u64>($t10, select A::S.x(global<A::S>($t1)))
     # << opaque call: $t7 := A::read_at($t1)
 25: nop
 26: assert Eq<u64>($t7, $t10)
 27: label L1
 28: return $t8
 29: label L2
 30: abort($t6)
}


[variant verification]
public fun B::move_to_test_incorrect($t0|account: signer, $t1|addr2: address) {
     var $t2|x0: u64
     var $t3|x1: u64
     var $t4: bool
     var $t5: num
     var $t6: u64
     var $t7: u64
     var $t8: B::T
     var $t9: bool
     var $t10: u64
  0: assume WellFormed($t0)
  1: assume WellFormed($t1)
  2: assume forall $rsc: ResourceDomain<A::S>(): WellFormed($rsc)
  3: assume forall $rsc: ResourceDomain<B::T>(): WellFormed($rsc)
     # >> opaque call: $t4 := A::read_at($t1)
  4: nop
  5: assume Identical($t4, Not(exists<A::S>($t1)))
  6: if ($t4) goto 7 else goto 10
  7: label L4
  8: trace_abort($t5)
  9: goto 31
 10: label L3
 11: assume WellFormed($t6)
 12: assume Eq<u64>($t6, select A::S.x(global<A::S>($t1)))
     # << opaque call: $t4 := A::read_at($t1)
 13: nop
 14: $t7 := 2
 15: $t8 := pack B::T($t7)
     # VC: caller does not have permission to modify `B::T` at given address at tests/spec_instrumentation/modifies.move:52:9+7
 16: assert CanModify<B::T>($t0)
 17: move_to<B::T>($t8, $t0) on_abort goto 31 with $t5
     # >> opaque call: $t7 := A::read_at($t1)
 18: nop
 19: assume Identical($t9, Not(exists<A::S>($t1)))
 20: if ($t9) goto 21 else goto 24
 21: label L6
 22: trace_abort($t5)
 23: goto 31
 24: label L5
 25: assume WellFormed($t10)
 26: assume Eq<u64>($t10, select A::S.x(global<A::S>($t1)))
     # << opaque call: $t7 := A::read_at($t1)
 27: nop
 28: assert Eq<u64>($t6, $t10)
 29: label L1
 30: return ()
 31: label L2
 32: abort($t5)
}


[variant verification]
public fun B::mutate_S_test1_incorrect($t0|addr1: address, $t1|addr2: address) {
     var $t2|x0: u64
     var $t3|x1: u64
     var $t4: bool
     var $t5: num
     var $t6: u64
     var $t7: bool
     var $t8: bool
     var $t9: u64
  0: assume WellFormed($t0)
  1: assume WellFormed($t1)
  2: assume forall $rsc: ResourceDomain<A::S>(): WellFormed($rsc)
  3: assume Neq<address>($t0, $t1)
     # >> opaque call: $t4 := A::read_at($t1)
  4: nop
  5: assume Identical($t4, Not(exists<A::S>($t1)))
  6: if ($t4) goto 7 else goto 10
  7: label L4
  8: trace_abort($t5)
  9: goto 38
 10: label L3
 11: assume WellFormed($t6)
 12: assume Eq<u64>($t6, select A::S.x(global<A::S>($t1)))
     # << opaque call: $t4 := A::read_at($t1)
 13: nop
     # >> opaque call: A::mutate_at($t0)
 14: nop
     # VC: caller does not have permission to modify `A::S` at given address at tests/spec_instrumentation/modifies.move:79:9+19
 15: assert CanModify<A::S>($t0)
 16: assume Identical($t7, Not(exists<A::S>($t0)))
 17: if ($t7) goto 18 else goto 21
 18: label L6
 19: trace_abort($t5)
 20: goto 38
 21: label L5
 22: modifies global<A::S>($t0)
 23: assume Eq<u64>(select A::S.x(global<A::S>($t0)), 2)
     # << opaque call: A::mutate_at($t0)
 24: nop
     # >> opaque call: $t5 := A::read_at($t1)
 25: nop
 26: assume Identical($t8, Not(exists<A::S>($t1)))
 27: if ($t8) goto 28 else goto 31
 28: label L8
 29: trace_abort($t5)
 30: goto 38
 31: label L7
 32: assume WellFormed($t9)
 33: assume Eq<u64>($t9, select A::S.x(global<A::S>($t1)))
     # << opaque call: $t5 := A::read_at($t1)
 34: nop
 35: assert Eq<u64>($t6, $t9)
 36: label L1
 37: return ()
 38: label L2
 39: abort($t5)
}


[variant verification]
public fun B::mutate_S_test2_incorrect($t0|addr: address) {
     var $t1|x0: u64
     var $t2|x1: u64
     var $t3: bool
     var $t4: num
     var $t5: u64
     var $t6: bool
     var $t7: bool
     var $t8: u64
  0: assume WellFormed($t0)
  1: assume forall $rsc: ResourceDomain<A::S>(): WellFormed($rsc)
     # >> opaque call: $t3 := A::read_at($t0)
  2: nop
  3: assume Identical($t3, Not(exists<A::S>($t0)))
  4: if ($t3) goto 5 else goto 8
  5: label L4
  6: trace_abort($t4)
  7: goto 36
  8: label L3
  9: assume WellFormed($t5)
 10: assume Eq<u64>($t5, select A::S.x(global<A::S>($t0)))
     # << opaque call: $t3 := A::read_at($t0)
 11: nop
     # >> opaque call: A::mutate_at($t0)
 12: nop
     # VC: caller does not have permission to modify `A::S` at given address at tests/spec_instrumentation/modifies.move:92:9+18
 13: assert CanModify<A::S>($t0)
 14: assume Identical($t6, Not(exists<A::S>($t0)))
 15: if ($t6) goto 16 else goto 19
 16: label L6
 17: trace_abort($t4)
 18: goto 36
 19: label L5
 20: modifies global<A::S>($t0)
 21: assume Eq<u64>(select A::S.x(global<A::S>($t0)), 2)
     # << opaque call: A::mutate_at($t0)
 22: nop
     # >> opaque call: $t4 := A::read_at($t0)
 23: nop
 24: assume Identical($t7, Not(exists<A::S>($t0)))
 25: if ($t7) goto 26 else goto 29
 26: label L8
 27: trace_abort($t4)
 28: goto 36
 29: label L7
 30: assume WellFormed($t8)
 31: assume Eq<u64>($t8, select A::S.x(global<A::S>($t0)))
     # << opaque call: $t4 := A::read_at($t0)
 32: nop
 33: assert Eq<u64>($t5, $t8)
 34: label L1
 35: return ()
 36: label L2
 37: abort($t4)
}


[variant verification]
public fun B::mutate_at_test_incorrect($t0|addr1: address, $t1|addr2: address) {
     var $t2|t: &mut B::T
     var $t3|x0: u64
     var $t4|x1: u64
     var $t5: bool
     var $t6: num
     var $t7: u64
     var $t8: &mut B::T
     var $t9: u64
     var $t10: &mut u64
     var $t11: bool
     var $t12: u64
  0: assume WellFormed($t0)
  1: assume WellFormed($t1)
  2: assume forall $rsc: ResourceDomain<A::S>(): WellFormed($rsc)
  3: assume forall $rsc: ResourceDomain<B::T>(): WellFormed($rsc)
     # >> opaque call: $t5 := A::read_at($t1)
  4: nop
  5: assume Identical($t5, Not(exists<A::S>($t1)))
  6: if ($t5) goto 7 else goto 10
  7: label L4
  8: trace_abort($t6)
  9: goto 34
 10: label L3
 11: assume WellFormed($t7)
 12: assume Eq<u64>($t7, select A::S.x(global<A::S>($t1)))
     # << opaque call: $t5 := A::read_at($t1)
 13: nop
     # VC: caller does not have permission to modify `B::T` at given address at tests/spec_instrumentation/modifies.move:38:17+17
 14: assert CanModify<B::T>($t0)
 15: $t8 := borrow_global<B::T>($t0) on_abort goto 34 with $t6
 16: $t9 := 2
 17: $t10 := borrow_field<B::T>.x($t8)
 18: write_ref($t10, $t9)
 19: write_back[Reference($t8)]($t10)
 20: write_back[B::T]($t8)
     # >> opaque call: $t9 := A::read_at($t1)
 21: nop
 22: assume Identical($t11, Not(exists<A::S>($t1)))
 23: if ($t11) goto 24 else goto 27
 24: label L6
 25: trace_abort($t6)
 26: goto 34
 27: label L5
 28: assume WellFormed($t12)
 29: assume Eq<u64>($t12, select A::S.x(global<A::S>($t1)))
     # << opaque call: $t9 := A::read_at($t1)
 30: nop
 31: assert Eq<u64>($t7, $t12)
 32: label L1
 33: return ()
 34: label L2
 35: abort($t6)
}
