============ initial translation from Move ================

[variant baseline]
fun Test::get_and_incr($t0|addr: address): u64 {
     var $t1|r: &mut Test::R
     var $t2|v: u64
     var $t3: address
     var $t4: bool
     var $t5: bool
     var $t6: u64
     var $t7: address
     var $t8: &mut Test::R
     var $t9: &mut Test::R
     var $t10: &u64
     var $t11: u64
     var $t12: &mut Test::R
     var $t13: &u64
     var $t14: u64
     var $t15: u64
     var $t16: u64
     var $t17: &mut Test::R
     var $t18: &mut u64
     var $t19: u64
  0: $t3 := copy($t0)
  1: $t4 := exists<Test::R>($t3)
  2: $t5 := !($t4)
  3: if ($t5) goto 6 else goto 4
  4: label L1
  5: goto 9
  6: label L0
  7: $t6 := 33
  8: abort($t6)
  9: label L2
 10: $t7 := copy($t0)
 11: $t8 := borrow_global<Test::R>($t7)
 12: $t1 := $t8
 13: $t9 := copy($t1)
 14: $t10 := borrow_field<Test::R>.v($t9)
 15: $t11 := read_ref($t10)
 16: $t2 := $t11
 17: $t12 := copy($t1)
 18: $t13 := borrow_field<Test::R>.v($t12)
 19: $t14 := read_ref($t13)
 20: $t15 := 1
 21: $t16 := +($t14, $t15)
 22: $t17 := move($t1)
 23: $t18 := borrow_field<Test::R>.v($t17)
 24: write_ref($t18, $t16)
 25: $t19 := copy($t2)
 26: return $t19
}


[variant baseline]
fun Test::incr_twice() {
     var $t0: address
     var $t1: u64
     var $t2: address
     var $t3: u64
  0: $t0 := 0x1
  1: $t1 := Test::get_and_incr($t0)
  2: destroy($t1)
  3: $t2 := 0x1
  4: $t3 := Test::get_and_incr($t2)
  5: destroy($t3)
  6: return ()
}

============ after pipeline `spec_instrumentation` ================

[variant verification]
fun Test::get_and_incr($t0|addr: address): u64 {
     var $t1|r: &mut Test::R
     var $t2|v: u64
     var $t3: bool
     var $t4: bool
     var $t5: u64
     var $t6: num
     var $t7: u64
     var $t8: u64
     var $t9: u64
     var $t10: u64
     var $t11: &mut u64
     # VC: `precondition does not hold at this call` at tests/spec_instrumentation/opaque_call.move:15:6+21
  0: assume Or(Neq<address>($t0, 0), Or(Not(exists[@0]<Test::R>($t0)), Ge(Add(select Test::R.v(global[@0]<Test::R>($t0)), 1), 18446744073709551615)))
  1: @0 := save_mem(Test::R)
  2: $t3 := exists<Test::R>($t0)
  3: $t4 := !($t3)
  4: if ($t4) goto 7 else goto 5
  5: label L1
  6: goto 11
  7: label L0
  8: $t5 := 33
  9: $t6 := move($t5)
 10: goto 28
 11: label L2
     # VC: `caller does not have permission to modify `Test::R` at given address` at tests/spec_instrumentation/opaque_call.move:8:14+17
 12: assert CanModify<Test::R>($t0)
 13: $t1 := borrow_global<Test::R>($t0) on_abort goto 28 with $t6
 14: $t7 := get_field<Test::R>.v($t1)
 15: $t8 := get_field<Test::R>.v($t1)
 16: $t9 := 1
 17: $t10 := +($t8, $t9) on_abort goto 28 with $t6
 18: $t11 := borrow_field<Test::R>.v($t1)
 19: write_ref($t11, $t10)
 20: write_back[Reference($t1)]($t11)
 21: write_back[Test::R]($t1)
 22: label L3
     # VC: `function does not abort under this condition` at tests/spec_instrumentation/opaque_call.move:16:6+35
 23: assert Not(Not(exists[@0]<Test::R>($t0)))
     # VC: `function does not abort under this condition` at tests/spec_instrumentation/opaque_call.move:17:6+56
 24: assert Not(Ge(Add(select Test::R.v(global[@0]<Test::R>($t0)), 1), 18446744073709551615))
     # VC: `post-condition does not hold` at tests/spec_instrumentation/opaque_call.move:19:6+56
 25: assert Eq<u64>(select Test::R.v(global<Test::R>($t0)), Add(select Test::R.v(global[@0]<Test::R>($t0)), 1))
     # VC: `post-condition does not hold` at tests/spec_instrumentation/opaque_call.move:20:6+36
 26: assert Eq<u64>($t7, select Test::R.v(global<Test::R>($t0)))
 27: return $t7
 28: label L4
     # VC: `abort not covered by any of the `aborts_if` clauses` at tests/spec_instrumentation/opaque_call.move:6:2+175
 29: assert Or(Not(exists[@0]<Test::R>($t0)), Ge(Add(select Test::R.v(global[@0]<Test::R>($t0)), 1), 18446744073709551615))
     # VC: `abort code not covered by any of the `aborts_if` or `aborts_with` clauses` at tests/spec_instrumentation/opaque_call.move:6:2+1
 30: assert Or(And(Not(exists[@0]<Test::R>($t0)), Eq(33, $t6)), Ge(Add(select Test::R.v(global[@0]<Test::R>($t0)), 1), 18446744073709551615))
 31: abort($t6)
}


[variant verification]
fun Test::incr_twice() {
     var $t0: address
     var $t1: bool
     var $t2: num
     var $t3: u64
     var $t4: address
     var $t5: bool
     var $t6: u64
  0: @1 := save_mem(Test::R)
  1: $t0 := 0x1
     # original call of opaque function: $t1 := Test::get_and_incr($t0)
     # VC: `precondition does not hold at this call` at tests/spec_instrumentation/opaque_call.move:15:6+21
  2: assert Or(Neq<address>($t0, 0), Or(Not(exists[@2]<Test::R>($t0)), Ge(Add(select Test::R.v(global[@2]<Test::R>($t0)), 1), 18446744073709551615)))
  3: @2 := save_mem(Test::R)
  4: modifies global<Test::R>($t0)
  5: assume Eq($t1, Or(Not(exists[@2]<Test::R>($t0)), Ge(Add(select Test::R.v(global[@2]<Test::R>($t0)), 1), 18446744073709551615)))
  6: if ($t1) goto 7 else goto 10
  7: label L4
  8: assume Or(And(Not(exists[@2]<Test::R>($t0)), Eq(33, $t2)), Ge(Add(select Test::R.v(global[@2]<Test::R>($t0)), 1), 18446744073709551615))
  9: goto 31
 10: label L3
 11: assume Eq<u64>(select Test::R.v(global<Test::R>($t0)), Add(select Test::R.v(global[@2]<Test::R>($t0)), 1))
 12: assume Eq<u64>($t3, select Test::R.v(global<Test::R>($t0)))
 13: destroy($t3)
 14: $t4 := 0x1
     # original call of opaque function: $t3 := Test::get_and_incr($t2)
 15: assert Or(Neq<address>($t4, 0), Or(Not(exists[@3]<Test::R>($t4)), Ge(Add(select Test::R.v(global[@3]<Test::R>($t4)), 1), 18446744073709551615)))
 16: @3 := save_mem(Test::R)
 17: modifies global<Test::R>($t4)
 18: assume Eq($t5, Or(Not(exists[@3]<Test::R>($t4)), Ge(Add(select Test::R.v(global[@3]<Test::R>($t4)), 1), 18446744073709551615)))
 19: if ($t5) goto 20 else goto 23
 20: label L6
 21: assume Or(And(Not(exists[@3]<Test::R>($t4)), Eq(33, $t2)), Ge(Add(select Test::R.v(global[@3]<Test::R>($t4)), 1), 18446744073709551615))
 22: goto 31
 23: label L5
 24: assume Eq<u64>(select Test::R.v(global<Test::R>($t4)), Add(select Test::R.v(global[@3]<Test::R>($t4)), 1))
 25: assume Eq<u64>($t6, select Test::R.v(global<Test::R>($t4)))
 26: destroy($t6)
 27: label L1
     # VC: `function does not abort under this condition` at tests/spec_instrumentation/opaque_call.move:28:6+34
 28: assert Not(Not(exists[@1]<Test::R>(1)))
     # VC: `post-condition does not hold` at tests/spec_instrumentation/opaque_call.move:29:6+54
 29: assert Eq<u64>(select Test::R.v(global<Test::R>(1)), Add(select Test::R.v(global[@1]<Test::R>(1)), 2))
 30: return ()
 31: label L2
     # VC: `abort not covered by any of the `aborts_if` clauses` at tests/spec_instrumentation/opaque_call.move:23:2+80
 32: assert Not(exists[@1]<Test::R>(1))
     # VC: `abort code not covered by any of the `aborts_if` or `aborts_with` clauses` at tests/spec_instrumentation/opaque_call.move:23:2+1
 33: assert And(Not(exists[@1]<Test::R>(1)), Eq(33, $t2))
 34: abort($t2)
}
