Command `check`:
Command `publish`:
Command `run storage/0x00000000000000000000000000000002/modules/ScriptFun.mv script_fun --signers 0xA --args 5`:
Execution failed with unexpected error INVALID_MAIN_FUNCTION_SIGNATURE
Command `view storage/0x0000000000000000000000000000000A/resources/0x00000000000000000000000000000002::ScriptFun::Called.bcs`:
Error: `move view <file>` must point to a valid file under storage
Command `run storage/0x00000000000000000000000000000002/modules/ScriptFun.mv private_fun --signers 0xA`:
Execution failed with unexpected error EXECUTE_SCRIPT_FUNCTION_CALLED_ON_NON_SCRIPT_VISIBLE
Command `run storage/0x00000000000000000000000000000002/modules/ScriptFun.mv public_fun --signers 0xA`:
Execution failed with unexpected error EXECUTE_SCRIPT_FUNCTION_CALLED_ON_NON_SCRIPT_VISIBLE
Command `run storage/0x00000000000000000000000000000002/modules/ScriptFun.mv nonexistent_fun --signers 0xA`:
Execution failed with unexpected error FUNCTION_RESOLUTION_FAILURE
