{
 "title": "Validator",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": { "query": "label_values(owner)" } }
  ]
 },
 "panels": [
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus Rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    { "expr": "diem_consensus_current_round" }
   ]
  },
  {
   "title": "Committed Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_last_committed_round"
    }
   ]
  },
  {
   "title": "State Sync Committed & Synced Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "diem_state_sync_version{type=\"committed\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "diem_state_sync_version{type=\"synced\"}",
     "legendFormat": "synced"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"system_ttl\"}"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_core_mempool_txn_commit_latency_sum{stage=~\"commit_accepted|commit_rejected\"}[5m])/rate(diem_core_mempool_txn_commit_latency_count{stage=~\"commit_accepted|commit_rejected\"}[5m])"
    }
   ]
  },
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_last_committed_round[5m])"
    }
   ]
  },
  {
   "title": "Block creation to signed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{stage=\"signed\"}[5m]) / rate(diem_consensus_block_tracing_count{stage=\"signed\"}[5m])"
    }
   ]
  },
  {
   "title": "Committed successful txns per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(diem_consensus_last_committed_version[5m])"
    }
   ]
  }
 ]
}