============ initial translation from Move ================

[variant baseline]
pub fun Test::incr($t0|a: address) {
     var $t1|r: &mut Test::R
     var $t2: address
     var $t3: &mut Test::R
     var $t4: &mut Test::R
     var $t5: &u64
     var $t6: u64
     var $t7: u64
     var $t8: u64
     var $t9: &mut Test::R
     var $t10: &mut u64
  0: $t2 := copy($t0)
  1: $t3 := borrow_global<Test::R>($t2)
  2: $t1 := $t3
  3: $t4 := copy($t1)
  4: $t5 := borrow_field<Test::R>.x($t4)
  5: $t6 := read_ref($t5)
  6: $t7 := 1
  7: $t8 := +($t6, $t7)
  8: $t9 := move($t1)
  9: $t10 := borrow_field<Test::R>.x($t9)
 10: write_ref($t10, $t8)
 11: return ()
}

============ after pipeline `global_invariant_instrumentation` ================

[variant verification]
pub fun Test::incr($t0|a: address) {
     var $t1|r: &mut Test::R
     var $t2: num
     var $t3: u64
     var $t4: u64
     var $t5: u64
     var $t6: &mut u64
  0: assume WellFormed($t0)
  1: assume forall $rsc: ResourceDomain<Test::R>(): WellFormed($rsc)
  2: $t1 := borrow_global<Test::R>($t0) on_abort goto 14 with $t2
  3: $t3 := get_field<Test::R>.x($t1)
  4: $t4 := 1
  5: $t5 := +($t3, $t4) on_abort goto 14 with $t2
  6: $t6 := borrow_field<Test::R>.x($t1)
  7: write_ref($t6, $t5)
  8: write_back[Reference($t1)]($t6)
     # state save for global update invariants
  9: @1 := save_mem(Test::R)
 10: write_back[Test::R]($t1)
     # global invariant at tests/global_invariant_instrumentation/update.move:7:9+82
     # VC: global memory invariant does not hold at tests/global_invariant_instrumentation/update.move:7:9+82
 11: assert forall a: TypeDomain<address>(): Lt(select Test::R.x(global[@1]<Test::R>(a)), select Test::R.x(global<Test::R>(a)))
 12: label L1
 13: return ()
 14: label L2
 15: abort($t2)
}
