error: 

   ┌── tests/move_check/locals/reassign_parameter.move:7:9 ───
   │
 7 │ ╭         if  (true) {
 8 │ │             let R { } = r;
 9 │ │         }
   │ ╰─────────^ Invalid return
   ·
 6 │         r = R {};
   │         - The parameter 'r' might still contain a value. The value does not have the 'drop' ability and must be consumed before the function returns
   ·
 4 │     public fun reassign_parameter(r: R) {
   │                                      - The type '0x8675309::M::R' does not have the ability 'drop'
   ·
 2 │     struct R {}
   │            - To satisfy the constraint, the 'drop' ability would need to be added here
   │

