warning[W09002]: unused variable
  ┌─ tests/move_check/locals/unused_copyable.move:5:12
  │
5 │     fun t0(i: u64, s: S) {
  │            ^ Unused parameter 'i'. Consider removing or prefixing with an underscore: '_i'

warning[W09002]: unused variable
  ┌─ tests/move_check/locals/unused_copyable.move:5:20
  │
5 │     fun t0(i: u64, s: S) {
  │                    ^ Unused parameter 's'. Consider removing or prefixing with an underscore: '_s'

warning[W09003]: unused assignment
  ┌─ tests/move_check/locals/unused_copyable.move:9:13
  │
9 │         let s = S{};
  │             ^ Unused assignment or binding for local 's'. Consider removing, replacing with '_', or prefixing with '_' (e.g., '_s')

