============ initial translation from Move ================

[variant baseline]
fun TestEliminateMutRefs::test1(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2|x_ref: &mut u64
     var $t3: u64
     var $t4: TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: &mut TestEliminateMutRefs::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: TestEliminateMutRefs::R
  0: $t3 := 3
  1: $t4 := pack TestEliminateMutRefs::R($t3)
  2: $t0 := $t4
  3: $t5 := borrow_local($t0)
  4: $t1 := $t5
  5: $t6 := move($t1)
  6: $t7 := borrow_field<TestEliminateMutRefs::R>.x($t6)
  7: $t2 := $t7
  8: $t8 := 0
  9: $t9 := move($t2)
 10: write_ref($t9, $t8)
 11: $t10 := move($t0)
 12: return $t10
}


[variant baseline]
fun TestEliminateMutRefs::test2($t0|x_ref: &mut u64, $t1|v: u64) {
     var $t2: u64
     var $t3: &mut u64
  0: $t2 := copy($t1)
  1: $t3 := move($t0)
  2: write_ref($t3, $t2)
  3: return ()
}


[variant baseline]
public fun TestEliminateMutRefs::test3($t0|r_ref: &mut TestEliminateMutRefs::R, $t1|v: u64) {
     var $t2|x_ref: &mut u64
     var $t3: &mut TestEliminateMutRefs::R
     var $t4: &mut u64
     var $t5: &mut u64
     var $t6: u64
  0: $t3 := move($t0)
  1: $t4 := borrow_field<TestEliminateMutRefs::R>.x($t3)
  2: $t2 := $t4
  3: $t5 := move($t2)
  4: $t6 := copy($t1)
  5: TestEliminateMutRefs::test2($t5, $t6)
  6: return ()
}


[variant baseline]
fun TestEliminateMutRefs::test4(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2: u64
     var $t3: TestEliminateMutRefs::R
     var $t4: &mut TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
  0: $t2 := 3
  1: $t3 := pack TestEliminateMutRefs::R($t2)
  2: $t0 := $t3
  3: $t4 := borrow_local($t0)
  4: $t1 := $t4
  5: $t5 := move($t1)
  6: $t6 := 0
  7: TestEliminateMutRefs::test3($t5, $t6)
  8: $t7 := move($t0)
  9: return $t7
}


[variant baseline]
public fun TestEliminateMutRefs::test5($t0|r_ref: &mut TestEliminateMutRefs::R): &mut u64 {
     var $t1: &mut TestEliminateMutRefs::R
     var $t2: &mut u64
  0: $t1 := move($t0)
  1: $t2 := borrow_field<TestEliminateMutRefs::R>.x($t1)
  2: return $t2
}


[variant baseline]
fun TestEliminateMutRefs::test6(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2|x_ref: &mut u64
     var $t3: u64
     var $t4: TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: &mut TestEliminateMutRefs::R
     var $t7: &mut u64
     var $t8: &mut u64
     var $t9: u64
     var $t10: TestEliminateMutRefs::R
  0: $t3 := 3
  1: $t4 := pack TestEliminateMutRefs::R($t3)
  2: $t0 := $t4
  3: $t5 := borrow_local($t0)
  4: $t1 := $t5
  5: $t6 := move($t1)
  6: $t7 := TestEliminateMutRefs::test5($t6)
  7: $t2 := $t7
  8: $t8 := move($t2)
  9: $t9 := 0
 10: TestEliminateMutRefs::test2($t8, $t9)
 11: $t10 := move($t0)
 12: return $t10
}


[variant baseline]
fun TestEliminateMutRefs::test7($t0|b: bool) {
     var $t1|r1: TestEliminateMutRefs::R
     var $t2|r2: TestEliminateMutRefs::R
     var $t3|r_ref: &mut TestEliminateMutRefs::R
     var $t4: u64
     var $t5: TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: &mut TestEliminateMutRefs::R
     var $t9: bool
     var $t10: &mut TestEliminateMutRefs::R
     var $t11: &mut TestEliminateMutRefs::R
     var $t12: &mut TestEliminateMutRefs::R
     var $t13: u64
  0: $t4 := 3
  1: $t5 := pack TestEliminateMutRefs::R($t4)
  2: $t1 := $t5
  3: $t6 := 4
  4: $t7 := pack TestEliminateMutRefs::R($t6)
  5: $t2 := $t7
  6: $t8 := borrow_local($t1)
  7: $t3 := $t8
  8: $t9 := copy($t0)
  9: if ($t9) goto 12 else goto 10
 10: label L1
 11: goto 18
 12: label L0
 13: $t10 := move($t3)
 14: destroy($t10)
 15: $t11 := borrow_local($t2)
 16: $t3 := $t11
 17: goto 18
 18: label L2
 19: $t12 := move($t3)
 20: $t13 := 0
 21: TestEliminateMutRefs::test3($t12, $t13)
 22: return ()
}


[variant baseline]
fun TestEliminateMutRefs::test8($t0|b: bool, $t1|n: u64, $t2|r_ref: &mut TestEliminateMutRefs::R) {
     var $t3|r1: TestEliminateMutRefs::R
     var $t4|r2: TestEliminateMutRefs::R
     var $t5|t_ref: &mut TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: u64
     var $t9: TestEliminateMutRefs::R
     var $t10: &mut TestEliminateMutRefs::R
     var $t11: u64
     var $t12: u64
     var $t13: bool
     var $t14: &mut TestEliminateMutRefs::R
     var $t15: u64
     var $t16: u64
     var $t17: u64
     var $t18: u64
     var $t19: bool
     var $t20: &mut TestEliminateMutRefs::R
     var $t21: &mut TestEliminateMutRefs::R
     var $t22: u64
     var $t23: u64
     var $t24: u64
     var $t25: bool
     var $t26: &mut TestEliminateMutRefs::R
     var $t27: &mut TestEliminateMutRefs::R
     var $t28: u64
     var $t29: &mut TestEliminateMutRefs::R
     var $t30: &mut TestEliminateMutRefs::R
     var $t31: u64
  0: $t6 := 3
  1: $t7 := pack TestEliminateMutRefs::R($t6)
  2: $t3 := $t7
  3: $t8 := 4
  4: $t9 := pack TestEliminateMutRefs::R($t8)
  5: $t4 := $t9
  6: $t10 := borrow_local($t4)
  7: $t5 := $t10
  8: goto 9
  9: label L7
 10: $t11 := 0
 11: $t12 := copy($t1)
 12: $t13 := <($t11, $t12)
 13: if ($t13) goto 16 else goto 14
 14: label L1
 15: goto 41
 16: label L0
 17: $t14 := move($t5)
 18: destroy($t14)
 19: $t15 := copy($t1)
 20: $t16 := 2
 21: $t17 := /($t15, $t16)
 22: $t18 := 0
 23: $t19 := ==($t17, $t18)
 24: if ($t19) goto 27 else goto 25
 25: label L4
 26: goto 31
 27: label L3
 28: $t20 := borrow_local($t3)
 29: $t5 := $t20
 30: goto 35
 31: label L5
 32: $t21 := borrow_local($t4)
 33: $t5 := $t21
 34: goto 35
 35: label L6
 36: $t22 := copy($t1)
 37: $t23 := 1
 38: $t24 := -($t22, $t23)
 39: $t1 := $t24
 40: goto 9
 41: label L2
 42: $t25 := copy($t0)
 43: if ($t25) goto 46 else goto 44
 44: label L9
 45: goto 53
 46: label L8
 47: $t26 := move($t5)
 48: destroy($t26)
 49: $t27 := move($t2)
 50: $t28 := 0
 51: TestEliminateMutRefs::test3($t27, $t28)
 52: goto 60
 53: label L10
 54: $t29 := move($t2)
 55: destroy($t29)
 56: $t30 := move($t5)
 57: $t31 := 0
 58: TestEliminateMutRefs::test3($t30, $t31)
 59: goto 60
 60: label L11
 61: return ()
}

============ after pipeline `mut_ref_instrumentation` ================

[variant baseline]
fun TestEliminateMutRefs::test1(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2|x_ref: &mut u64
     var $t3: u64
     var $t4: TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: &mut TestEliminateMutRefs::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: TestEliminateMutRefs::R
  0: $t3 := 3
  1: $t4 := pack TestEliminateMutRefs::R($t3)
  2: $t0 := $t4
  3: $t5 := borrow_local($t0)
  4: $t1 := $t5
  5: $t6 := move($t1)
  6: $t7 := borrow_field<TestEliminateMutRefs::R>.x($t6)
  7: $t2 := $t7
  8: $t8 := 0
  9: $t9 := move($t2)
 10: write_ref($t9, $t8)
 11: $t10 := move($t0)
 12: return $t10
}


[variant baseline]
fun TestEliminateMutRefs::test2($t0|x_ref: &mut u64, $t1|v: u64) {
     var $t2: u64
     var $t3: &mut u64
  0: $t2 := copy($t1)
  1: $t3 := copy($t0)
  2: write_ref($t3, $t2)
  3: trace_local[x_ref]($t0)
  4: return ()
}


[variant baseline]
public fun TestEliminateMutRefs::test3($t0|r_ref: &mut TestEliminateMutRefs::R, $t1|v: u64) {
     var $t2|x_ref: &mut u64
     var $t3: &mut TestEliminateMutRefs::R
     var $t4: &mut u64
     var $t5: &mut u64
     var $t6: u64
  0: $t3 := copy($t0)
  1: $t4 := borrow_field<TestEliminateMutRefs::R>.x($t3)
  2: $t2 := $t4
  3: $t5 := move($t2)
  4: $t6 := copy($t1)
  5: TestEliminateMutRefs::test2($t5, $t6)
  6: trace_local[r_ref]($t0)
  7: return ()
}


[variant baseline]
fun TestEliminateMutRefs::test4(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2: u64
     var $t3: TestEliminateMutRefs::R
     var $t4: &mut TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
  0: $t2 := 3
  1: $t3 := pack TestEliminateMutRefs::R($t2)
  2: $t0 := $t3
  3: $t4 := borrow_local($t0)
  4: $t1 := $t4
  5: $t5 := move($t1)
  6: $t6 := 0
  7: TestEliminateMutRefs::test3($t5, $t6)
  8: $t7 := move($t0)
  9: return $t7
}


[variant baseline]
public fun TestEliminateMutRefs::test5($t0|r_ref: &mut TestEliminateMutRefs::R): &mut u64 {
     var $t1: &mut TestEliminateMutRefs::R
     var $t2: &mut u64
  0: $t1 := copy($t0)
  1: $t2 := borrow_field<TestEliminateMutRefs::R>.x($t1)
  2: trace_local[r_ref]($t0)
  3: return $t2
}


[variant baseline]
fun TestEliminateMutRefs::test6(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2|x_ref: &mut u64
     var $t3: u64
     var $t4: TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: &mut TestEliminateMutRefs::R
     var $t7: &mut u64
     var $t8: &mut u64
     var $t9: u64
     var $t10: TestEliminateMutRefs::R
  0: $t3 := 3
  1: $t4 := pack TestEliminateMutRefs::R($t3)
  2: $t0 := $t4
  3: $t5 := borrow_local($t0)
  4: $t1 := $t5
  5: $t6 := move($t1)
  6: $t7 := TestEliminateMutRefs::test5($t6)
  7: $t2 := $t7
  8: $t8 := move($t2)
  9: $t9 := 0
 10: TestEliminateMutRefs::test2($t8, $t9)
 11: $t10 := move($t0)
 12: return $t10
}


[variant baseline]
fun TestEliminateMutRefs::test7($t0|b: bool) {
     var $t1|r1: TestEliminateMutRefs::R
     var $t2|r2: TestEliminateMutRefs::R
     var $t3|r_ref: &mut TestEliminateMutRefs::R
     var $t4: u64
     var $t5: TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: &mut TestEliminateMutRefs::R
     var $t9: bool
     var $t10: &mut TestEliminateMutRefs::R
     var $t11: &mut TestEliminateMutRefs::R
     var $t12: &mut TestEliminateMutRefs::R
     var $t13: u64
  0: $t4 := 3
  1: $t5 := pack TestEliminateMutRefs::R($t4)
  2: $t1 := $t5
  3: $t6 := 4
  4: $t7 := pack TestEliminateMutRefs::R($t6)
  5: $t2 := $t7
  6: $t8 := borrow_local($t1)
  7: $t3 := $t8
  8: $t9 := copy($t0)
  9: if ($t9) goto 12 else goto 10
 10: label L1
 11: goto 17
 12: label L0
 13: $t10 := move($t3)
 14: destroy($t10)
 15: $t11 := borrow_local($t2)
 16: $t3 := $t11
 17: label L2
 18: $t12 := move($t3)
 19: $t13 := 0
 20: TestEliminateMutRefs::test3($t12, $t13)
 21: return ()
}


[variant baseline]
fun TestEliminateMutRefs::test8($t0|b: bool, $t1|n: u64, $t2|r_ref: &mut TestEliminateMutRefs::R) {
     var $t3|r1: TestEliminateMutRefs::R
     var $t4|r2: TestEliminateMutRefs::R
     var $t5|t_ref: &mut TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: u64
     var $t9: TestEliminateMutRefs::R
     var $t10: &mut TestEliminateMutRefs::R
     var $t11: u64
     var $t12: u64
     var $t13: bool
     var $t14: &mut TestEliminateMutRefs::R
     var $t15: u64
     var $t16: u64
     var $t17: u64
     var $t18: u64
     var $t19: bool
     var $t20: &mut TestEliminateMutRefs::R
     var $t21: &mut TestEliminateMutRefs::R
     var $t22: u64
     var $t23: u64
     var $t24: u64
     var $t25: bool
     var $t26: &mut TestEliminateMutRefs::R
     var $t27: &mut TestEliminateMutRefs::R
     var $t28: u64
     var $t29: &mut TestEliminateMutRefs::R
     var $t30: &mut TestEliminateMutRefs::R
     var $t31: u64
  0: $t6 := 3
  1: $t7 := pack TestEliminateMutRefs::R($t6)
  2: $t3 := $t7
  3: $t8 := 4
  4: $t9 := pack TestEliminateMutRefs::R($t8)
  5: $t4 := $t9
  6: $t10 := borrow_local($t4)
  7: $t5 := $t10
  8: label L7
  9: $t11 := 0
 10: $t12 := copy($t1)
 11: $t13 := <($t11, $t12)
 12: if ($t13) goto 15 else goto 13
 13: label L1
 14: goto 39
 15: label L0
 16: $t14 := move($t5)
 17: destroy($t14)
 18: $t15 := copy($t1)
 19: $t16 := 2
 20: $t17 := /($t15, $t16)
 21: $t18 := 0
 22: $t19 := ==($t17, $t18)
 23: if ($t19) goto 26 else goto 24
 24: label L4
 25: goto 30
 26: label L3
 27: $t20 := borrow_local($t3)
 28: $t5 := $t20
 29: goto 33
 30: label L5
 31: $t21 := borrow_local($t4)
 32: $t5 := $t21
 33: label L6
 34: $t22 := copy($t1)
 35: $t23 := 1
 36: $t24 := -($t22, $t23)
 37: $t1 := $t24
 38: goto 8
 39: label L2
 40: $t25 := copy($t0)
 41: if ($t25) goto 44 else goto 42
 42: label L9
 43: goto 51
 44: label L8
 45: $t26 := move($t5)
 46: destroy($t26)
 47: $t27 := copy($t2)
 48: $t28 := 0
 49: TestEliminateMutRefs::test3($t27, $t28)
 50: goto 57
 51: label L10
 52: $t29 := copy($t2)
 53: destroy($t29)
 54: $t30 := move($t5)
 55: $t31 := 0
 56: TestEliminateMutRefs::test3($t30, $t31)
 57: label L11
 58: trace_local[r_ref]($t2)
 59: return ()
}
