[0] Transaction(0)
[1] Move VM Status: EXECUTED
[2] Transaction Status: Keep(EXECUTED)
[3] Transaction(1)
[4] Move VM Status: EXECUTED
[5] Transaction Status: Keep(EXECUTED)
[6] Transaction(2)
[7] "\n\nerror: \n\n   ┌── (file):2:5 ───\n   │\n 2 │     friend 0xD98F86E3303C97B00313854B8314F51B::A;\n   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid friend \'0xD98F86E3303C97B00313854B8314F51B::A\' in module \'0xD98F86E3303C97B00313854B8314F51B::B\'\n   ·\n 2 │     friend 0xD98F86E3303C97B00313854B8314F51B::A;\n   │     --------------------------------------------- This friend relationship creates a dependency cycle: \'0xD98F86E3303C97B00313854B8314F51B::B\' is a friend of \'0xD98F86E3303C97B00313854B8314F51B::A\' is a friend of \'0xD98F86E3303C97B00313854B8314F51B::B\'\n   │\n\n\n"
