Command `publish src/modules/`:
Command `run src/scripts/emit.move --signers 0xA --args 5`:
Command `doctor`:
Command `publish Events.move`:
Breaking change detected--publishing aborted. Re-run with --ignore-breaking-changes to publish anyway.
Layout API for structs of module 00000000000000000000000000000002::Events has changed. Need to do a data migration of published structs
Command `publish --ignore-breaking-changes Events.move`:
Command `doctor`:
Error: Failed to deserialize event "0.bcs" stored under address "0x0000000000000000000000000000000A"
