============ initial translation from Move ================

[variant baseline]
fun TestLiveVars::test1($t0|r_ref: &TestLiveVars::R): u64 {
     var $t1|x_ref: &u64
     var $t2: &TestLiveVars::R
     var $t3: &u64
     var $t4: &u64
     var $t5: u64
  0: $t2 := move($t0)
  1: $t3 := borrow_field<TestLiveVars::R>.x($t2)
  2: $t1 := $t3
  3: $t4 := move($t1)
  4: $t5 := read_ref($t4)
  5: return $t5
}


[variant baseline]
fun TestLiveVars::test2($t0|b: bool): u64 {
     var $t1|r1: TestLiveVars::R
     var $t2|r2: TestLiveVars::R
     var $t3|r_ref: &TestLiveVars::R
     var $t4: u64
     var $t5: TestLiveVars::R
     var $t6: u64
     var $t7: TestLiveVars::R
     var $t8: &TestLiveVars::R
     var $t9: bool
     var $t10: &TestLiveVars::R
     var $t11: &TestLiveVars::R
     var $t12: &TestLiveVars::R
     var $t13: u64
  0: $t4 := 3
  1: $t5 := pack TestLiveVars::R($t4)
  2: $t1 := $t5
  3: $t6 := 4
  4: $t7 := pack TestLiveVars::R($t6)
  5: $t2 := $t7
  6: $t8 := borrow_local($t1)
  7: $t3 := $t8
  8: $t9 := copy($t0)
  9: if ($t9) goto L0 else goto L1
 10: L1:
 11: goto L2
 12: L0:
 13: $t10 := move($t3)
 14: destroy($t10)
 15: $t11 := borrow_local($t2)
 16: $t3 := $t11
 17: goto L2
 18: L2:
 19: $t12 := move($t3)
 20: $t13 := TestLiveVars::test1($t12)
 21: return $t13
}


[variant baseline]
fun TestLiveVars::test3($t0|n: u64, $t1|r_ref: &TestLiveVars::R): u64 {
     var $t2|r1: TestLiveVars::R
     var $t3|r2: TestLiveVars::R
     var $t4: u64
     var $t5: TestLiveVars::R
     var $t6: u64
     var $t7: TestLiveVars::R
     var $t8: u64
     var $t9: u64
     var $t10: bool
     var $t11: &TestLiveVars::R
     var $t12: u64
     var $t13: u64
     var $t14: u64
     var $t15: u64
     var $t16: bool
     var $t17: &TestLiveVars::R
     var $t18: &TestLiveVars::R
     var $t19: u64
     var $t20: u64
     var $t21: u64
     var $t22: &TestLiveVars::R
     var $t23: u64
  0: $t4 := 3
  1: $t5 := pack TestLiveVars::R($t4)
  2: $t2 := $t5
  3: $t6 := 4
  4: $t7 := pack TestLiveVars::R($t6)
  5: $t3 := $t7
  6: goto L7
  7: L7:
  8: $t8 := 0
  9: $t9 := copy($t0)
 10: $t10 := <($t8, $t9)
 11: if ($t10) goto L0 else goto L1
 12: L1:
 13: goto L2
 14: L0:
 15: $t11 := move($t1)
 16: destroy($t11)
 17: $t12 := copy($t0)
 18: $t13 := 2
 19: $t14 := /($t12, $t13)
 20: $t15 := 0
 21: $t16 := ==($t14, $t15)
 22: if ($t16) goto L3 else goto L4
 23: L4:
 24: goto L5
 25: L3:
 26: $t17 := borrow_local($t2)
 27: $t1 := $t17
 28: goto L6
 29: L5:
 30: $t18 := borrow_local($t3)
 31: $t1 := $t18
 32: goto L6
 33: L6:
 34: $t19 := copy($t0)
 35: $t20 := 1
 36: $t21 := -($t19, $t20)
 37: $t0 := $t21
 38: goto L7
 39: L2:
 40: $t22 := move($t1)
 41: $t23 := TestLiveVars::test1($t22)
 42: return $t23
}

============ after pipeline `livevar` ================

[variant baseline]
fun TestLiveVars::test1($t0|r_ref: TestLiveVars::R): u64 {
     var $t1|x_ref: u64
     var $t2: TestLiveVars::R
     // live vars: r_ref
  0: $t2 := move($t0)
     // live vars: $t2
  1: $t1 := get_field<TestLiveVars::R>.x($t2)
     // live vars: x_ref
  2: return $t1
}


[variant baseline]
fun TestLiveVars::test2($t0|b: bool): u64 {
     var $t1|r1: TestLiveVars::R
     var $t2|r2: TestLiveVars::R
     var $t3|r_ref: TestLiveVars::R
     var $t4: bool
     var $t5: u64
     var $t6: u64
     var $t7: u64
     // live vars: b
  0: $t4 := move($t0)
     // live vars: $t4
  1: $t5 := 3
     // live vars: $t4, $t5
  2: $t1 := pack TestLiveVars::R($t5)
     // live vars: r1, $t4
  3: $t6 := 4
     // live vars: r1, $t4, $t6
  4: $t2 := pack TestLiveVars::R($t6)
     // live vars: r1, r2, $t4
  5: $t3 := $t1
     // live vars: r2, r_ref, $t4
  6: if ($t4) goto L0 else goto L1
     // live vars: r_ref
  7: L1:
     // live vars: r_ref
  8: goto L2
     // live vars: r2, r_ref
  9: L0:
     // live vars: r2, r_ref
 10: destroy($t3)
     // live vars: r2
 11: $t3 := $t2
     // live vars: r_ref
 12: goto L2
     // live vars: r_ref
 13: L2:
     // live vars: r_ref
 14: $t7 := TestLiveVars::test1($t3)
     // live vars: $t7
 15: return $t7
}


[variant baseline]
fun TestLiveVars::test3($t0|n: u64, $t1|r_ref: TestLiveVars::R): u64 {
     var $t2|r1: TestLiveVars::R
     var $t3|r2: TestLiveVars::R
     var $t4: u64
     var $t5: TestLiveVars::R
     var $t6: u64
     var $t7: u64
     var $t8: u64
     var $t9: bool
     var $t10: u64
     var $t11: u64
     var $t12: u64
     var $t13: bool
     var $t14: u64
     var $t15: u64
     // live vars: n, r_ref
  0: $t4 := move($t0)
     // live vars: r_ref, $t4
  1: $t5 := move($t1)
     // live vars: $t4, $t5
  2: $t6 := 3
     // live vars: $t4, $t5, $t6
  3: $t2 := pack TestLiveVars::R($t6)
     // live vars: r1, $t4, $t5
  4: $t7 := 4
     // live vars: r1, $t4, $t5, $t7
  5: $t3 := pack TestLiveVars::R($t7)
     // live vars: r1, r2, $t4, $t5
  6: goto L7
     // live vars: r1, r2, $t4, $t5
  7: L7:
     // live vars: r1, r2, $t4, $t5
  8: $t8 := 0
     // live vars: r1, r2, $t4, $t5, $t8
  9: $t9 := <($t8, $t4)
     // live vars: r1, r2, $t4, $t5, $t9
 10: if ($t9) goto L0 else goto L1
     // live vars: $t5
 11: L1:
     // live vars: $t5
 12: goto L2
     // live vars: r1, r2, $t4, $t5
 13: L0:
     // live vars: r1, r2, $t4, $t5
 14: destroy($t5)
     // live vars: r1, r2, $t4
 15: $t10 := 2
     // live vars: r1, r2, $t4, $t10
 16: $t11 := /($t4, $t10)
     // live vars: r1, r2, $t4, $t11
 17: $t12 := 0
     // live vars: r1, r2, $t4, $t11, $t12
 18: $t13 := ==($t11, $t12)
     // live vars: r1, r2, $t4, $t13
 19: if ($t13) goto L3 else goto L4
     // live vars: r1, r2, $t4
 20: L4:
     // live vars: r1, r2, $t4
 21: goto L5
     // live vars: r1, r2, $t4
 22: L3:
     // live vars: r1, r2, $t4
 23: $t5 := $t2
     // live vars: r1, r2, $t4, $t5
 24: goto L6
     // live vars: r1, r2, $t4
 25: L5:
     // live vars: r1, r2, $t4
 26: $t5 := $t3
     // live vars: r1, r2, $t4, $t5
 27: goto L6
     // live vars: r1, r2, $t4, $t5
 28: L6:
     // live vars: r1, r2, $t4, $t5
 29: $t14 := 1
     // live vars: r1, r2, $t4, $t5, $t14
 30: $t4 := -($t4, $t14)
     // live vars: r1, r2, $t4, $t5
 31: goto L7
     // live vars: $t5
 32: L2:
     // live vars: $t5
 33: $t15 := TestLiveVars::test1($t5)
     // live vars: $t15
 34: return $t15
}
