Command `sandbox publish`:
Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeSecondaryIndexes.mv read_indirect`:
Accesses:
Formal(0): Read
Formal(0)/0x1::ConcretizeSecondaryIndexes::Addr/a: Read
Formal(0)/0x1::ConcretizeSecondaryIndexes::Addr/a/0x1::ConcretizeSecondaryIndexes::S/f: Read

Locals:
Ret(0): Formal(0)/0x1::ConcretizeSecondaryIndexes::Addr/a/0x1::ConcretizeSecondaryIndexes::S/f

Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeSecondaryIndexes.mv read_indirect --concretize --args 0xA`:

Command `sandbox run storage/0x00000000000000000000000000000001/modules/ConcretizeSecondaryIndexes.mv publish_addr --signers 0xA --args 0xB`:
Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeSecondaryIndexes.mv read_indirect --concretize --args 0xA`:
0xa/0x1::ConcretizeSecondaryIndexes::Addr/a: Read

Command `sandbox run storage/0x00000000000000000000000000000001/modules/ConcretizeSecondaryIndexes.mv publish --signers 0xB`:
Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeSecondaryIndexes.mv read_indirect --concretize --args 0xA`:
0xa/0x1::ConcretizeSecondaryIndexes::Addr/a: Read
0xb/0x1::ConcretizeSecondaryIndexes::S/f: Read

Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeSecondaryIndexes.mv multi_arg --concretize --signers 0x1 --args 0xA 2`:
0xa/0x1::ConcretizeSecondaryIndexes::Addr/a: Read
0xb/0x1::ConcretizeSecondaryIndexes::S/f: Read

Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeVector.mv read_vec`:
Accesses:
Formal(0): Read
Formal(0)/0x1::ConcretizeVector::S/v: Read
Formal(0)/0x1::ConcretizeVector::S/v/[_]: Read
Formal(0)/0x1::ConcretizeVector::S/v/[_]/0x1::ConcretizeVector::T/f: Read

Locals:
Ret(0): Formal(0)/0x1::ConcretizeVector::S/v/[_]/0x1::ConcretizeVector::T/f

Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeVector.mv read_vec --concretize --args 0x1`:

Command `sandbox run storage/0x00000000000000000000000000000001/modules/ConcretizeVector.mv publish --signers 0x1 0x2`:
Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeVector.mv read_vec --concretize --args 0x1`:
0x1/0x1::ConcretizeVector::S/v: Read
0x1/0x1::ConcretizeVector::S/v/[_]: Read
0x1/0x1::ConcretizeVector::T/f: Read
0x2/0x1::ConcretizeVector::T/f: Read

Command `experimental read-write-set storage/0x00000000000000000000000000000001/modules/ConcretizeVector.mv write_vec --concretize --args 0x1 2`:
0x1/0x1::ConcretizeVector::S/v: Read
0x1/0x1::ConcretizeVector::S/v/[_]: Read
0x1/0x1::ConcretizeVector::T/f: Write
0x2/0x1::ConcretizeVector::T/f: Write

