============ initial translation from Move ================

[variant baseline]
fun TestEliminateMutRefs::test1(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2|x_ref: &mut u64
     var $t3: u64
     var $t4: TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: &mut TestEliminateMutRefs::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: TestEliminateMutRefs::R
  0: $t3 := 3
  1: $t4 := pack TestEliminateMutRefs::R($t3)
  2: $t0 := $t4
  3: $t5 := borrow_local($t0)
  4: $t1 := $t5
  5: $t6 := move($t1)
  6: $t7 := borrow_field<TestEliminateMutRefs::R>.x($t6)
  7: $t2 := $t7
  8: $t8 := 0
  9: $t9 := move($t2)
 10: write_ref($t9, $t8)
 11: $t10 := move($t0)
 12: return $t10
}


[variant baseline]
fun TestEliminateMutRefs::test2($t0|x_ref: &mut u64, $t1|v: u64) {
     var $t2: u64
     var $t3: &mut u64
  0: $t2 := copy($t1)
  1: $t3 := move($t0)
  2: write_ref($t3, $t2)
  3: return ()
}


[variant baseline]
pub fun TestEliminateMutRefs::test3($t0|r_ref: &mut TestEliminateMutRefs::R, $t1|v: u64) {
     var $t2|x_ref: &mut u64
     var $t3: &mut TestEliminateMutRefs::R
     var $t4: &mut u64
     var $t5: &mut u64
     var $t6: u64
  0: $t3 := move($t0)
  1: $t4 := borrow_field<TestEliminateMutRefs::R>.x($t3)
  2: $t2 := $t4
  3: $t5 := move($t2)
  4: $t6 := copy($t1)
  5: TestEliminateMutRefs::test2($t5, $t6)
  6: return ()
}


[variant baseline]
fun TestEliminateMutRefs::test4(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2: u64
     var $t3: TestEliminateMutRefs::R
     var $t4: &mut TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
  0: $t2 := 3
  1: $t3 := pack TestEliminateMutRefs::R($t2)
  2: $t0 := $t3
  3: $t4 := borrow_local($t0)
  4: $t1 := $t4
  5: $t5 := move($t1)
  6: $t6 := 0
  7: TestEliminateMutRefs::test3($t5, $t6)
  8: $t7 := move($t0)
  9: return $t7
}


[variant baseline]
pub fun TestEliminateMutRefs::test5($t0|r_ref: &mut TestEliminateMutRefs::R): &mut u64 {
     var $t1: &mut TestEliminateMutRefs::R
     var $t2: &mut u64
  0: $t1 := move($t0)
  1: $t2 := borrow_field<TestEliminateMutRefs::R>.x($t1)
  2: return $t2
}


[variant baseline]
fun TestEliminateMutRefs::test6(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2|x_ref: &mut u64
     var $t3: u64
     var $t4: TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: &mut TestEliminateMutRefs::R
     var $t7: &mut u64
     var $t8: &mut u64
     var $t9: u64
     var $t10: TestEliminateMutRefs::R
  0: $t3 := 3
  1: $t4 := pack TestEliminateMutRefs::R($t3)
  2: $t0 := $t4
  3: $t5 := borrow_local($t0)
  4: $t1 := $t5
  5: $t6 := move($t1)
  6: $t7 := TestEliminateMutRefs::test5($t6)
  7: $t2 := $t7
  8: $t8 := move($t2)
  9: $t9 := 0
 10: TestEliminateMutRefs::test2($t8, $t9)
 11: $t10 := move($t0)
 12: return $t10
}


[variant baseline]
fun TestEliminateMutRefs::test7($t0|b: bool) {
     var $t1|r1: TestEliminateMutRefs::R
     var $t2|r2: TestEliminateMutRefs::R
     var $t3|r_ref: &mut TestEliminateMutRefs::R
     var $t4: u64
     var $t5: TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: &mut TestEliminateMutRefs::R
     var $t9: bool
     var $t10: &mut TestEliminateMutRefs::R
     var $t11: &mut TestEliminateMutRefs::R
     var $t12: &mut TestEliminateMutRefs::R
     var $t13: u64
  0: $t4 := 3
  1: $t5 := pack TestEliminateMutRefs::R($t4)
  2: $t1 := $t5
  3: $t6 := 4
  4: $t7 := pack TestEliminateMutRefs::R($t6)
  5: $t2 := $t7
  6: $t8 := borrow_local($t1)
  7: $t3 := $t8
  8: $t9 := copy($t0)
  9: if ($t9) goto 12 else goto 10
 10: label L1
 11: goto 18
 12: label L0
 13: $t10 := move($t3)
 14: destroy($t10)
 15: $t11 := borrow_local($t2)
 16: $t3 := $t11
 17: goto 18
 18: label L2
 19: $t12 := move($t3)
 20: $t13 := 0
 21: TestEliminateMutRefs::test3($t12, $t13)
 22: return ()
}


[variant baseline]
fun TestEliminateMutRefs::test8($t0|b: bool, $t1|n: u64, $t2|r_ref: &mut TestEliminateMutRefs::R) {
     var $t3|r1: TestEliminateMutRefs::R
     var $t4|r2: TestEliminateMutRefs::R
     var $t5|t_ref: &mut TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: u64
     var $t9: TestEliminateMutRefs::R
     var $t10: &mut TestEliminateMutRefs::R
     var $t11: u64
     var $t12: u64
     var $t13: bool
     var $t14: &mut TestEliminateMutRefs::R
     var $t15: u64
     var $t16: u64
     var $t17: u64
     var $t18: u64
     var $t19: bool
     var $t20: &mut TestEliminateMutRefs::R
     var $t21: &mut TestEliminateMutRefs::R
     var $t22: u64
     var $t23: u64
     var $t24: u64
     var $t25: bool
     var $t26: &mut TestEliminateMutRefs::R
     var $t27: &mut TestEliminateMutRefs::R
     var $t28: u64
     var $t29: &mut TestEliminateMutRefs::R
     var $t30: &mut TestEliminateMutRefs::R
     var $t31: u64
  0: $t6 := 3
  1: $t7 := pack TestEliminateMutRefs::R($t6)
  2: $t3 := $t7
  3: $t8 := 4
  4: $t9 := pack TestEliminateMutRefs::R($t8)
  5: $t4 := $t9
  6: $t10 := borrow_local($t4)
  7: $t5 := $t10
  8: goto 9
  9: label L7
 10: $t11 := 0
 11: $t12 := copy($t1)
 12: $t13 := <($t11, $t12)
 13: if ($t13) goto 16 else goto 14
 14: label L1
 15: goto 41
 16: label L0
 17: $t14 := move($t5)
 18: destroy($t14)
 19: $t15 := copy($t1)
 20: $t16 := 2
 21: $t17 := /($t15, $t16)
 22: $t18 := 0
 23: $t19 := ==($t17, $t18)
 24: if ($t19) goto 27 else goto 25
 25: label L4
 26: goto 31
 27: label L3
 28: $t20 := borrow_local($t3)
 29: $t5 := $t20
 30: goto 35
 31: label L5
 32: $t21 := borrow_local($t4)
 33: $t5 := $t21
 34: goto 35
 35: label L6
 36: $t22 := copy($t1)
 37: $t23 := 1
 38: $t24 := -($t22, $t23)
 39: $t1 := $t24
 40: goto 9
 41: label L2
 42: $t25 := copy($t0)
 43: if ($t25) goto 46 else goto 44
 44: label L9
 45: goto 53
 46: label L8
 47: $t26 := move($t5)
 48: destroy($t26)
 49: $t27 := move($t2)
 50: $t28 := 0
 51: TestEliminateMutRefs::test3($t27, $t28)
 52: goto 60
 53: label L10
 54: $t29 := move($t2)
 55: destroy($t29)
 56: $t30 := move($t5)
 57: $t31 := 0
 58: TestEliminateMutRefs::test3($t30, $t31)
 59: goto 60
 60: label L11
 61: return ()
}

============ after pipeline `eliminate_mut_refs` ================

[variant baseline]
fun TestEliminateMutRefs::test1(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2|x_ref: &mut u64
     var $t3: u64
     var $t4: TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: &mut TestEliminateMutRefs::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: TestEliminateMutRefs::R
  0: $t3 := 3
  1: $t4 := pack TestEliminateMutRefs::R($t3)
  2: $t0 := $t4
  3: $t5 := borrow_local($t0)
  4: $t1 := $t5
  5: $t6 := move($t1)
  6: $t7 := borrow_field<TestEliminateMutRefs::R>.x($t6)
  7: $t2 := $t7
  8: $t8 := 0
  9: $t9 := move($t2)
 10: write_ref($t9, $t8)
 11: $t10 := move($t0)
 12: return $t10
}


[variant baseline]
fun TestEliminateMutRefs::test2($t0|x_ref: u64, $t1|v: u64): u64 {
     var $t2: u64
     var $t3: &mut u64
     var $t4: u64
     var $t5: &mut u64
     var $t6: u64
  0: $t4 := move($t0)
  1: $t6 := move($t1)
  2: $t5 := borrow_local($t4)
  3: $t2 := copy($t6)
  4: $t3 := move($t5)
  5: write_ref($t3, $t2)
  6: return $t4
}


[variant baseline]
pub fun TestEliminateMutRefs::test3($t0|r_ref: TestEliminateMutRefs::R, $t1|v: u64): TestEliminateMutRefs::R {
     var $t2|x_ref: &mut u64
     var $t3: &mut TestEliminateMutRefs::R
     var $t4: &mut u64
     var $t5: &mut u64
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: &mut TestEliminateMutRefs::R
     var $t9: u64
     var $t10: u64
  0: $t7 := move($t0)
  1: $t9 := move($t1)
  2: $t8 := borrow_local($t7)
  3: $t3 := move($t8)
  4: $t4 := borrow_field<TestEliminateMutRefs::R>.x($t3)
  5: $t2 := $t4
  6: $t5 := move($t2)
  7: $t6 := copy($t9)
  8: $t10 := read_ref($t5)
  9: $t10 := TestEliminateMutRefs::test2($t10, $t6)
 10: write_ref($t5, $t10)
 11: return $t7
}


[variant baseline]
fun TestEliminateMutRefs::test4(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2: u64
     var $t3: TestEliminateMutRefs::R
     var $t4: &mut TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: TestEliminateMutRefs::R
  0: $t2 := 3
  1: $t3 := pack TestEliminateMutRefs::R($t2)
  2: $t0 := $t3
  3: $t4 := borrow_local($t0)
  4: $t1 := $t4
  5: $t5 := move($t1)
  6: $t6 := 0
  7: $t8 := read_ref($t5)
  8: $t8 := TestEliminateMutRefs::test3($t8, $t6)
  9: write_ref($t5, $t8)
 10: $t7 := move($t0)
 11: return $t7
}


[variant baseline]
pub fun TestEliminateMutRefs::test5($t0|r_ref: TestEliminateMutRefs::R): (&mut u64, TestEliminateMutRefs::R) {
     var $t1: &mut TestEliminateMutRefs::R
     var $t2: &mut u64
     var $t3: TestEliminateMutRefs::R
     var $t4: &mut TestEliminateMutRefs::R
  0: $t3 := move($t0)
  1: $t4 := borrow_local($t3)
  2: $t1 := move($t4)
  3: $t2 := borrow_field<TestEliminateMutRefs::R>.x($t1)
  4: return ($t2, $t3)
}


[variant baseline]
fun TestEliminateMutRefs::test6(): TestEliminateMutRefs::R {
     var $t0|r: TestEliminateMutRefs::R
     var $t1|r_ref: &mut TestEliminateMutRefs::R
     var $t2|x_ref: &mut u64
     var $t3: u64
     var $t4: TestEliminateMutRefs::R
     var $t5: &mut TestEliminateMutRefs::R
     var $t6: &mut TestEliminateMutRefs::R
     var $t7: &mut u64
     var $t8: &mut u64
     var $t9: u64
     var $t10: TestEliminateMutRefs::R
     var $t11: u64
     var $t12: TestEliminateMutRefs::R
  0: $t3 := 3
  1: $t4 := pack TestEliminateMutRefs::R($t3)
  2: $t0 := $t4
  3: $t5 := borrow_local($t0)
  4: $t1 := $t5
  5: $t6 := move($t1)
  6: $t12 := read_ref($t6)
  7: ($t7, $t12) := TestEliminateMutRefs::test5($t12)
  8: write_ref($t6, $t12)
  9: splice[0 -> $t6]($t7)
 10: $t2 := $t7
 11: $t8 := move($t2)
 12: $t9 := 0
 13: $t11 := read_ref($t8)
 14: $t11 := TestEliminateMutRefs::test2($t11, $t9)
 15: write_ref($t8, $t11)
 16: $t10 := move($t0)
 17: return $t10
}


[variant baseline]
fun TestEliminateMutRefs::test7($t0|b: bool) {
     var $t1|r1: TestEliminateMutRefs::R
     var $t2|r2: TestEliminateMutRefs::R
     var $t3|r_ref: &mut TestEliminateMutRefs::R
     var $t4: u64
     var $t5: TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: &mut TestEliminateMutRefs::R
     var $t9: bool
     var $t10: &mut TestEliminateMutRefs::R
     var $t11: &mut TestEliminateMutRefs::R
     var $t12: &mut TestEliminateMutRefs::R
     var $t13: u64
     var $t14: bool
     var $t15: TestEliminateMutRefs::R
  0: $t14 := move($t0)
  1: $t4 := 3
  2: $t5 := pack TestEliminateMutRefs::R($t4)
  3: $t1 := $t5
  4: $t6 := 4
  5: $t7 := pack TestEliminateMutRefs::R($t6)
  6: $t2 := $t7
  7: $t8 := borrow_local($t1)
  8: $t3 := $t8
  9: $t9 := copy($t14)
 10: if ($t9) goto 13 else goto 11
 11: label L1
 12: goto 18
 13: label L0
 14: $t10 := move($t3)
 15: destroy($t10)
 16: $t11 := borrow_local($t2)
 17: $t3 := $t11
 18: label L2
 19: $t12 := move($t3)
 20: $t13 := 0
 21: $t15 := read_ref($t12)
 22: $t15 := TestEliminateMutRefs::test3($t15, $t13)
 23: write_ref($t12, $t15)
 24: return ()
}


[variant baseline]
fun TestEliminateMutRefs::test8($t0|b: bool, $t1|n: u64, $t2|r_ref: TestEliminateMutRefs::R): TestEliminateMutRefs::R {
     var $t3|r1: TestEliminateMutRefs::R
     var $t4|r2: TestEliminateMutRefs::R
     var $t5|t_ref: &mut TestEliminateMutRefs::R
     var $t6: u64
     var $t7: TestEliminateMutRefs::R
     var $t8: u64
     var $t9: TestEliminateMutRefs::R
     var $t10: &mut TestEliminateMutRefs::R
     var $t11: u64
     var $t12: u64
     var $t13: bool
     var $t14: &mut TestEliminateMutRefs::R
     var $t15: u64
     var $t16: u64
     var $t17: u64
     var $t18: u64
     var $t19: bool
     var $t20: &mut TestEliminateMutRefs::R
     var $t21: &mut TestEliminateMutRefs::R
     var $t22: u64
     var $t23: u64
     var $t24: u64
     var $t25: bool
     var $t26: &mut TestEliminateMutRefs::R
     var $t27: &mut TestEliminateMutRefs::R
     var $t28: u64
     var $t29: &mut TestEliminateMutRefs::R
     var $t30: &mut TestEliminateMutRefs::R
     var $t31: u64
     var $t32: bool
     var $t33: u64
     var $t34: TestEliminateMutRefs::R
     var $t35: &mut TestEliminateMutRefs::R
     var $t36: TestEliminateMutRefs::R
  0: $t32 := move($t0)
  1: $t33 := move($t1)
  2: $t34 := move($t2)
  3: $t35 := borrow_local($t34)
  4: $t6 := 3
  5: $t7 := pack TestEliminateMutRefs::R($t6)
  6: $t3 := $t7
  7: $t8 := 4
  8: $t9 := pack TestEliminateMutRefs::R($t8)
  9: $t4 := $t9
 10: $t10 := borrow_local($t4)
 11: $t5 := $t10
 12: label L7
 13: $t11 := 0
 14: $t12 := copy($t33)
 15: $t13 := <($t11, $t12)
 16: if ($t13) goto 19 else goto 17
 17: label L1
 18: goto 43
 19: label L0
 20: $t14 := move($t5)
 21: destroy($t14)
 22: $t15 := copy($t33)
 23: $t16 := 2
 24: $t17 := /($t15, $t16)
 25: $t18 := 0
 26: $t19 := ==($t17, $t18)
 27: if ($t19) goto 30 else goto 28
 28: label L4
 29: goto 34
 30: label L3
 31: $t20 := borrow_local($t3)
 32: $t5 := $t20
 33: goto 37
 34: label L5
 35: $t21 := borrow_local($t4)
 36: $t5 := $t21
 37: label L6
 38: $t22 := copy($t33)
 39: $t23 := 1
 40: $t24 := -($t22, $t23)
 41: $t33 := $t24
 42: goto 12
 43: label L2
 44: $t25 := copy($t32)
 45: if ($t25) goto 48 else goto 46
 46: label L9
 47: goto 57
 48: label L8
 49: $t26 := move($t5)
 50: destroy($t26)
 51: $t27 := move($t35)
 52: $t28 := 0
 53: $t36 := read_ref($t27)
 54: $t36 := TestEliminateMutRefs::test3($t36, $t28)
 55: write_ref($t27, $t36)
 56: goto 65
 57: label L10
 58: $t29 := move($t35)
 59: destroy($t29)
 60: $t30 := move($t5)
 61: $t31 := 0
 62: $t36 := read_ref($t30)
 63: $t36 := TestEliminateMutRefs::test3($t36, $t31)
 64: write_ref($t30, $t36)
 65: label L11
 66: return $t34
}
