============ initial translation from Move ================

fun TestBorrow::test1(): TestBorrow::R {
     var r: TestBorrow::R
     var r_ref: &mut TestBorrow::R
     var x_ref: &mut u64
     var $t3: u64
     var $t4: TestBorrow::R
     var $t5: &mut TestBorrow::R
     var $t6: &mut TestBorrow::R
     var $t7: &mut u64
     var $t8: u64
     var $t9: &mut u64
     var $t10: TestBorrow::R
  0: $t3 := 3
  1: $t4 := pack TestBorrow::R($t3)
  2: r := $t4
  3: $t5 := borrow_local(r)
  4: r_ref := $t5
  5: $t6 := move(r_ref)
  6: $t7 := borrow_field<TestBorrow::R>.x($t6)
  7: x_ref := $t7
  8: $t8 := 0
  9: $t9 := move(x_ref)
 10: write_ref($t9, $t8)
 11: $t10 := move(r)
 12: return $t10
}


fun TestBorrow::test2(x_ref: &mut u64, v: u64) {
     var $t2: u64
     var $t3: &mut u64
  0: $t2 := copy(v)
  1: $t3 := move(x_ref)
  2: write_ref($t3, $t2)
  3: return ()
}


pub fun TestBorrow::test3(r_ref: &mut TestBorrow::R, v: u64) {
     var x_ref: &mut u64
     var $t3: &mut TestBorrow::R
     var $t4: &mut u64
     var $t5: &mut u64
     var $t6: u64
  0: $t3 := move(r_ref)
  1: $t4 := borrow_field<TestBorrow::R>.x($t3)
  2: x_ref := $t4
  3: $t5 := move(x_ref)
  4: $t6 := copy(v)
  5: TestBorrow::test2($t5, $t6)
  6: return ()
}


fun TestBorrow::test4(): TestBorrow::R {
     var r: TestBorrow::R
     var r_ref: &mut TestBorrow::R
     var $t2: u64
     var $t3: TestBorrow::R
     var $t4: &mut TestBorrow::R
     var $t5: &mut TestBorrow::R
     var $t6: u64
     var $t7: TestBorrow::R
  0: $t2 := 3
  1: $t3 := pack TestBorrow::R($t2)
  2: r := $t3
  3: $t4 := borrow_local(r)
  4: r_ref := $t4
  5: $t5 := move(r_ref)
  6: $t6 := 0
  7: TestBorrow::test3($t5, $t6)
  8: $t7 := move(r)
  9: return $t7
}


pub fun TestBorrow::test5(r_ref: &mut TestBorrow::R): &mut u64 {
     var $t1: &mut TestBorrow::R
     var $t2: &mut u64
  0: $t1 := move(r_ref)
  1: $t2 := borrow_field<TestBorrow::R>.x($t1)
  2: return $t2
}


fun TestBorrow::test6(): TestBorrow::R {
     var r: TestBorrow::R
     var r_ref: &mut TestBorrow::R
     var x_ref: &mut u64
     var $t3: u64
     var $t4: TestBorrow::R
     var $t5: &mut TestBorrow::R
     var $t6: &mut TestBorrow::R
     var $t7: &mut u64
     var $t8: &mut u64
     var $t9: u64
     var $t10: TestBorrow::R
  0: $t3 := 3
  1: $t4 := pack TestBorrow::R($t3)
  2: r := $t4
  3: $t5 := borrow_local(r)
  4: r_ref := $t5
  5: $t6 := move(r_ref)
  6: $t7 := TestBorrow::test5($t6)
  7: x_ref := $t7
  8: $t8 := move(x_ref)
  9: $t9 := 0
 10: TestBorrow::test2($t8, $t9)
 11: $t10 := move(r)
 12: return $t10
}


fun TestBorrow::test7(b: bool) {
     var r1: TestBorrow::R
     var r2: TestBorrow::R
     var r_ref: &mut TestBorrow::R
     var $t4: u64
     var $t5: TestBorrow::R
     var $t6: u64
     var $t7: TestBorrow::R
     var $t8: &mut TestBorrow::R
     var $t9: bool
     var $t10: &mut TestBorrow::R
     var $t11: &mut TestBorrow::R
     var $t12: &mut TestBorrow::R
     var $t13: u64
  0: $t4 := 3
  1: $t5 := pack TestBorrow::R($t4)
  2: r1 := $t5
  3: $t6 := 4
  4: $t7 := pack TestBorrow::R($t6)
  5: r2 := $t7
  6: $t8 := borrow_local(r1)
  7: r_ref := $t8
  8: $t9 := copy(b)
  9: if ($t9) goto L0 else goto L1
 10: L1:
 11: goto L2
 12: L0:
 13: $t10 := move(r_ref)
 14: destroy($t10)
 15: $t11 := borrow_local(r2)
 16: r_ref := $t11
 17: goto L2
 18: L2:
 19: $t12 := move(r_ref)
 20: $t13 := 0
 21: TestBorrow::test3($t12, $t13)
 22: return ()
}


fun TestBorrow::test8(b: bool, n: u64, r_ref: &mut TestBorrow::R) {
     var r1: TestBorrow::R
     var r2: TestBorrow::R
     var t_ref: &mut TestBorrow::R
     var $t6: u64
     var $t7: TestBorrow::R
     var $t8: u64
     var $t9: TestBorrow::R
     var $t10: &mut TestBorrow::R
     var $t11: u64
     var $t12: u64
     var $t13: bool
     var $t14: &mut TestBorrow::R
     var $t15: u64
     var $t16: u64
     var $t17: u64
     var $t18: u64
     var $t19: bool
     var $t20: &mut TestBorrow::R
     var $t21: &mut TestBorrow::R
     var $t22: u64
     var $t23: u64
     var $t24: u64
     var $t25: bool
     var $t26: &mut TestBorrow::R
     var $t27: &mut TestBorrow::R
     var $t28: u64
     var $t29: &mut TestBorrow::R
     var $t30: &mut TestBorrow::R
     var $t31: u64
  0: $t6 := 3
  1: $t7 := pack TestBorrow::R($t6)
  2: r1 := $t7
  3: $t8 := 4
  4: $t9 := pack TestBorrow::R($t8)
  5: r2 := $t9
  6: $t10 := borrow_local(r2)
  7: t_ref := $t10
  8: goto L7
  9: L7:
 10: $t11 := 0
 11: $t12 := copy(n)
 12: $t13 := <($t11, $t12)
 13: if ($t13) goto L0 else goto L1
 14: L1:
 15: goto L2
 16: L0:
 17: $t14 := move(t_ref)
 18: destroy($t14)
 19: $t15 := copy(n)
 20: $t16 := 2
 21: $t17 := /($t15, $t16)
 22: $t18 := 0
 23: $t19 := ==($t17, $t18)
 24: if ($t19) goto L3 else goto L4
 25: L4:
 26: goto L5
 27: L3:
 28: $t20 := borrow_local(r1)
 29: t_ref := $t20
 30: goto L6
 31: L5:
 32: $t21 := borrow_local(r2)
 33: t_ref := $t21
 34: goto L6
 35: L6:
 36: $t22 := copy(n)
 37: $t23 := 1
 38: $t24 := -($t22, $t23)
 39: n := $t24
 40: goto L7
 41: L2:
 42: $t25 := copy(b)
 43: if ($t25) goto L8 else goto L9
 44: L9:
 45: goto L10
 46: L8:
 47: $t26 := move(t_ref)
 48: destroy($t26)
 49: $t27 := move(r_ref)
 50: $t28 := 0
 51: TestBorrow::test3($t27, $t28)
 52: goto L11
 53: L10:
 54: $t29 := move(r_ref)
 55: destroy($t29)
 56: $t30 := move(t_ref)
 57: $t31 := 0
 58: TestBorrow::test3($t30, $t31)
 59: goto L11
 60: L11:
 61: return ()
}

============ after pipeline `borrow` ================

fun TestBorrow::test1(): TestBorrow::R {
     var r: TestBorrow::R
     var r_ref: &mut TestBorrow::R
     var x_ref: &mut u64
     var $t3: u64
     var $t4: u64
  0: $t3 := 3
  1: r := pack TestBorrow::R($t3)
  2: r_ref := borrow_local(r)
     // live_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}
  3: x_ref := borrow_field<TestBorrow::R>.x(r_ref)
     // live_nodes: Reference(x_ref)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}, Reference(r_ref) -> {Reference(x_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}, Reference(x_ref) -> {Reference(r_ref)}
  4: $t4 := 0
     // live_nodes: Reference(x_ref)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}, Reference(r_ref) -> {Reference(x_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}, Reference(x_ref) -> {Reference(r_ref)}
  5: write_ref(x_ref, $t4)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}, Reference(r_ref) -> {Reference(x_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}, Reference(x_ref) -> {Reference(r_ref)}
  6: return r
}


fun TestBorrow::test2(x_ref: u64, v: u64): u64 {
     var $t2: u64
     var $t3: u64
     var $t4: &mut u64
     // live_nodes: LocalRoot(x_ref), LocalRoot(v)
     // unchecked_nodes: LocalRoot(x_ref)
  0: $t2 := move(x_ref)
     // live_nodes: LocalRoot(v), LocalRoot($t2)
     // unchecked_nodes: LocalRoot($t2)
     // moved_nodes: LocalRoot(x_ref)
  1: $t3 := move(v)
     // live_nodes: LocalRoot($t2), LocalRoot($t3)
     // unchecked_nodes: LocalRoot($t2)
     // moved_nodes: LocalRoot(x_ref), LocalRoot(v)
  2: $t4 := borrow_local($t2)
     // live_nodes: LocalRoot($t2), LocalRoot($t3), Reference($t4)
     // unchecked_nodes: LocalRoot($t2), Reference($t4)
     // moved_nodes: LocalRoot(x_ref), LocalRoot(v)
     // borrowed_by: LocalRoot($t2) -> {Reference($t4)}
     // borrows_from: Reference($t4) -> {LocalRoot($t2)}
  3: write_ref($t4, $t3)
     // live_nodes: LocalRoot($t2), LocalRoot($t3)
     // unchecked_nodes: LocalRoot($t2), Reference($t4)
     // moved_nodes: LocalRoot(x_ref), LocalRoot(v)
     // borrowed_by: LocalRoot($t2) -> {Reference($t4)}
     // borrows_from: Reference($t4) -> {LocalRoot($t2)}
  4: return $t2
}


pub fun TestBorrow::test3(r_ref: TestBorrow::R, v: u64): TestBorrow::R {
     var x_ref: &mut u64
     var $t3: TestBorrow::R
     var $t4: u64
     var $t5: &mut TestBorrow::R
     var $t6: u64
     // live_nodes: LocalRoot(r_ref), LocalRoot(v)
  0: $t3 := move(r_ref)
     // live_nodes: LocalRoot(v), LocalRoot($t3)
     // moved_nodes: LocalRoot(r_ref)
  1: $t4 := move(v)
     // live_nodes: LocalRoot($t3), LocalRoot($t4)
     // moved_nodes: LocalRoot(r_ref), LocalRoot(v)
  2: $t5 := borrow_local($t3)
     // live_nodes: LocalRoot($t3), LocalRoot($t4), Reference($t5)
     // moved_nodes: LocalRoot(r_ref), LocalRoot(v)
     // borrowed_by: LocalRoot($t3) -> {Reference($t5)}
     // borrows_from: Reference($t5) -> {LocalRoot($t3)}
  3: x_ref := borrow_field<TestBorrow::R>.x($t5)
     // live_nodes: LocalRoot($t3), LocalRoot($t4), Reference(x_ref)
     // moved_nodes: LocalRoot(r_ref), LocalRoot(v)
     // borrowed_by: LocalRoot($t3) -> {Reference($t5)}, Reference($t5) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t5)}, Reference($t5) -> {LocalRoot($t3)}
  4: $t6 := read_ref(x_ref)
     // live_nodes: LocalRoot($t3), LocalRoot($t4), Reference(x_ref)
     // moved_nodes: LocalRoot(r_ref), LocalRoot(v)
     // borrowed_by: LocalRoot($t3) -> {Reference($t5)}, Reference($t5) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t5)}, Reference($t5) -> {LocalRoot($t3)}
  5: $t6 := TestBorrow::test2($t6, $t4)
     // live_nodes: LocalRoot($t3), LocalRoot($t4), Reference(x_ref)
     // moved_nodes: LocalRoot(r_ref), LocalRoot(v)
     // borrowed_by: LocalRoot($t3) -> {Reference($t5)}, Reference($t5) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t5)}, Reference($t5) -> {LocalRoot($t3)}
  6: write_ref(x_ref, $t6)
     // live_nodes: LocalRoot($t3), LocalRoot($t4)
     // moved_nodes: LocalRoot(r_ref), LocalRoot(v)
     // borrowed_by: LocalRoot($t3) -> {Reference($t5)}, Reference($t5) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t5)}, Reference($t5) -> {LocalRoot($t3)}
  7: return $t3
}


fun TestBorrow::test4(): TestBorrow::R {
     var r: TestBorrow::R
     var r_ref: &mut TestBorrow::R
     var $t2: u64
     var $t3: u64
     var $t4: TestBorrow::R
  0: $t2 := 3
  1: r := pack TestBorrow::R($t2)
  2: r_ref := borrow_local(r)
     // live_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}
  3: $t3 := 0
     // live_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}
  4: $t4 := read_ref(r_ref)
     // live_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}
  5: $t4 := TestBorrow::test3($t4, $t3)
     // live_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}
  6: write_ref(r_ref, $t4)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}
  7: return r
}


pub fun TestBorrow::test5(r_ref: TestBorrow::R): (&mut u64, TestBorrow::R) {
     var $t1: TestBorrow::R
     var $t2: &mut TestBorrow::R
     var $t3: &mut u64
     // live_nodes: LocalRoot(r_ref)
     // unchecked_nodes: LocalRoot(r_ref)
  0: $t1 := move(r_ref)
     // live_nodes: LocalRoot($t1)
     // unchecked_nodes: LocalRoot($t1)
     // moved_nodes: LocalRoot(r_ref)
  1: $t2 := borrow_local($t1)
     // live_nodes: LocalRoot($t1), Reference($t2)
     // unchecked_nodes: LocalRoot($t1), Reference($t2)
     // moved_nodes: LocalRoot(r_ref)
     // borrowed_by: LocalRoot($t1) -> {Reference($t2)}
     // borrows_from: Reference($t2) -> {LocalRoot($t1)}
  2: $t3 := borrow_field<TestBorrow::R>.x($t2)
     // live_nodes: LocalRoot($t1), Reference($t3)
     // unchecked_nodes: LocalRoot($t1), Reference($t2), Reference($t3)
     // moved_nodes: LocalRoot(r_ref)
     // borrowed_by: LocalRoot($t1) -> {Reference($t2)}, Reference($t2) -> {Reference($t3)}
     // borrows_from: Reference($t2) -> {LocalRoot($t1)}, Reference($t3) -> {Reference($t2)}
  3: return ($t3, $t1)
}


fun TestBorrow::test6(): TestBorrow::R {
     var r: TestBorrow::R
     var r_ref: &mut TestBorrow::R
     var x_ref: &mut u64
     var $t3: u64
     var $t4: &mut TestBorrow::R
     var $t5: TestBorrow::R
     var $t6: &mut u64
     var $t7: u64
     var $t8: u64
  0: $t3 := 3
  1: r := pack TestBorrow::R($t3)
  2: r_ref := borrow_local(r)
     // live_nodes: Reference(r_ref)
     // spliced_nodes: Reference($t4)
     // borrowed_by: LocalRoot(r) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r)}
  3: $t4 := move(r_ref)
     // live_nodes: Reference($t4)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}
     // borrows_from: Reference($t4) -> {LocalRoot(r)}
  4: $t5 := read_ref(r_ref)
     // live_nodes: Reference($t4)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}
     // borrows_from: Reference($t4) -> {LocalRoot(r)}
  5: ($t6, $t5) := TestBorrow::test5($t5)
     // live_nodes: Reference($t4)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}
     // borrows_from: Reference($t4) -> {LocalRoot(r)}
  6: write_ref(r_ref, $t5)
     // live_nodes: Reference($t4)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}
     // borrows_from: Reference($t4) -> {LocalRoot(r)}
  7: splice[0 -> $t4]($t6)
     // live_nodes: Reference($t6)
     // unchecked_nodes: Reference($t6)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}, Reference($t4) -> {Reference($t6)}
     // borrows_from: Reference($t4) -> {LocalRoot(r)}, Reference($t6) -> {Reference($t4)}
  8: x_ref := $t6
     // live_nodes: Reference(x_ref)
     // unchecked_nodes: Reference(x_ref)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref), Reference($t6)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}, Reference($t4) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t4)}, Reference($t4) -> {LocalRoot(r)}
  9: $t7 := 0
     // live_nodes: Reference(x_ref)
     // unchecked_nodes: Reference(x_ref)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref), Reference($t6)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}, Reference($t4) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t4)}, Reference($t4) -> {LocalRoot(r)}
 10: $t8 := read_ref(x_ref)
     // live_nodes: Reference(x_ref)
     // unchecked_nodes: Reference(x_ref)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref), Reference($t6)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}, Reference($t4) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t4)}, Reference($t4) -> {LocalRoot(r)}
 11: $t8 := TestBorrow::test2($t8, $t7)
     // live_nodes: Reference(x_ref)
     // unchecked_nodes: Reference(x_ref)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref), Reference($t6)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}, Reference($t4) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t4)}, Reference($t4) -> {LocalRoot(r)}
 12: write_ref(x_ref, $t8)
     // unchecked_nodes: Reference(x_ref)
     // spliced_nodes: Reference($t4)
     // moved_nodes: Reference(r_ref), Reference($t6)
     // borrowed_by: LocalRoot(r) -> {Reference($t4)}, Reference($t4) -> {Reference(x_ref)}
     // borrows_from: Reference(x_ref) -> {Reference($t4)}, Reference($t4) -> {LocalRoot(r)}
 13: return r
}


fun TestBorrow::test7(b: bool) {
     var r1: TestBorrow::R
     var r2: TestBorrow::R
     var r_ref: &mut TestBorrow::R
     var $t4: bool
     var $t5: u64
     var $t6: u64
     var $t7: u64
     var $t8: TestBorrow::R
     // live_nodes: LocalRoot(b)
  0: $t4 := move(b)
     // live_nodes: LocalRoot($t4)
     // moved_nodes: LocalRoot(b)
  1: $t5 := 3
     // live_nodes: LocalRoot($t4)
     // moved_nodes: LocalRoot(b)
  2: r1 := pack TestBorrow::R($t5)
     // live_nodes: LocalRoot($t4)
     // moved_nodes: LocalRoot(b)
  3: $t6 := 4
     // live_nodes: LocalRoot($t4)
     // moved_nodes: LocalRoot(b)
  4: r2 := pack TestBorrow::R($t6)
     // live_nodes: LocalRoot($t4)
     // moved_nodes: LocalRoot(b)
  5: r_ref := borrow_local(r1)
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1)}
  6: if ($t4) goto L0 else goto L1
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1)}
  7: L1:
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1)}
  8: goto L2
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1)}
  9: L0:
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1)}
 10: destroy(r_ref)
     // live_nodes: LocalRoot($t4)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1)}
 11: r_ref := borrow_local(r2)
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}, LocalRoot(r2) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1), LocalRoot(r2)}
 12: goto L2
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}, LocalRoot(r2) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1), LocalRoot(r2)}
 13: L2:
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}, LocalRoot(r2) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1), LocalRoot(r2)}
 14: $t7 := 0
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}, LocalRoot(r2) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1), LocalRoot(r2)}
 15: $t8 := read_ref(r_ref)
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}, LocalRoot(r2) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1), LocalRoot(r2)}
 16: $t8 := TestBorrow::test3($t8, $t7)
     // live_nodes: LocalRoot($t4), Reference(r_ref)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}, LocalRoot(r2) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1), LocalRoot(r2)}
 17: write_ref(r_ref, $t8)
     // live_nodes: LocalRoot($t4)
     // moved_nodes: LocalRoot(b)
     // borrowed_by: LocalRoot(r1) -> {Reference(r_ref)}, LocalRoot(r2) -> {Reference(r_ref)}
     // borrows_from: Reference(r_ref) -> {LocalRoot(r1), LocalRoot(r2)}
 18: return ()
}


fun TestBorrow::test8(b: bool, n: u64, r_ref: TestBorrow::R): TestBorrow::R {
     var r1: TestBorrow::R
     var r2: TestBorrow::R
     var t_ref: &mut TestBorrow::R
     var $t6: bool
     var $t7: TestBorrow::R
     var $t8: &mut TestBorrow::R
     var $t9: u64
     var $t10: u64
     var $t11: u64
     var $t12: bool
     var $t13: u64
     var $t14: u64
     var $t15: u64
     var $t16: u64
     var $t17: bool
     var $t18: u64
     var $t19: u64
     var $t20: TestBorrow::R
     var $t21: u64
     // live_nodes: LocalRoot(b), LocalRoot(n), LocalRoot(r_ref)
     // unchecked_nodes: LocalRoot(r_ref)
  0: $t6 := move(b)
     // live_nodes: LocalRoot(n), LocalRoot(r_ref), LocalRoot($t6)
     // unchecked_nodes: LocalRoot(r_ref)
     // moved_nodes: LocalRoot(b)
  1: $t7 := move(r_ref)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7)
     // unchecked_nodes: LocalRoot($t7)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
  2: $t8 := borrow_local($t7)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference($t8) -> {LocalRoot($t7)}
  3: $t9 := 3
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference($t8) -> {LocalRoot($t7)}
  4: r1 := pack TestBorrow::R($t9)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference($t8) -> {LocalRoot($t7)}
  5: $t10 := 4
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference($t8) -> {LocalRoot($t7)}
  6: r2 := pack TestBorrow::R($t10)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference($t8) -> {LocalRoot($t7)}
  7: t_ref := borrow_local(r2)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
  8: goto L7
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
  9: L7:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 10: $t11 := 0
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 11: $t12 := <($t11, $t13)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 12: if ($t12) goto L0 else goto L1
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 13: L1:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 14: goto L2
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 15: L0:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 16: destroy(t_ref)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 17: $t14 := 2
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 18: $t15 := /($t13, $t14)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 19: $t16 := 0
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 20: $t17 := ==($t15, $t16)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 21: if ($t17) goto L3 else goto L4
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 22: L4:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 23: goto L5
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 24: L3:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 25: t_ref := borrow_local(r1)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 26: goto L6
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 27: L5:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 28: t_ref := borrow_local(r2)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 29: goto L6
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 30: L6:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 31: $t18 := 1
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 32: $t13 := -($t13, $t18)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 33: goto L7
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 34: L2:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 35: if ($t6) goto L8 else goto L9
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 36: L9:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 37: goto L10
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 38: L8:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 39: destroy(t_ref)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 40: $t19 := 0
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 41: $t20 := read_ref($t8)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 42: $t20 := TestBorrow::test3($t20, $t19)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 43: write_ref($t8, $t20)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 44: goto L11
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 45: L10:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref), Reference($t8)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 46: destroy($t8)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 47: $t21 := 0
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 48: $t20 := read_ref(t_ref)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 49: $t20 := TestBorrow::test3($t20, $t21)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7), Reference(t_ref)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 50: write_ref(t_ref, $t20)
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 51: goto L11
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 52: L11:
     // live_nodes: LocalRoot(n), LocalRoot($t6), LocalRoot($t7)
     // unchecked_nodes: LocalRoot($t7), Reference($t8)
     // moved_nodes: LocalRoot(b), LocalRoot(r_ref)
     // borrowed_by: LocalRoot(r1) -> {Reference(t_ref)}, LocalRoot(r2) -> {Reference(t_ref)}, LocalRoot($t7) -> {Reference($t8)}
     // borrows_from: Reference(t_ref) -> {LocalRoot(r1), LocalRoot(r2)}, Reference($t8) -> {LocalRoot($t7)}
 53: return $t7
}
