error[E07004]: invalid return of locally borrowed state
   ┌─ tests/move_check/borrows/return_borrowed_local_invalid.move:19:9
   │  
19 │ ╭         (&mut v1,
20 │ │         &v2,
21 │ │         id_mut(&mut v3),
22 │ │         id(&v4),
23 │ │         &mut s1.f,
   │ │         --------- It is still being mutably borrowed by this reference
24 │ │         &s2.f,
25 │ │         id_mut(&mut s3.f),
26 │ │         id(&s4.f))
   │ ╰──────────────────^ Invalid return. Local variable 's1' is still being borrowed.

error[E07004]: invalid return of locally borrowed state
   ┌─ tests/move_check/borrows/return_borrowed_local_invalid.move:19:9
   │  
19 │ ╭         (&mut v1,
20 │ │         &v2,
21 │ │         id_mut(&mut v3),
22 │ │         id(&v4),
23 │ │         &mut s1.f,
24 │ │         &s2.f,
   │ │         ----- It is still being borrowed by this reference
25 │ │         id_mut(&mut s3.f),
26 │ │         id(&s4.f))
   │ ╰──────────────────^ Invalid return. Local variable 's2' is still being borrowed.

error[E07004]: invalid return of locally borrowed state
   ┌─ tests/move_check/borrows/return_borrowed_local_invalid.move:19:9
   │  
19 │ ╭         (&mut v1,
20 │ │         &v2,
21 │ │         id_mut(&mut v3),
22 │ │         id(&v4),
   · │
25 │ │         id_mut(&mut s3.f),
   │ │         ----------------- It is still being mutably borrowed by this reference
26 │ │         id(&s4.f))
   │ ╰──────────────────^ Invalid return. Local variable 's3' is still being borrowed.

error[E07004]: invalid return of locally borrowed state
   ┌─ tests/move_check/borrows/return_borrowed_local_invalid.move:19:9
   │  
19 │ ╭         (&mut v1,
20 │ │         &v2,
21 │ │         id_mut(&mut v3),
22 │ │         id(&v4),
   · │
25 │ │         id_mut(&mut s3.f),
26 │ │         id(&s4.f))
   │ │         --------- It is still being borrowed by this reference
   │ ╰──────────────────^ Invalid return. Local variable 's4' is still being borrowed.

error[E07004]: invalid return of locally borrowed state
   ┌─ tests/move_check/borrows/return_borrowed_local_invalid.move:19:9
   │  
19 │ ╭         (&mut v1,
   │            ------- It is still being mutably borrowed by this reference
20 │ │         &v2,
21 │ │         id_mut(&mut v3),
22 │ │         id(&v4),
   · │
25 │ │         id_mut(&mut s3.f),
26 │ │         id(&s4.f))
   │ ╰──────────────────^ Invalid return. Local variable 'v1' is still being borrowed.

error[E07004]: invalid return of locally borrowed state
   ┌─ tests/move_check/borrows/return_borrowed_local_invalid.move:19:9
   │  
19 │ ╭         (&mut v1,
20 │ │         &v2,
   │ │         --- It is still being borrowed by this reference
21 │ │         id_mut(&mut v3),
22 │ │         id(&v4),
   · │
25 │ │         id_mut(&mut s3.f),
26 │ │         id(&s4.f))
   │ ╰──────────────────^ Invalid return. Local variable 'v2' is still being borrowed.

error[E07004]: invalid return of locally borrowed state
   ┌─ tests/move_check/borrows/return_borrowed_local_invalid.move:19:9
   │  
19 │ ╭         (&mut v1,
20 │ │         &v2,
21 │ │         id_mut(&mut v3),
   │ │         --------------- It is still being mutably borrowed by this reference
22 │ │         id(&v4),
   · │
25 │ │         id_mut(&mut s3.f),
26 │ │         id(&s4.f))
   │ ╰──────────────────^ Invalid return. Local variable 'v3' is still being borrowed.

error[E07004]: invalid return of locally borrowed state
   ┌─ tests/move_check/borrows/return_borrowed_local_invalid.move:19:9
   │  
19 │ ╭         (&mut v1,
20 │ │         &v2,
21 │ │         id_mut(&mut v3),
22 │ │         id(&v4),
   │ │         ------- It is still being borrowed by this reference
   · │
25 │ │         id_mut(&mut s3.f),
26 │ │         id(&s4.f))
   │ ╰──────────────────^ Invalid return. Local variable 'v4' is still being borrowed.

