error: expected `bool` but found `num` in expression

   ┌── tests/sources/invariants_err.move:9:15 ───
   │
 9 │     invariant x + 1;
   │               ^^^^^
   │

error: `old(..)` expression not allowed in this context

    ┌── tests/sources/invariants_err.move:11:15 ───
    │
 11 │     invariant old(x) > 0;
    │               ^^^^^^
    │

error: `old(..old(..)..)` not allowed

    ┌── tests/sources/invariants_err.move:13:26 ───
    │
 13 │     invariant update old(old(x)) > 0;
    │                          ^^^^^^
    │

error: data invariants cannot depend on global state (directly or indirectly uses a global spec var or resource storage).

    ┌── tests/sources/invariants_err.move:15:5 ───
    │
 15 │     invariant exists<S>(0x0);
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^
    │

error: data invariants cannot depend on global state (directly or indirectly uses a global spec var or resource storage).

    ┌── tests/sources/invariants_err.move:16:5 ───
    │
 16 │     invariant global<S>(0x0).x == x;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    │

error: data invariants cannot depend on global state (directly or indirectly uses a global spec var or resource storage).

    ┌── tests/sources/invariants_err.move:17:5 ───
    │
 17 │     invariant sender() == 0x0;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    │

error: data invariants cannot depend on global state (directly or indirectly uses a global spec var or resource storage).

    ┌── tests/sources/invariants_err.move:18:5 ───
    │
 18 │     invariant spec_var > 0;
    │     ^^^^^^^^^^^^^^^^^^^^^^^
    │

error: data invariants cannot depend on global state (directly or indirectly uses a global spec var or resource storage).

    ┌── tests/sources/invariants_err.move:20:5 ───
    │
 20 │     invariant rec_fun(true);
    │     ^^^^^^^^^^^^^^^^^^^^^^^^
    │
