Command `sandbox publish src/modules -v`:
Compiling Move modules...
Found and compiled 1 modules
Publishing a new module 00000000000000000000000000000002::Events (wrote 368 bytes)
Wrote 368 bytes of module ID's and code
Command `sandbox run src/scripts/emit.move --signers 0xA --args 5 -v`:
Compiling transaction script...
Emitted 1 events:
Emitted [5, 0, 0, 0, 0, 0, 0, 0] as the 0th event to stream [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]
Changed resource(s) under 1 address(es):
  Changed 2 resource(s) under address 0000000000000000000000000000000A:
    Added type 0x1::Event::EventHandleGenerator: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10] (wrote 69 bytes)
    Added type 0x2::Events::Handle: [1, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10] (wrote 65 bytes)
Wrote 134 bytes of resource ID's and data
Command `sandbox view storage/0x0000000000000000000000000000000A/events/0.bcs`:
copy drop store 0x2::Events::AnEvent {
    i: 5
}
Command `sandbox run src/scripts/emit.move --signers 0xA --args 6 -v`:
Compiling transaction script...
Emitted 1 events:
Emitted [6, 0, 0, 0, 0, 0, 0, 0] as the 1th event to stream [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 0000000000000000000000000000000A:
    Changed type 0x2::Events::Handle: [2, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10] (wrote 65 bytes)
Wrote 65 bytes of resource ID's and data
Command `sandbox view storage/0x0000000000000000000000000000000A/events/0.bcs`:
copy drop store 0x2::Events::AnEvent {
    i: 5
}
copy drop store 0x2::Events::AnEvent {
    i: 6
}
