Command `publish ../../../../../stdlib/modules`:
Compiling Move modules...
Found and compiled 41 modules
Committed changes.
Command `publish`:
Compiling Move modules...
Found and compiled 1 modules
Committed changes.
Command `run emit.move --signers 0xA --args 5`:
Compiling transaction script...
Emitted 1 events:
Emitted Value(Container(StructC(RefCell { value: [U64(5)] }))) as the 0th event to stream [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]
Changed resource(s) under 1 address(es):
  Changed 2 resource(s) under address 0000000000000000000000000000000a:
    Added type 00000000::Event::EventHandleGenerator: [U64(1), Address(00000000)]
    Added type 00000000::Events::Handle: [[U64(1), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]]
Committed changes.
Command `view move_data/0x0000000000000000000000000000000a/events/0`:
00000000::Events::AnEvent {
    i: 5
}
Command `run emit.move --signers 0xA --args 6`:
Compiling transaction script...
Emitted 1 events:
Emitted Value(Container(StructC(RefCell { value: [U64(6)] }))) as the 1th event to stream [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 0000000000000000000000000000000a:
    Changed type 00000000::Events::Handle: [[U64(2), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]]
Committed changes.
Command `view move_data/0x0000000000000000000000000000000a/events/0`:
00000000::Events::AnEvent {
    i: 5
}
00000000::Events::AnEvent {
    i: 6
}
