Command `publish src/modules -v`:
Compiling Move modules...
Found and compiled 1 modules
Command `run src/scripts/emit.move --signers 0xA --args 5 -v`:
Compiling transaction script...
Emitted 1 events:
Emitted Value(Container(StructC(RefCell { value: [U64(5)] }))) as the 0th event to stream [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]
Changed resource(s) under 1 address(es):
  Changed 2 resource(s) under address 0000000000000000000000000000000A:
    Added type 0x1::Event::EventHandleGenerator: [U64(1), Address(a)]
    Added type 0x2::Events::Handle: [[U64(1), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]]
Command `view storage/0x0000000000000000000000000000000A/events/0.bcs`:
0x2::Events::AnEvent {
    i: 5
}
Command `run src/scripts/emit.move --signers 0xA --args 6 -v`:
Compiling transaction script...
Emitted 1 events:
Emitted Value(Container(StructC(RefCell { value: [U64(6)] }))) as the 1th event to stream [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 0000000000000000000000000000000A:
    Changed type 0x2::Events::Handle: [[U64(2), [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]]
Command `view storage/0x0000000000000000000000000000000A/events/0.bcs`:
0x2::Events::AnEvent {
    i: 5
}
0x2::Events::AnEvent {
    i: 6
}
