Command `publish src/modules/`:
Command `publish M.move`:
Breaking change detected--publishing aborted. Re-run with --ignore-breaking-changes to publish anyway.
Layout API for structs of module 00000000000000000000000000000002::M has changed. Need to do a data migration of published structs
Command `run src/scripts/publish.move --signers 0xA`:
Command `doctor`:
Command `publish --ignore-breaking-changes M.move`:
Command `doctor`:
Error: Failed to deserialize resource "0x00000000000000000000000000000002::M::R.bcs" stored under address "0x0000000000000000000000000000000A"
