============ initial translation from Move ================

fun TestLiveVars::test1(r_ref: &TestLiveVars::R): u64 {
     var x_ref: &u64
     var $t2: &TestLiveVars::R
     var $t3: &u64
     var $t4: &u64
     var $t5: u64
  0: $t2 := move(r_ref)
  1: $t3 := borrow_field<TestLiveVars::R>.x($t2)
  2: x_ref := $t3
  3: $t4 := move(x_ref)
  4: $t5 := read_ref($t4)
  5: return $t5
}


fun TestLiveVars::test2(b: bool): u64 {
     var r1: TestLiveVars::R
     var r2: TestLiveVars::R
     var r_ref: &TestLiveVars::R
     var $t4: u64
     var $t5: TestLiveVars::R
     var $t6: u64
     var $t7: TestLiveVars::R
     var $t8: &TestLiveVars::R
     var $t9: bool
     var $t10: &TestLiveVars::R
     var $t11: &TestLiveVars::R
     var $t12: &TestLiveVars::R
     var $t13: u64
  0: $t4 := 3
  1: $t5 := pack TestLiveVars::R($t4)
  2: r1 := $t5
  3: $t6 := 4
  4: $t7 := pack TestLiveVars::R($t6)
  5: r2 := $t7
  6: $t8 := borrow_local(r1)
  7: r_ref := $t8
  8: $t9 := copy(b)
  9: if ($t9) goto L0 else goto L1
 10: L1:
 11: goto L2
 12: L0:
 13: $t10 := move(r_ref)
 14: destroy($t10)
 15: $t11 := borrow_local(r2)
 16: r_ref := $t11
 17: goto L2
 18: L2:
 19: $t12 := move(r_ref)
 20: $t13 := TestLiveVars::test1($t12)
 21: return $t13
}


fun TestLiveVars::test3(n: u64, r_ref: &TestLiveVars::R): u64 {
     var r1: TestLiveVars::R
     var r2: TestLiveVars::R
     var $t4: u64
     var $t5: TestLiveVars::R
     var $t6: u64
     var $t7: TestLiveVars::R
     var $t8: u64
     var $t9: u64
     var $t10: bool
     var $t11: &TestLiveVars::R
     var $t12: u64
     var $t13: u64
     var $t14: u64
     var $t15: u64
     var $t16: bool
     var $t17: &TestLiveVars::R
     var $t18: &TestLiveVars::R
     var $t19: u64
     var $t20: u64
     var $t21: u64
     var $t22: &TestLiveVars::R
     var $t23: u64
  0: $t4 := 3
  1: $t5 := pack TestLiveVars::R($t4)
  2: r1 := $t5
  3: $t6 := 4
  4: $t7 := pack TestLiveVars::R($t6)
  5: r2 := $t7
  6: goto L7
  7: L7:
  8: $t8 := 0
  9: $t9 := copy(n)
 10: $t10 := <($t8, $t9)
 11: if ($t10) goto L0 else goto L1
 12: L1:
 13: goto L2
 14: L0:
 15: $t11 := move(r_ref)
 16: destroy($t11)
 17: $t12 := copy(n)
 18: $t13 := 2
 19: $t14 := /($t12, $t13)
 20: $t15 := 0
 21: $t16 := ==($t14, $t15)
 22: if ($t16) goto L3 else goto L4
 23: L4:
 24: goto L5
 25: L3:
 26: $t17 := borrow_local(r1)
 27: r_ref := $t17
 28: goto L6
 29: L5:
 30: $t18 := borrow_local(r2)
 31: r_ref := $t18
 32: goto L6
 33: L6:
 34: $t19 := copy(n)
 35: $t20 := 1
 36: $t21 := -($t19, $t20)
 37: n := $t21
 38: goto L7
 39: L2:
 40: $t22 := move(r_ref)
 41: $t23 := TestLiveVars::test1($t22)
 42: return $t23
}

============ after pipeline `livevar` ================

fun TestLiveVars::test1(r_ref: &TestLiveVars::R): u64 {
     var x_ref: &u64
     var $t2: u64
     // live vars: r_ref
  0: x_ref := borrow_field<TestLiveVars::R>.x(r_ref)
     // live vars: x_ref
  1: $t2 := read_ref(x_ref)
     // live vars: $t2
  2: return $t2
}


fun TestLiveVars::test2(b: bool): u64 {
     var r1: TestLiveVars::R
     var r2: TestLiveVars::R
     var r_ref: &TestLiveVars::R
     var $t4: u64
     var $t5: u64
     var $t6: u64
     // live vars: b
  0: $t4 := 3
     // live vars: b, $t4
  1: r1 := pack TestLiveVars::R($t4)
     // live vars: b, r1
  2: $t5 := 4
     // live vars: b, r1, $t5
  3: r2 := pack TestLiveVars::R($t5)
     // live vars: b, r1, r2
  4: r_ref := borrow_local(r1)
     // live vars: b, r2, r_ref
  5: if (b) goto L0 else goto L1
     // live vars: r_ref
  6: L1:
     // live vars: r_ref
  7: goto L2
     // live vars: r2, r_ref
  8: L0:
     // live vars: r2, r_ref
  9: destroy(r_ref)
     // live vars: r2
 10: r_ref := borrow_local(r2)
     // live vars: r_ref
 11: goto L2
     // live vars: r_ref
 12: L2:
     // live vars: r_ref
 13: $t6 := TestLiveVars::test1(r_ref)
     // live vars: $t6
 14: return $t6
}


fun TestLiveVars::test3(n: u64, r_ref: &TestLiveVars::R): u64 {
     var r1: TestLiveVars::R
     var r2: TestLiveVars::R
     var $t4: u64
     var $t5: u64
     var $t6: u64
     var $t7: bool
     var $t8: u64
     var $t9: u64
     var $t10: u64
     var $t11: bool
     var $t12: u64
     var $t13: u64
     // live vars: n, r_ref
  0: $t4 := 3
     // live vars: n, r_ref, $t4
  1: r1 := pack TestLiveVars::R($t4)
     // live vars: n, r_ref, r1
  2: $t5 := 4
     // live vars: n, r_ref, r1, $t5
  3: r2 := pack TestLiveVars::R($t5)
     // live vars: n, r_ref, r1, r2
  4: goto L7
     // live vars: n, r_ref, r1, r2
  5: L7:
     // live vars: n, r_ref, r1, r2
  6: $t6 := 0
     // live vars: n, r_ref, r1, r2, $t6
  7: $t7 := <($t6, n)
     // live vars: n, r_ref, r1, r2, $t7
  8: if ($t7) goto L0 else goto L1
     // live vars: r_ref
  9: L1:
     // live vars: r_ref
 10: goto L2
     // live vars: n, r_ref, r1, r2
 11: L0:
     // live vars: n, r_ref, r1, r2
 12: destroy(r_ref)
     // live vars: n, r1, r2
 13: $t8 := 2
     // live vars: n, r1, r2, $t8
 14: $t9 := /(n, $t8)
     // live vars: n, r1, r2, $t9
 15: $t10 := 0
     // live vars: n, r1, r2, $t9, $t10
 16: $t11 := ==($t9, $t10)
     // live vars: n, r1, r2, $t11
 17: if ($t11) goto L3 else goto L4
     // live vars: n, r1, r2
 18: L4:
     // live vars: n, r1, r2
 19: goto L5
     // live vars: n, r1, r2
 20: L3:
     // live vars: n, r1, r2
 21: r_ref := borrow_local(r1)
     // live vars: n, r_ref, r1, r2
 22: goto L6
     // live vars: n, r1, r2
 23: L5:
     // live vars: n, r1, r2
 24: r_ref := borrow_local(r2)
     // live vars: n, r_ref, r1, r2
 25: goto L6
     // live vars: n, r_ref, r1, r2
 26: L6:
     // live vars: n, r_ref, r1, r2
 27: $t12 := 1
     // live vars: n, r_ref, r1, r2, $t12
 28: n := -(n, $t12)
     // live vars: n, r_ref, r1, r2
 29: goto L7
     // live vars: r_ref
 30: L2:
     // live vars: r_ref
 31: $t13 := TestLiveVars::test1(r_ref)
     // live vars: $t13
 32: return $t13
}
