Command `publish src1 -v`:
Compiling Move modules...
Found and compiled 4 modules
Publishing a new module 0x42::A
Publishing a new module 0x42::B
Publishing a new module 0x42::C
Publishing a new module 0x42::D
Command `publish src2 -v`:
Compiling Move modules...
Found and compiled 1 modules
Publishing module 0x42::C introduces cyclic dependencies.
Cycle detected: 0x42::C -> 0x42::A -> 0x42::B -> 0x42::C
Re-run with --ignore-breaking-changes to publish anyway.
Command `publish src2 -v --ignore-breaking-changes`:
Compiling Move modules...
Found and compiled 1 modules
Command `doctor`:
Error: Cyclic module dependencies are detected with module 0x42::A in the loop
