Command `publish src/modules/`:
Command `publish M.move`:
Breaking change detected--publishing aborted. Re-run with --ignore-breaking-changes to publish anyway.
Linking API for structs/functions of module 00000000000000000000000000000002::M has changed. Need to redeploy all dependent modules.
Command `doctor`:
Command `publish --ignore-breaking-changes M.move`:
Command `doctor`:
Error: Failed to link module ModuleId { address: 00000000000000000000000000000002, name: Identifier("M2") } against its dependencies
