ResolutionGraph {
    build_options: BuildConfig {
        dev_mode: true,
        generate_transaction_builders: false,
        generate_abis: false,
    },
    root_package: SourceManifest {
        package: PackageInfo {
            name: Identifier(
                "test",
            ),
            version: (
                0,
                0,
                0,
            ),
            authors: [],
            license: None,
        },
        addresses: Some(
            {
                Identifier(
                    "A",
                ): None,
            },
        ),
        dev_address_assignments: Some(
            {
                Identifier(
                    "A",
                ): 00000000000000000000000000000001,
            },
        ),
        build: None,
        dependencies: {},
        dev_dependencies: {},
    },
    graph: {
        14402189752926126668: [],
    },
    package_table: {
        Identifier(
            "test",
        ): ResolutionPackage {
            resolution_graph_index: 14402189752926126668,
            source_package: SourceManifest {
                package: PackageInfo {
                    name: Identifier(
                        "test",
                    ),
                    version: (
                        0,
                        0,
                        0,
                    ),
                    authors: [],
                    license: None,
                },
                addresses: Some(
                    {
                        Identifier(
                            "A",
                        ): None,
                    },
                ),
                dev_address_assignments: Some(
                    {
                        Identifier(
                            "A",
                        ): 00000000000000000000000000000001,
                    },
                ),
                build: None,
                dependencies: {},
                dev_dependencies: {},
            },
            package_path: "ELIDED_FOR_TEST",
            renaming: {},
            resolution_table: {
                Identifier(
                    "A",
                ): 00000000000000000000000000000001,
            },
        },
    },
}